#include "adlg.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* adlg_group = new tag_collection(
	"adlg",
	{
		
		block_tag("Death/Taunting Dialog",
		{
			undefined_tag("Situation", 9999),
			undefined_tag("Root Situation", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			long_tag("Unknown"),
			long_tag("Unknown"),
			undefined_tag("Spoken Dialog", 9999),
			block_tag("Unknown",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Unknown",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
		}),
		block_tag("Killing/Cautious Dialog",
		{
			short_tag("Dialogue Type"),
			short_tag("Vocalization Index"),
			undefined_tag("Vocalization Name", 9999),
			short_tag("Speaker Type"),
			short_tag("Flags"),
			short_tag("Listener/Target"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Hostility"),
			short_tag("Damage Type"),
			short_tag("Danger Level"),
			short_tag("Attitude"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Subject Actor Type"),
			short_tag("Cause Actor Type"),
			short_tag("Cause Type"),
			short_tag("Subject Type"),
			undefined_tag("Cause AI Type Name", 9999),
			short_tag("Spacial Relationship"),
			short_tag("Unknown"),
			undefined_tag("Subject AI Type Name", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Conditions"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Unknown",
		{
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Unknown",
		{
			long_tag("Unknown"),
		}),
	});
};
