#include "ai__.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* ai___group = new tag_collection(
	"ai__",
	{
		
		block_tag("Style Palette",
		{
			undefined_tag("Reference", 9999),
		}),
		block_tag("Squad Groups",
		{
			string_tag("Name"),
			short_tag("Parent Index"),
			short_tag("Initial Orders Index"),
		}),
		block_tag("Squads",
		{
			string_tag("Name"),
			undefined_tag("Flags", 9999),
			short_tag("Team"),
			short_tag("Parent Index"),
			long_tag("Squad Delay Time"),
			short_tag("Normal Diff Count"),
			short_tag("Insane Diff Count"),
			short_tag("Major Upgrade"),
			short_tag("Unknown"),
			short_tag("Vehicle Type Index"),
			short_tag("Character Type Index"),
			short_tag("Initial Zone Index"),
			short_tag("Unknown"),
			short_tag("Initial Weapon Index"),
			short_tag("Initial Secondary Weapon Index"),
			short_tag("Grenade Type"),
			short_tag("Initial Order Index"),
			undefined_tag("Vehicle Variant", 9999),
			block_tag("Starting Locations",
			{
				undefined_tag("Name", 9999),
				long_tag("Position x"),
				long_tag("Position y"),
				long_tag("Position z"),
				short_tag("Reference Frame"),
				short_tag("Unknown"),
				undefined_tag("Facing (Yaw, Pitch) y", 9999),
				undefined_tag("Facing (Yaw, Pitch) p", 9999),
				undefined_tag("Flags", 9999),
				short_tag("Character Type Index"),
				short_tag("Initial Weapon Index"),
				short_tag("Initial Secondary Weapon Index"),
				short_tag("Unknown"),
				short_tag("Vehicle Type Index"),
				short_tag("Seat Type"),
				short_tag("Grenade Type"),
				short_tag("Swarm Count"),
				undefined_tag("Actor Variant Name", 9999),
				undefined_tag("Vehicle Variant Name", 9999),
				long_tag("Initial Movement Distance"),
				short_tag("Emitter Vehicle Index"),
				short_tag("Initial Movement Mode"),
				string_tag("Placement Script"),
				short_tag("Unknown"),
				short_tag("Unknown"),
			}),
			string_tag("Placement Script"),
			short_tag("Unknown"),
			short_tag("Unknown"),
		}),
		block_tag("Zones",
		{
			string_tag("Name"),
			undefined_tag("Flags", 9999),
			short_tag("Manual Bsp Index"),
			short_tag("Unknown"),
			block_tag("Firing Positions",
			{
				long_tag("Position (Local) x"),
				long_tag("Position (Local) y"),
				long_tag("Position (Local) z"),
				short_tag("Reference Frame"),
				short_tag("Flags"),
				short_tag("Area Index"),
				short_tag("Cluster Index"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Normal y", 9999),
				undefined_tag("Normal p", 9999),
			}),
			block_tag("Areas",
			{
				string_tag("Name"),
				undefined_tag("Area Flags", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				short_tag("Manual Reference Frame"),
				short_tag("Unknown"),
				block_tag("Flight Hints",
				{
					short_tag("Flight Hint Index"),
					short_tag("Poit Index"),
				}),
			}),
		}),
		block_tag("Character Palette",
		{
			undefined_tag("Reference", 9999),
		}),
		block_tag("AI Animation References",
		{
			string_tag("Animation Name"),
			undefined_tag("Animation Graph", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("AI Script References",
		{
			string_tag("Script Name"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("AI Recording References",
		{
			string_tag("Recording Name"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("AI Conversations",
		{
			string_tag("Name"),
			short_tag("Flags"),
			short_tag("Unknown"),
			long_tag("Trigger Distance"),
			long_tag("Run-To-Player Dist"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("Participants",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				short_tag("Use This Object Index"),
				short_tag("Set New Name Index"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				string_tag("Encounter Name"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Lines",
			{
				short_tag("Flags"),
				short_tag("Participant Index"),
				short_tag("Addressee"),
				short_tag("Addressee Participant Index"),
				undefined_tag("Unknown", 9999),
				long_tag("Line Delay Time"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Variant 1", 9999),
				undefined_tag("Variant 2", 9999),
				undefined_tag("Variant 3", 9999),
				undefined_tag("Variant 4", 9999),
				undefined_tag("Variant 5", 9999),
				undefined_tag("Variant 6", 9999),
			}),
			block_tag("Unknown",
			{
			}),
		}),
		block_tag("Scripting Data",
		{
			block_tag("Point Sets",
			{
				string_tag("Name"),
				block_tag("Points",
				{
					string_tag("Name"),
					long_tag("Position x"),
					long_tag("Position y"),
					long_tag("Position z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
					long_tag("Surface Index"),
					undefined_tag("Facing Direction y", 9999),
					undefined_tag("Facing Direction p", 9999),
				}),
				short_tag("Bsp Index"),
				short_tag("Manual Reference Frame"),
				undefined_tag("Flags", 9999),
			}),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Orders",
		{
			string_tag("Name"),
			short_tag("Style Index"),
			short_tag("Unknown"),
			undefined_tag("Flags", 9999),
			short_tag("Force Combat Status"),
			short_tag("Unknown"),
			string_tag("Entry Script"),
			short_tag("Unknown"),
			short_tag("Follow Squad Index"),
			long_tag("Follow Radius"),
			block_tag("Primary Area Set",
			{
				short_tag("Area Type"),
				short_tag("Unknown"),
				short_tag("Zone Index"),
				short_tag("Area Index"),
			}),
			block_tag("Secondary Area Set",
			{
				short_tag("Area Type"),
				short_tag("Unknown"),
				short_tag("Zone Index"),
				short_tag("Area Index"),
			}),
			block_tag("Secondary Set Trigger",
			{
				short_tag("Combination Rule"),
				short_tag("Dialogue Type"),
				block_tag("Triggers",
				{
					undefined_tag("Trigger Flags", 9999),
					short_tag("Trigger Index"),
					short_tag("Unknown"),
				}),
			}),
			block_tag("Special Movement",
			{
				undefined_tag("Special Movement 1", 9999),
			}),
			block_tag("Order Endings",
			{
				short_tag("Next Order Index"),
				short_tag("Combination Rule"),
				long_tag("Delay Time"),
				short_tag("Dialogue Type"),
				short_tag("Unknown"),
				block_tag("Triggers",
				{
					undefined_tag("Trigger Flags", 9999),
					short_tag("Trigger Index"),
					short_tag("Unknown"),
				}),
			}),
		}),
		block_tag("Triggers",
		{
			string_tag("Name"),
			undefined_tag("Trigger Flags", 9999),
			short_tag("Combination Rule"),
			short_tag("Unknown"),
			block_tag("Conditions",
			{
				short_tag("Rule Type"),
				short_tag("Squad Index"),
				short_tag("Squad Group Index"),
				short_tag("A"),
				long_tag("X"),
				short_tag("Trigger Volume Index"),
				short_tag("Unknown"),
				string_tag("Exit Condition Script"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Flags", 9999),
			}),
		}),
		block_tag("BSP Preferences",
		{
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Structure BSP", 9999),
			undefined_tag("Structure Lightmap", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Radiance Est. Search Distance"),
			undefined_tag("Unknown", 9999),
			long_tag("Luminels Per World Unit"),
			long_tag("Output White Reference"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("Flags"),
			short_tag("Unknown"),
			short_tag("Default Sky Index"),
			short_tag("Unknown"),
		}),
		block_tag("Weapon References",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Vehicle References",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Vehicle Datum References",
		{
			short_tag("Type Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			long_tag("Position x"),
			long_tag("Position y"),
			long_tag("Position z"),
			undefined_tag("Rotation y", 9999),
			undefined_tag("Rotation p", 9999),
			undefined_tag("Rotation r", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			long_tag("Unique ID"),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder Index"),
			undefined_tag("Variant Name", 9999),
			undefined_tag("Active Change Colors", 9999),
			undefined_tag("Primary Color", 9999),
			undefined_tag("Secondary Color", 9999),
			undefined_tag("Tertiary Color", 9999),
			undefined_tag("Quaternary Color", 9999),
			long_tag("Body Vitality"),
			undefined_tag("Flags", 9999),
		}),
		block_tag("Mission Dialogue Scenes",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Flags", 9999),
			block_tag("Trigger Conditions",
			{
				short_tag("Combination Rule"),
				short_tag("Unknown"),
				block_tag("Triggers",
				{
					undefined_tag("Trigger Flags", 9999),
					short_tag("Trigger Index"),
					short_tag("Unknown"),
				}),
			}),
			block_tag("Roles",
			{
				undefined_tag("Name", 9999),
				short_tag("Group"),
				short_tag("Unknown"),
				block_tag("Role Variants",
				{
					undefined_tag("Variant Designation", 9999),
				}),
			}),
		}),
		block_tag("Flocks",
		{
			short_tag("Bsp Index"),
			short_tag("Unknown"),
			short_tag("Bounding Volume Index"),
			short_tag("Flags"),
			long_tag("Ecology Margin"),
			block_tag("Sources",
			{
				long_tag("Position i"),
				long_tag("Position j"),
				long_tag("Position k"),
				undefined_tag("Starting Yaw, Pitch y", 9999),
				undefined_tag("Starting Yaw, Pitch p", 9999),
				long_tag("Radius"),
				long_tag("Weight"),
			}),
			block_tag("Sinks",
			{
				long_tag("Position i"),
				long_tag("Position j"),
				long_tag("Position k"),
				long_tag("Radius"),
			}),
			long_tag("Production Frequency"),
			long_tag("Scale min"),
			long_tag("Scale max"),
			undefined_tag("Creature", 9999),
			undefined_tag("Boid Count min", 9999),
			undefined_tag("Boid Count max", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			long_tag("Neighborhood Radius"),
			long_tag("Avoidance Radius"),
			long_tag("Forward Scale"),
			long_tag("Alignment Scale"),
			long_tag("Avoidance Scale"),
			long_tag("Leveling Force Scale"),
			long_tag("Sink Scale"),
			undefined_tag("Perception Angle", 9999),
			long_tag("Average Throttle"),
			long_tag("Maximum Throttle"),
			long_tag("Position Scale"),
			long_tag("Position Min Radius"),
			long_tag("Position Max Radius"),
			long_tag("Movement Weight Threshold"),
			long_tag("Danger Radius"),
			long_tag("Danger Scale"),
			undefined_tag("", 9999),
			long_tag("Random Offset Scale"),
			long_tag("Random Offset Period min"),
			long_tag("Random Offset Period max"),
			undefined_tag("Flock Name", 9999),
		}),
		block_tag("Trigger Volume References",
		{
			undefined_tag("Name", 9999),
			short_tag("Object Name Index"),
			short_tag("Unknown"),
			undefined_tag("Node Name", 9999),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Position x"),
			long_tag("Position y"),
			long_tag("Position z"),
			long_tag("Extents x"),
			long_tag("Extents y"),
			long_tag("Extents z"),
			undefined_tag("Unknown", 9999),
			short_tag("Kill Trigger Volume Index"),
			short_tag("Unknown"),
		}),
	});
};
