#include "bipd.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* bipd_group = new tag_collection(
	"bipd",
	{
		
		short_tag("Object Type"),
		short_tag("Flags"),
		long_tag("Bounding Radius"),
		undefined_tag("Bounding Offset", 9999),
		long_tag("Acceleration Scale"),
		short_tag("Lightmap Shadow Mode"),
		byte_tag("Sweetener Size"),
		byte_tag("Unknown"),
		undefined_tag("Runtime Flags", 9999),
		long_tag("Dynamic Light Sphere Radius"),
		undefined_tag("Dynamic Light Sphere Offset", 9999),
		undefined_tag("Default Model Variant", 9999),
		undefined_tag("Model", 9999),
		undefined_tag("Crate Object", 9999),
		undefined_tag("Modifier Shader", 9999),
		undefined_tag("Creation Effect", 9999),
		undefined_tag("Material Effects", 9999),
		block_tag("AI Properties",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("AI Type Name", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("AI Size"),
			short_tag("Leap Jump Speed"),
		}),
		block_tag("Functions",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Import Name", 9999),
			undefined_tag("Export Name", 9999),
			undefined_tag("Turn Off With", 9999),
			long_tag("Minimum Value"),
			undefined_tag("Default Function", 9999),
			undefined_tag("Scale By", 9999),
		}),
		long_tag("Apply Collision Damage Scale"),
		undefined_tag("Game Acceleration", 9999),
		undefined_tag("Game Scale", 9999),
		undefined_tag("Absolute Acceleration", 9999),
		undefined_tag("Absolute Scale", 9999),
		short_tag("HUD Text Message Index"),
		short_tag("Unknown"),
		block_tag("Attachments",
		{
			undefined_tag("Type", 9999),
			undefined_tag("Marker", 9999),
			short_tag("Change Color"),
			short_tag("Unknown"),
			undefined_tag("Primary Scale", 9999),
			undefined_tag("Secondary Scale", 9999),
		}),
		block_tag("Widgets",
		{
			undefined_tag("Type", 9999),
		}),
		block_tag("Old Functions",
		{
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Change Colors",
		{
			block_tag("Initial Permutations",
			{
				long_tag("Weight"),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Variant Name", 9999),
			}),
			block_tag("Functions",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Scale Flags", 9999),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Darken By", 9999),
				undefined_tag("Scale By", 9999),
			}),
		}),
		block_tag("Predicted Resources",
		{
			short_tag("Type"),
			short_tag("Resource Index"),
			tagref_tag("Tag Index"),
		}),
		undefined_tag("Flags", 9999),
		short_tag("Default Team"),
		short_tag("Constant Sound Volume"),
		undefined_tag("Integrated Light Toggle", 9999),
		undefined_tag("Camera Field of View", 9999),
		long_tag("Camera Stiffness"),
		undefined_tag("Camera Marker Name", 9999),
		undefined_tag("Camera Submerged Marker Name", 9999),
		undefined_tag("Pitch Auto-Level", 9999),
		undefined_tag("Pitch Range", 9999),
		block_tag("Camera Tracks",
		{
			undefined_tag("Track", 9999),
		}),
		undefined_tag("Acceleration Range", 9999),
		long_tag("Acceleration Action Scale"),
		long_tag("Acceleration Attach Scale"),
		long_tag("Soft Ping Threshold"),
		long_tag("Soft Ping Interrupt Time"),
		long_tag("Hard Ping Threshold"),
		long_tag("Hard Ping Interrupt Time"),
		long_tag("Hard Death Threshold"),
		long_tag("Feign Death Threshold"),
		long_tag("Feign Death Time"),
		long_tag("Distance Of Evade Animation"),
		long_tag("Distance Of Dive Animation"),
		long_tag("Stunned Movement Threshold"),
		long_tag("Feign Death Chance"),
		long_tag("Feign Repeat Chance"),
		undefined_tag("Spawned Turret Character", 9999),
		undefined_tag("Spawned Actor Count", 9999),
		long_tag("Spawned Velocity"),
		undefined_tag("Aiming Velocity Maximum", 9999),
		undefined_tag("Aiming Acceleration Maximum", 9999),
		long_tag("Casual Aiming Modifier"),
		undefined_tag("Looking Velocity Maximum", 9999),
		undefined_tag("Looking Acceleration Maximum", 9999),
		undefined_tag("Right Hand Node", 9999),
		undefined_tag("Left Hand Node", 9999),
		undefined_tag("Preferred Gun Node", 9999),
		undefined_tag("Melee Damage", 9999),
		undefined_tag("Boarding Melee Damage", 9999),
		undefined_tag("Boarding Melee Response", 9999),
		undefined_tag("Landing Melee Damage", 9999),
		undefined_tag("Flurry Melee Damage", 9999),
		undefined_tag("Obstacle Smash Damage", 9999),
		short_tag("Motion Sensor Blip Size"),
		short_tag("Unknown"),
		block_tag("Postures",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Pill Offset", 9999),
		}),
		block_tag("New HUD Interfaces",
		{
			undefined_tag("New Unit HUD Interface", 9999),
		}),
		block_tag("Dialogue Variants",
		{
			short_tag("Variant Number"),
			short_tag("Unknown"),
			undefined_tag("Dialogue", 9999),
		}),
		long_tag("Grenade Velocity"),
		short_tag("Grenade Type"),
		short_tag("Grenade Count"),
		block_tag("Powered Seats",
		{
			long_tag("Driver Powerup Time"),
			long_tag("Driver Powerdown Time"),
		}),
		block_tag("Weapons",
		{
			undefined_tag("Weapon", 9999),
		}),
		block_tag("Seats",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Seat Animation", 9999),
			undefined_tag("Seat Marker Name", 9999),
			undefined_tag("Entry Marker(s) Name", 9999),
			undefined_tag("Boarding Grenade Marker", 9999),
			undefined_tag("Boarding Grenade String", 9999),
			undefined_tag("Boarding Melee String", 9999),
			long_tag("Ping Scale"),
			long_tag("Turnover Time"),
			undefined_tag("Acceleration Range", 9999),
			long_tag("Acceleration Action Scale"),
			long_tag("Acceleration Attach Scale"),
			long_tag("AI Scariness"),
			short_tag("AI Seat Type"),
			short_tag("Boarding Seat Index"),
			long_tag("Listener Interpolation Factor"),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("Yaw Rate Bounds", 9999),
			undefined_tag("Pitch Rate Bounds", 9999),
			long_tag("Minimum Speed Reference"),
			long_tag("Maximum Speed Reference"),
			long_tag("Speed Exponent"),
			undefined_tag("Camera Marker Name", 9999),
			undefined_tag("Camera Submerged Marker Name", 9999),
			undefined_tag("Pitch Auto-Level", 9999),
			undefined_tag("Pitch Range", 9999),
			block_tag("Camera Tracks",
			{
				undefined_tag("Track", 9999),
			}),
			block_tag("Unit HUD Interface",
			{
				undefined_tag("New Unit HUD Interface", 9999),
			}),
			undefined_tag("Enter Seat String", 9999),
			undefined_tag("Yaw", 9999),
			undefined_tag("Built-In Gunner", 9999),
			long_tag("Entry Radius"),
			undefined_tag("Entry Marker Cone Angle", 9999),
			undefined_tag("Entry Marker Facing Angle", 9999),
			long_tag("Maximum Relative Velocity"),
			undefined_tag("Invisible Seat Region", 9999),
			long_tag("Invisible Seat Region Index"),
		}),
		long_tag("Boost Peak Power"),
		long_tag("Boost Rise Power"),
		long_tag("Boost Peak Time"),
		long_tag("Boost Fall Power"),
		long_tag("Boost Dead Time"),
		long_tag("Lipsync Attack Weight"),
		long_tag("Lipsync Decay Weight"),
		undefined_tag("Moving Turning Speed", 9999),
		undefined_tag("Flags", 9999),
		undefined_tag("Stationary Turning Threshold", 9999),
		long_tag("Jump Velocity"),
		long_tag("Maximum Soft Landing Time"),
		long_tag("Maximum Hard Landing Time"),
		long_tag("Minimum Soft Landing Velocity"),
		long_tag("Minimum Hard Landing Velocity"),
		long_tag("Maximum Hard Landing Velocity"),
		long_tag("Death Hard Landing Velocity"),
		long_tag("Stun Duration"),
		long_tag("Standing Camera Height"),
		long_tag("Crouching Camera Height"),
		long_tag("Crouch Transition Time"),
		undefined_tag("Camera Interpolation Start", 9999),
		undefined_tag("Camera Interpolation End", 9999),
		long_tag("Camera Forward Movement Scale"),
		long_tag("Camera Side Movement Scale"),
		long_tag("Camera Vertical Movement Scale"),
		long_tag("Camera Exclusion Distance"),
		long_tag("Autoaim Width"),
		undefined_tag("Lock-On Flags", 9999),
		long_tag("Lock-On Distance"),
		short_tag("Physics Control Node Index"),
		short_tag("Unknown"),
		long_tag("Cosine Stationary Turning Threshold"),
		long_tag("Crouch Transition Velocity"),
		short_tag("Pelvis Node Index"),
		short_tag("Head Node Index"),
		long_tag("Headshot Acceleration Scale"),
		undefined_tag("Area Damage Effect", 9999),
		undefined_tag("Flags", 9999),
		long_tag("Height Standing"),
		long_tag("Height Crouching"),
		long_tag("Radius"),
		long_tag("Mass"),
		undefined_tag("Living Material Name", 9999),
		undefined_tag("Dead Material Name", 9999),
		short_tag("Living Material Global Index"),
		short_tag("Dead Material Global Index"),
		block_tag("Dead Sphere Shapes",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("User Data", 9999),
			undefined_tag("Rotation i", 9999),
			long_tag("w Rotation i"),
			undefined_tag("Rotation j", 9999),
			long_tag("w Rotation j"),
			undefined_tag("Rotation k", 9999),
			long_tag("w Rotation k"),
			undefined_tag("Translation", 9999),
			long_tag("w Translation"),
		}),
		block_tag("Pill Shapes",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Bottom", 9999),
			long_tag("w Bottom"),
			undefined_tag("Top", 9999),
			long_tag("w Top"),
		}),
		block_tag("Sphere Shapes",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("User Data", 9999),
			undefined_tag("Rotation i", 9999),
			long_tag("w Rotation i"),
			undefined_tag("Rotation j", 9999),
			long_tag("w Rotation j"),
			undefined_tag("Rotation k", 9999),
			long_tag("w Rotation k"),
			undefined_tag("Translation", 9999),
			long_tag("w Translation"),
		}),
		undefined_tag("Maximum Slope Angle", 9999),
		undefined_tag("Downhill Falloff Angle", 9999),
		undefined_tag("Downhill Cutoff Angle", 9999),
		undefined_tag("Uphill Falloff Angle", 9999),
		undefined_tag("Uphill Cutoff Angle", 9999),
		long_tag("Downhill Velocity Scale"),
		long_tag("Uphill Velocity Scale"),
		long_tag("Minimum Normal k"),
		long_tag("Downhill k0"),
		long_tag("Downhill k1"),
		long_tag("Uphill k0"),
		long_tag("Uphill k1"),
		undefined_tag("Bank Angle", 9999),
		long_tag("Bank Apply Time"),
		long_tag("Bank Decay Time"),
		long_tag("Pitch Ratio"),
		long_tag("Maximum Velocity"),
		long_tag("Maximum Sidestep Velocity"),
		long_tag("Acceleration"),
		long_tag("Deceleration"),
		undefined_tag("Angular Velocity Maximum", 9999),
		undefined_tag("Angular Acceleration Maximum", 9999),
		long_tag("Crouch Velocity Modifier"),
		block_tag("Contact Points",
		{
			undefined_tag("Marker Name", 9999),
		}),
		undefined_tag("Reanimation Character", 9999),
		undefined_tag("Death Spawn Character", 9999),
		short_tag("Death Spawn Count"),
		short_tag("Unknown"),
	});
};
