#include "bitm.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* bitm_group = new tag_collection(
	"bitm",
	{
		
		short_tag("Type"),
		short_tag("Format"),
		short_tag("Usage"),
		short_tag("Flags"),
		long_tag("Detail Fade Factor"),
		long_tag("Sharpen Amount"),
		long_tag("Bump Height"),
		short_tag("Sprite Budget Size"),
		short_tag("Sprite Budget Count"),
		short_tag("Color Plate Width"),
		short_tag("Color Plate Height"),
		long_tag("Compressed Color Plate Data"),
		undefined_tag("Unknown", 9999),
		long_tag("Processed Pixel Data"),
		undefined_tag("Unknown", 9999),
		long_tag("Blur Filter Size"),
		long_tag("Alpha Bias"),
		short_tag("Mipmap Count"),
		short_tag("Sprite Usage"),
		short_tag("Sprite Spacing"),
		short_tag("Force Format"),
		block_tag("Squences",
		{
			string_tag("Name"),
			short_tag("First Bitmap Index"),
			short_tag("Bitmap Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("Sprites",
			{
				short_tag("Bitmap Index"),
				short_tag("Unknown"),
				undefined_tag("Unknown", 9999),
				long_tag("Left"),
				long_tag("Right"),
				long_tag("Top"),
				long_tag("Bottom"),
				undefined_tag("Registration Point", 9999),
			}),
		}),
		block_tag("Bitmaps",
		{
			string_tag("Signature"),
			short_tag("Width"),
			short_tag("Height"),
			byte_tag("Depth"),
			undefined_tag("More Flags", 9999),
			short_tag("Type"),
			short_tag("Format"),
			short_tag("Flags"),
			point16_tag("Registration Point"),
			short_tag("Mipmap Count"),
			short_tag("Low-Detail Mipmap Count"),
			long_tag("Pixels Offset"),
			long_tag("LOD1 Offset"),
			long_tag("LOD2 Offset"),
			long_tag("LOD3 Offset"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("LOD1 Size"),
			long_tag("LOD2 Size"),
			long_tag("LOD3 Size"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			tagref_tag("Datum"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			undefined_tag("Unknown", 9999),
		}),
		byte_tag("Color Compression Quality"),
		byte_tag("Alpha Compression Quality"),
		byte_tag("Overlap"),
		byte_tag("Color Subsampling"),
	});
};
