#include "bsdt.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* bsdt_group = new tag_collection(
	"bsdt",
	{
		
		long_tag("Maximum Vitality"),
		undefined_tag("Effect", 9999),
		undefined_tag("Sound", 9999),
		block_tag("Particle Effects",
		{
			undefined_tag("Particle", 9999),
			long_tag("Location"),
			short_tag("Coordinate System"),
			short_tag("Environment"),
			short_tag("Disposition"),
			short_tag("Camera Mode"),
			short_tag("Sort Bias"),
			short_tag("Flags"),
			long_tag("LOD In Distance"),
			long_tag("LOD Feather In Delta"),
			long_tag("Unknown"),
			long_tag("LOD Out Distance"),
			long_tag("LOD Feather Out Delta"),
			long_tag("Unknown"),
			block_tag("Emitters",
			{
				undefined_tag("Particle Physics", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				undefined_tag("Emission Shape", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier"),
				undefined_tag("Function", 9999),
				long_tag("Translational Offset x"),
				long_tag("Translational Offset y"),
				long_tag("Translational Offset z"),
				undefined_tag("Relative Direction y", 9999),
				undefined_tag("Relative Direction p", 9999),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
		}),
		long_tag("Particle Density"),
	});
};
