#include "char.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* char_group = new tag_collection(
	"char",
	{
		
		undefined_tag("Character Flags", 9999),
		undefined_tag("Parent Character", 9999),
		undefined_tag("Unit", 9999),
		undefined_tag("Creature", 9999),
		undefined_tag("Style", 9999),
		undefined_tag("Major Character", 9999),
		block_tag("Variants",
		{
			undefined_tag("Variant Name", 9999),
			short_tag("Variant Index"),
			short_tag("Unknown"),
			undefined_tag("Variant Designator", 9999),
		}),
		block_tag("General Properties",
		{
			undefined_tag("General Flags", 9999),
			short_tag("Type"),
			short_tag("Unknown"),
			long_tag("Scariness"),
		}),
		block_tag("Vitality Properties",
		{
			undefined_tag("Vitality Flags", 9999),
			long_tag("Normal Body Vitality"),
			long_tag("Normal Shield Vitality"),
			long_tag("Legendary Body Vitality"),
			long_tag("Legendary Shield Vitality"),
			long_tag("Body Recharge Fraction"),
			long_tag("Soft Ping Threshold (With Shields)"),
			long_tag("Soft Ping Threshold (No Shields)"),
			long_tag("Soft Ping Min Interrupt Time"),
			long_tag("Hard Ping Threshold (With Shields)"),
			long_tag("Hard Ping Threshold (No Shields)"),
			long_tag("Hard Ping Min Interrupt Time"),
			long_tag("Current Damage Decay Delay"),
			long_tag("Current Damage Decay Time"),
			long_tag("Recent Damage Decay Delay"),
			long_tag("Recent Damage Decay Time"),
			long_tag("Body Recharge Delay Time"),
			long_tag("Body Recharge Time"),
			long_tag("Shield Recharge Delay Time"),
			long_tag("Shield Recharge Time"),
			long_tag("Stun Threshold"),
			undefined_tag("Stun Time Bounds", 9999),
			long_tag("Extended Shield Damage Threshold %"),
			long_tag("Extended Body Damage Threshold %"),
			long_tag("Suicide Radius"),
			long_tag("Runtime Body Recharge Velocity"),
			long_tag("Runtime Shield Recharge Velocity"),
		}),
		block_tag("Placement Properties",
		{
			undefined_tag("Placement Flags", 9999),
			long_tag("Few Upgrade Chance (Easy)"),
			long_tag("Few Upgrade Chance (Normal)"),
			long_tag("Few Upgrade Chance (Heroic)"),
			long_tag("Few Upgrade Chance (Legendary)"),
			long_tag("Normal Upgrade Chance (Easy)"),
			long_tag("Normal Upgrade Chance (Normal)"),
			long_tag("Normal Upgrade Chance (Heroic)"),
			long_tag("Normal Upgrade Chance (Legendary)"),
			long_tag("Many Upgrade Chance (Easy)"),
			long_tag("Many Upgrade Chance (Normal)"),
			long_tag("Many Upgrade Chance (Heroic)"),
			long_tag("Many Upgrade Chance (Legendary)"),
		}),
		block_tag("Perception Properties",
		{
			undefined_tag("Perception Flags", 9999),
			long_tag("Max Vision Distance"),
			undefined_tag("Central Vision Angle", 9999),
			undefined_tag("Max Vision Angle", 9999),
			undefined_tag("Peripheral Vision Angle", 9999),
			long_tag("Peripheral Distance"),
			long_tag("Hearing Distance"),
			long_tag("Notice Projectile Chance"),
			long_tag("Notice Vehicle Chance"),
			long_tag("Combat Perception Time"),
			long_tag("Guard Perception Time"),
			long_tag("Non-Combat Perception Time"),
			long_tag("First Ack. Surprise Distance"),
		}),
		block_tag("Look Properties",
		{
			undefined_tag("Maximum Aiming Deviation", 9999),
			undefined_tag("Maximum Looking Deviation", 9999),
			undefined_tag("Runtime Aiming Deviation Cosines", 9999),
			undefined_tag("Runtime Looking Deviation Cosines", 9999),
			undefined_tag("Non-Combat Look Delta L", 9999),
			undefined_tag("Non-Combat Look Delta R", 9999),
			undefined_tag("Combat Look Delta L", 9999),
			undefined_tag("Combat Look Delta R", 9999),
			undefined_tag("Noncombat Idle Looking", 9999),
			undefined_tag("Noncombat Idle Aiming", 9999),
			undefined_tag("Combat Idle Looking", 9999),
			undefined_tag("Combat Idle Aiming", 9999),
		}),
		block_tag("Movement Properties",
		{
			undefined_tag("Flags", 9999),
			long_tag("Pathfinding Radius"),
			long_tag("Destination Radius"),
			long_tag("Dive Grenade Chance"),
			short_tag("Obstacle Leap Min Size"),
			short_tag("Obstacle Leap Max Size"),
			short_tag("Obstacle Ignore Size"),
			short_tag("Obstacle Smashable Size"),
			short_tag("Unknown"),
			short_tag("Jump Height"),
			undefined_tag("Movement Hint Flags", 9999),
			long_tag("Throttle Scale"),
		}),
		block_tag("Swarm Properties",
		{
			short_tag("Scatter Killed Count"),
			short_tag("Unknown"),
			long_tag("Scatter Radius"),
			long_tag("Scatter Time"),
			long_tag("Hound Min Distance"),
			long_tag("Hound Max Distance"),
			long_tag("Perlin Offset Scale"),
			undefined_tag("Offset Period", 9999),
			long_tag("Perlin Idle Movement Threshold"),
			long_tag("Perlin Combat Movement Threshold"),
		}),
		block_tag("Ready Properties",
		{
			undefined_tag("Ready Time Bounds", 9999),
		}),
		block_tag("Engage Properties",
		{
			undefined_tag("Flags", 9999),
			long_tag("Crouch Danger Threshold"),
			long_tag("Stand Danger Threshold"),
			long_tag("Fight Danger Move Threshold"),
		}),
		block_tag("Charge Properties",
		{
			undefined_tag("Charge Flags", 9999),
			long_tag("Melee Consider Range"),
			long_tag("Melee Chance"),
			long_tag("Melee Attack Range"),
			long_tag("Melee Abort Range"),
			long_tag("Melee Attack Timeout"),
			long_tag("Melee Attack Delay Timer"),
			undefined_tag("Melee Leap Range", 9999),
			long_tag("Melee Leap Chance"),
			long_tag("Ideal Leap Velocity"),
			long_tag("Max Leap Velocity"),
			long_tag("Melee Leap Ballistic"),
			long_tag("Melee Delay Timer"),
			undefined_tag("Berserk Weapon", 9999),
		}),
		block_tag("Evasion Properties",
		{
			long_tag("Evasion Danger Threshold"),
			long_tag("Evasion Delay Timer"),
			long_tag("Evasion Chance"),
			long_tag("Evasion Proximity Threshold"),
			long_tag("Dive Retreat Chance"),
		}),
		block_tag("Cover Properties",
		{
			undefined_tag("Cover Flags", 9999),
			undefined_tag("Hide Behind Cover Time", 9999),
			long_tag("Cover Vitality Threshold"),
			long_tag("Cover Shield Fraction"),
			long_tag("Cover Check Delay"),
			long_tag("Emerge From Cover When Shielded"),
			long_tag("Cover Danger Threshold"),
			long_tag("Danger Upper Threshold"),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("Cover Chance", 9999),
			long_tag("Proximity Self Preserve"),
			long_tag("Disallow Cover Distance"),
			long_tag("Proximity Melee Distance"),
			long_tag("Unreachable Enemy Danger Threshold"),
			long_tag("Scary Target Threshold"),
		}),
		block_tag("Retreat Properties",
		{
			undefined_tag("Retreat Flags", 9999),
			long_tag("Shield Threshold"),
			long_tag("Scary Target Threshold"),
			long_tag("Danger Threshold"),
			long_tag("Proximity Threshold"),
			undefined_tag("Min/Max Forced Cower Time Bounds", 9999),
			undefined_tag("Min/Max Cower Time Bounds", 9999),
			long_tag("Proximity Ambush Threshold"),
			long_tag("Awareness Ambush Threshold"),
			long_tag("Leader Dead Retreat Chance"),
			long_tag("Peer Dead Retreat Chance"),
			long_tag("Second Peer Dead Retreat Chance"),
			undefined_tag("ZigZag Angle", 9999),
			long_tag("ZigZag Period"),
			long_tag("Retreat Grenade Chance"),
			undefined_tag("Backup Weapon", 9999),
		}),
		block_tag("Search Properties",
		{
			undefined_tag("Search Flags", 9999),
			undefined_tag("Search Time", 9999),
			undefined_tag("Uncover Distance Bounds", 9999),
		}),
		block_tag("Pre-Search Properties",
		{
			undefined_tag("Pre-Search Flags", 9999),
			undefined_tag("Min Presearch Time", 9999),
			undefined_tag("Max Presearch Time", 9999),
			long_tag("Min Certainty Radius"),
			long_tag("DEPRECATED"),
			undefined_tag("Min Suppressing Time", 9999),
		}),
		block_tag("Idle Properties",
		{
			undefined_tag("Idle Flags", 9999),
			undefined_tag("Idle Pose Delay Time", 9999),
		}),
		block_tag("Vocalization Properties",
		{
			long_tag("Look Comment Time"),
			long_tag("Look Long Comment Time"),
		}),
		block_tag("Boarding Properties",
		{
			undefined_tag("Flags", 9999),
			long_tag("Max Distance"),
			long_tag("Abort Distance"),
			long_tag("Max Speed"),
		}),
		block_tag("Boss Properties",
		{
			undefined_tag("Boss Flags", 9999),
			long_tag("Flurry Damage Threshold"),
			long_tag("Flurry Time"),
		}),
		block_tag("Weapons Properties",
		{
			undefined_tag("Weapons Flags", 9999),
			undefined_tag("Weapon", 9999),
			long_tag("Maximum Firing Range"),
			long_tag("Minimum Firing Range"),
			undefined_tag("Normal Combat Range", 9999),
			long_tag("Bombardment Range"),
			long_tag("Max Special Target Distance"),
			undefined_tag("Timid Combat Range", 9999),
			undefined_tag("Aggressive Combat Range", 9999),
			long_tag("Super Ballistic Range"),
			undefined_tag("Ballistic Firing Bounds", 9999),
			undefined_tag("Ballistic Fraction Bounds", 9999),
			undefined_tag("First Burst Delay Time", 9999),
			long_tag("Surprise Delay Time"),
			long_tag("Surprise Fire-Wildly Time"),
			long_tag("Death Fire-Wildly Chance"),
			long_tag("Death Fire-Wildly Time"),
			undefined_tag("Custom Stand Gun Offset", 9999),
			undefined_tag("Custom Crouch Gun Offset", 9999),
			short_tag("Special Fire Mode"),
			short_tag("Special Fire Situation"),
			long_tag("Special Fire Chance"),
			long_tag("Special Fire Delay"),
			long_tag("Special Damage Modifier"),
			undefined_tag("Special Projectile error", 9999),
			undefined_tag("Drop Weapon Loaded", 9999),
			undefined_tag("Drop Weapon Ammo", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("Normal Accuracy Bounds", 9999),
			long_tag("Normal Accuracy Time"),
			undefined_tag("Heroic Accuracy Bounds", 9999),
			long_tag("Heroic Accuracy Time"),
			undefined_tag("Legendary Accuracy Bounds", 9999),
			long_tag("Legendary Accuracy Time"),
			block_tag("Firing Patterns",
			{
				long_tag("Rate of Fire"),
				long_tag("Target Tracking"),
				long_tag("Target Leading"),
				undefined_tag("", 9999),
				undefined_tag("", 9999),
				undefined_tag("", 9999),
				undefined_tag("", 9999),
				long_tag("Burst Origin Radius"),
				undefined_tag("Burst Origin Angle", 9999),
				undefined_tag("Burst Return Length", 9999),
				undefined_tag("Burst Return Angle", 9999),
				undefined_tag("Burst Duration", 9999),
				undefined_tag("Burst Separation", 9999),
				long_tag("Weapon Damage Modifier"),
				undefined_tag("Projectile Error", 9999),
				undefined_tag("Burst Angular Velocity", 9999),
				undefined_tag("Maximum Error Angle", 9999),
			}),
			undefined_tag("Weapon Melee Damage", 9999),
		}),
		block_tag("Firing Pattern Properties",
		{
			undefined_tag("Weapon", 9999),
			block_tag("Firing Patterns",
			{
				long_tag("Rate of Fire"),
				long_tag("Target Tracking"),
				long_tag("Target Leading"),
				undefined_tag("", 9999),
				undefined_tag("", 9999),
				undefined_tag("", 9999),
				undefined_tag("", 9999),
				long_tag("Burst Origin Radius"),
				undefined_tag("Burst Origin Angle", 9999),
				undefined_tag("Burst Return Length", 9999),
				undefined_tag("Burst Return Angle", 9999),
				undefined_tag("Burst Duration", 9999),
				undefined_tag("Burst Separation", 9999),
				long_tag("Weapon Damage Modifier"),
				undefined_tag("Projectile Error", 9999),
				undefined_tag("Burst Angular Velocity", 9999),
				undefined_tag("Maximum Error Angle", 9999),
			}),
		}),
		block_tag("Grenades Properties",
		{
			undefined_tag("Grenades Flags", 9999),
			short_tag("Grenade Type"),
			short_tag("Trajectory Type"),
			short_tag("Unknown"),
			short_tag("Minimum Enemy Count"),
			long_tag("Enemy Radius"),
			long_tag("Grenade Ideal Velocity"),
			long_tag("Grenade Velocity"),
			undefined_tag("Grenade Ranges", 9999),
			long_tag("Collateral Damage Radius"),
			long_tag("Grenade Chance"),
			long_tag("Grenade Throw Delay"),
			long_tag("Grenade Uncover Chance"),
			long_tag("Anti-Vehicle Grenade Chance"),
			undefined_tag("Grenade Count", 9999),
			long_tag("Don't Drop Grenades Chance"),
		}),
		block_tag("Vehicle Associations",
		{
			undefined_tag("Vehicle", 9999),
			undefined_tag("Style", 9999),
			undefined_tag("Vehicle Flags", 9999),
			long_tag("AI Pathfinding Radius"),
			long_tag("AI Destination Radius"),
			long_tag("AI Deceleration Distance"),
			long_tag("AI Turning Radius"),
			long_tag("AI Inner Turning Radius"),
			long_tag("AI Ideal Turning Radius"),
			undefined_tag("AI Banshee Steering Maximum", 9999),
			long_tag("AI Max Steering Angle"),
			long_tag("AI Max Steering Delta"),
			long_tag("AI Oversteering Scale"),
			undefined_tag("AI Oversteering Bounds", 9999),
			long_tag("AI Side Slip Distance"),
			long_tag("AI Avoidance Distance"),
			long_tag("AI Min Urgency"),
			long_tag("AI Throttle Maximum"),
			long_tag("AI Goal Min Throttle Scale"),
			long_tag("AI Turn Min Throttle Scale"),
			long_tag("AI Direction Min Throttle Scale"),
			long_tag("AI Acceleration Scale"),
			long_tag("AI Throttle Blend"),
			long_tag("Theoretical Max Speed"),
			long_tag("Error Scale"),
			undefined_tag("AI Allowable Aim Deviation Angle", 9999),
			long_tag("AI Charge Tight Angle Distance"),
			long_tag("AI Charge Tight Angle"),
			long_tag("AI Charge Repeat Timeout"),
			long_tag("AI Charge Look-Ahead Time"),
			long_tag("AI Consider Distance"),
			long_tag("AI Charge Abort Distance"),
			long_tag("Vehicle Ram Timeout"),
			long_tag("Ram Paralysis Time"),
			long_tag("AI Cover Damage Threshold"),
			long_tag("AI Cover Min Distance"),
			long_tag("AI Cover Time"),
			long_tag("AI Cover Min Boost Distance"),
			long_tag("Turtling Recent Damage Threshold"),
			long_tag("Turtling Min Time"),
			long_tag("Turtling Timeout"),
			short_tag("Obstacle Ignore Size"),
			short_tag("Unknown"),
		}),
	});
};
