#include "clu_.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* clu__group = new tag_collection(
	"clu_",
	{
		
		block_tag("Cluster Data",
		{
			undefined_tag("BSP", 9999),
			block_tag("Background Sounds",
			{
				short_tag("Type Index"),
				short_tag("Unknown"),
			}),
			block_tag("Sound Environments",
			{
				short_tag("Type Index"),
				short_tag("Unknown"),
			}),
			long_tag("BSP Checksum"),
			block_tag("Cluster Centroids",
			{
				long_tag("Centroid x"),
				long_tag("Centroid y"),
				long_tag("Centroid z"),
			}),
			block_tag("Weather Properties",
			{
				short_tag("Type Index"),
				short_tag("Unknown"),
			}),
			block_tag("Atmospheric Fog Properties",
			{
				short_tag("Type Index"),
				short_tag("Unknown"),
			}),
		}),
		block_tag("Background Sound Palette",
		{
			string_tag("Name"),
			undefined_tag("Background Sound", 9999),
			undefined_tag("Inside Cluster Sound", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Cutoff Distance"),
			undefined_tag("Scale Flags", 9999),
			long_tag("Interior Scale"),
			long_tag("Portal Scale"),
			long_tag("Exterior Scale"),
			long_tag("Interpolation Speed"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Sound Environment Palette",
		{
			string_tag("Name"),
			undefined_tag("Sound Environment", 9999),
			long_tag("Cutoff Distance"),
			long_tag("Interpolation Speed"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Weather Palette",
		{
			string_tag("Name"),
			undefined_tag("Weather System", 9999),
			short_tag("Unknown"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Wind", 9999),
			long_tag("Wind Direction i"),
			long_tag("Wind Direction j"),
			long_tag("Wind Direction k"),
			long_tag("Wind Magnitude"),
			undefined_tag("Unknown", 9999),
			string_tag("Wind Scale Function"),
		}),
		block_tag("Atmospheric Fog Palette",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Color", 9999),
			long_tag("Spread Distance"),
			undefined_tag("Unknown", 9999),
			long_tag("Maximum Density"),
			long_tag("Start Distance"),
			long_tag("Opaque Distance"),
			undefined_tag("Color", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Maximum Density"),
			long_tag("Start Distance"),
			long_tag("Opaque Distance"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Planar Color", 9999),
			long_tag("Planar Max Density"),
			long_tag("Planar Override Amount"),
			long_tag("Planar Min Distance Bias"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Patchy Color", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Patchy Density min"),
			long_tag("Patchy Density max"),
			long_tag("Patchy Distance min"),
			long_tag("Patchy Distance max"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Patchy Fog", 9999),
			block_tag("Mixers",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Atmospheric Fog Source", 9999),
				undefined_tag("Interpolator", 9999),
				short_tag("Unknown"),
				short_tag("Unknown"),
			}),
			long_tag("Amount"),
			long_tag("Threshold"),
			long_tag("Brightness"),
			long_tag("Gamma Power"),
			short_tag("Camera Immersion Flags"),
			short_tag("Unknown"),
		}),
	});
};
