#include "coll.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* coll_group = new tag_collection(
	"coll",
	{
		
		undefined_tag("Import Info Block", 9999),
		undefined_tag("Import Info Block", 9999),
		undefined_tag("Errors Block", 9999),
		undefined_tag("Errors Block", 9999),
		undefined_tag("Flags", 9999),
		block_tag("Materials",
		{
			undefined_tag("Name", 9999),
		}),
		block_tag("Regions",
		{
			undefined_tag("Name", 9999),
			block_tag("Permutations",
			{
				undefined_tag("Name", 9999),
				block_tag("BSPs",
				{
					short_tag("Node Index"),
					short_tag("Unknown"),
					block_tag("BSP 3D Nodes",
					{
						short_tag("Plane"),
						undefined_tag("Front Child Lower", 9999),
						undefined_tag("Front Child Mid", 9999),
						undefined_tag("Front Child Upper", 9999),
						undefined_tag("Back Child Lower", 9999),
						undefined_tag("Back Child Mid", 9999),
						undefined_tag("Back Child Upper", 9999),
					}),
					block_tag("Planes",
					{
						long_tag("Plane i"),
						long_tag("Plane j"),
						long_tag("Plane k"),
						long_tag("Plane d"),
					}),
					block_tag("Leaves",
					{
						undefined_tag("Flags", 9999),
						undefined_tag("BSP 2D Reference Count", 9999),
						short_tag("First BSP 2D Reference"),
					}),
					block_tag("BSP 2D References",
					{
						short_tag("Plane"),
						short_tag("BSP 2D Node"),
					}),
					block_tag("BSP 2D Nodes",
					{
						long_tag("Plane i"),
						long_tag("Plane j"),
						long_tag("Plane d"),
						short_tag("Left Child"),
						short_tag("Right Child"),
					}),
					block_tag("Surfaces",
					{
						short_tag("Plane"),
						short_tag("First Edge"),
						undefined_tag("Flags", 9999),
						undefined_tag("Breakable Surface", 9999),
						short_tag("Material"),
					}),
					block_tag("Edges",
					{
						short_tag("Start Vertex"),
						short_tag("End Vertex"),
						short_tag("Forward Edge"),
						short_tag("Reverse Edge"),
						short_tag("Left Surface"),
						short_tag("Right Surface"),
					}),
					block_tag("Vertices",
					{
						long_tag("Point x"),
						long_tag("Point y"),
						long_tag("Point z"),
						short_tag("First Edge"),
						short_tag("Unknown"),
					}),
				}),
				block_tag("BSP Physics",
				{
					undefined_tag("Runtime Code Pointer", 9999),
					short_tag("Size"),
					short_tag("Count"),
					undefined_tag("User Data", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Center", 9999),
					long_tag("w Center"),
					undefined_tag("Half Extent", 9999),
					long_tag("w Half Extent"),
					tagref_tag("Runtime Model Tag"),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Runtime Code Pointer", 9999),
					short_tag("Size"),
					short_tag("Count"),
					undefined_tag("User Data", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Runtime Code Pointer", 9999),
					short_tag("Size"),
					short_tag("Count"),
					undefined_tag("User Data", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("MOPP Code Data", 9999),
					undefined_tag("Unknown", 9999),
				}),
			}),
		}),
		block_tag("Pathfinding Spheres",
		{
			short_tag("Node"),
			short_tag("Flags"),
			long_tag("Center x"),
			long_tag("Center y"),
			long_tag("Center z"),
			long_tag("Radius"),
		}),
		block_tag("Nodes",
		{
			undefined_tag("Name", 9999),
			short_tag("Unknown"),
			short_tag("Parent Node"),
			short_tag("Next Sibling Node"),
			short_tag("First Child Node"),
		}),
	});
};
