#include "cont.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* cont_group = new tag_collection(
	"cont",
	{
		
		short_tag("Flags"),
		short_tag("Scale Flags"),
		long_tag("Point Generation Rate"),
		long_tag("Min Point Velocity"),
		long_tag("Max Point Velocity"),
		undefined_tag("Point Velocity Cone Angle", 9999),
		long_tag("Inherited Velocity Fraction"),
		short_tag("Render Type"),
		short_tag("Unknown"),
		long_tag("Texture Repeats U"),
		long_tag("Texture Repeats V"),
		long_tag("Texture Animation U"),
		long_tag("Texture Animation V"),
		long_tag("Texture Animation Rate"),
		undefined_tag("Bitmap", 9999),
		short_tag("First Sequence Index"),
		short_tag("Sequence Count"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		short_tag("Shader Flags"),
		short_tag("Framebuffer Blend Function"),
		short_tag("Framebuffer Fade Mode"),
		short_tag("Map Flags"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Bitmap", 9999),
		short_tag("Anchor"),
		short_tag("Flags"),
		short_tag("Unknown"),
		short_tag("U-Animation Function"),
		long_tag("U-Animation Period"),
		long_tag("U-Animation Phase"),
		long_tag("U-Animation Scale"),
		short_tag("Unknown"),
		short_tag("V-Animation Function"),
		long_tag("V-Animation Period"),
		long_tag("V-Animation Phase"),
		long_tag("V-Animation Scale"),
		short_tag("Unknown"),
		short_tag("Rotation-Animation Function"),
		long_tag("Rotation-Animation Period"),
		long_tag("Rotation-Animation Phase"),
		long_tag("Rotation-Animation Scale"),
		long_tag("Rotation-Animation Center X"),
		long_tag("Rotation-Animation Center Y"),
		undefined_tag("Unknown", 9999),
		long_tag("ZSprite Radius Scale"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Point States",
		{
			long_tag("Duration Lower"),
			long_tag("Duration Upper"),
			long_tag("Transition Lower"),
			long_tag("Transition Upper"),
			undefined_tag("Physics", 9999),
			long_tag("Width"),
			long_tag("Color Lower Alpha"),
			long_tag("Color Lower Red"),
			long_tag("Color Lower Green"),
			long_tag("Color Lower Blue"),
			long_tag("Color Upper Alpha"),
			long_tag("Color Upper Red"),
			long_tag("Color Upper Green"),
			long_tag("Color Upper Blue"),
			undefined_tag("Scale Flags", 9999),
		}),
	});
};
