#include "crea.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* crea_group = new tag_collection(
	"crea",
	{
		
		short_tag("Object Type"),
		short_tag("Flags"),
		long_tag("Bounding Radius"),
		undefined_tag("Bounding Offset", 9999),
		long_tag("Acceleration Scale"),
		short_tag("Lightmap Shadow Mode"),
		byte_tag("Sweetener Size"),
		byte_tag("Unknown"),
		undefined_tag("Runtime Flags", 9999),
		long_tag("Dynamic Light Sphere Radius"),
		undefined_tag("Dynamic Light Sphere Offset", 9999),
		undefined_tag("Default Model Variant", 9999),
		undefined_tag("Model", 9999),
		undefined_tag("Crate Object", 9999),
		undefined_tag("Modifier Shader", 9999),
		undefined_tag("Creation Effect", 9999),
		undefined_tag("Material Effects", 9999),
		block_tag("AI Properties",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("AI Type Name", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("AI Size"),
			short_tag("Leap Jump Speed"),
		}),
		block_tag("Functions",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Import Name", 9999),
			undefined_tag("Export Name", 9999),
			undefined_tag("Turn Off With", 9999),
			long_tag("Minimum Value"),
			undefined_tag("Default Function", 9999),
			undefined_tag("Scale By", 9999),
		}),
		long_tag("Apply Collision Damage Scale"),
		undefined_tag("Game Acceleration", 9999),
		undefined_tag("Game Scale", 9999),
		undefined_tag("Absolute Acceleration", 9999),
		undefined_tag("Absolute Scale", 9999),
		short_tag("HUD Text Message Index"),
		short_tag("Unknown"),
		block_tag("Attachments",
		{
			undefined_tag("Type", 9999),
			undefined_tag("Marker", 9999),
			short_tag("Change Color"),
			short_tag("Unknown"),
			undefined_tag("Primary Scale", 9999),
			undefined_tag("Secondary Scale", 9999),
		}),
		block_tag("Widgets",
		{
			undefined_tag("Type", 9999),
		}),
		block_tag("Old Functions",
		{
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Change Colors",
		{
			block_tag("Initial Permutations",
			{
				long_tag("Weight"),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Variant Name", 9999),
			}),
			block_tag("Functions",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Scale Flags", 9999),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Darken By", 9999),
				undefined_tag("Scale By", 9999),
			}),
		}),
		block_tag("Predicted Resources",
		{
			short_tag("Type"),
			short_tag("Resource Index"),
			tagref_tag("Tag Index"),
		}),
		undefined_tag("Flags", 9999),
		short_tag("Default Team"),
		short_tag("Motion Sensor Blip Size"),
		undefined_tag("Turning Velocity Maximum", 9999),
		undefined_tag("Turning Acceleration Maximum", 9999),
		long_tag("Casual Turning Modifier"),
		long_tag("Autoaim Width"),
		undefined_tag("Flags", 9999),
		long_tag("Height Standing"),
		long_tag("Height Crouching"),
		long_tag("Radius"),
		long_tag("Mass"),
		undefined_tag("Living Material Name", 9999),
		undefined_tag("Dead Material Name", 9999),
		short_tag("Living Material Global Index"),
		short_tag("Dead Material Global Index"),
		block_tag("Dead Sphere Shapes",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("User Data", 9999),
			undefined_tag("Rotation i", 9999),
			long_tag("w Rotation i"),
			undefined_tag("Rotation j", 9999),
			long_tag("w Rotation j"),
			undefined_tag("Rotation k", 9999),
			long_tag("w Rotation k"),
			undefined_tag("Translation", 9999),
			long_tag("w Translation"),
		}),
		block_tag("Pill Shapes",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Bottom", 9999),
			long_tag("w Bottom"),
			undefined_tag("Top", 9999),
			long_tag("w Top"),
		}),
		block_tag("Sphere Shapes",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("User Data", 9999),
			undefined_tag("Rotation i", 9999),
			long_tag("w Rotation i"),
			undefined_tag("Rotation j", 9999),
			long_tag("w Rotation j"),
			undefined_tag("Rotation k", 9999),
			long_tag("w Rotation k"),
			undefined_tag("Translation", 9999),
			long_tag("w Translation"),
		}),
		undefined_tag("Maximum Slope Angle", 9999),
		undefined_tag("Downhill Falloff Angle", 9999),
		undefined_tag("Downhill Cutoff Angle", 9999),
		undefined_tag("Uphill Falloff Angle", 9999),
		undefined_tag("Uphill Cutoff Angle", 9999),
		long_tag("Downhill Velocity Scale"),
		long_tag("Uphill Velocity Scale"),
		long_tag("Minimum Normal k"),
		long_tag("Downhill k0"),
		long_tag("Downhill k1"),
		long_tag("Uphill k0"),
		long_tag("Uphill k1"),
		undefined_tag("Bank Angle", 9999),
		long_tag("Bank Apply Time"),
		long_tag("Bank Decay Time"),
		long_tag("Pitch Ratio"),
		long_tag("Maximum Velocity"),
		long_tag("Maximum Sidestep Velocity"),
		long_tag("Acceleration"),
		long_tag("Deceleration"),
		undefined_tag("Angular Velocity Maximum", 9999),
		undefined_tag("Angular Acceleration Maximum", 9999),
		long_tag("Crouch Velocity Modifier"),
		undefined_tag("Impact Damage", 9999),
		undefined_tag("Impact Shield Damage", 9999),
		undefined_tag("Destroy After Death Time", 9999),
	});
};
