#include "dc_s.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* dc_s_group = new tag_collection(
	"dc_s",
	{
		
		block_tag("Decorator",
		{
			long_tag("Grid Origin x"),
			long_tag("Grid Origin y"),
			long_tag("Grid Origin z"),
			long_tag("Cell Count Per Dimension"),
			block_tag("Cache Blocks",
			{
				long_tag("Resource Block Offset"),
				undefined_tag("Resource Block Size", 9999),
				undefined_tag("Section Data Size", 9999),
				undefined_tag("Resource Data Size", 9999),
				block_tag("Resources",
				{
					byte_tag("Type"),
					byte_tag("Unknown"),
					short_tag("Unknown"),
					short_tag("Primary Locator"),
					short_tag("Secondary Locator"),
					undefined_tag("Resource Data Size", 9999),
					undefined_tag("Resource Data Offset", 9999),
				}),
				tagref_tag("Owner Tag"),
				short_tag("Owner Tag Section Offset"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				block_tag("Cache Block Data",
				{
					block_tag("Placements",
					{
						long_tag("Internal Data 1"),
						long_tag("Compressed Position"),
						undefined_tag("Tint Color", 9999),
						undefined_tag("Lightmap Color", 9999),
						long_tag("Compressed Light Direction"),
						long_tag("Compressed Light 2 Direction"),
					}),
					block_tag("Decal Vertices",
					{
						long_tag("Position x"),
						long_tag("Position y"),
						long_tag("Position z"),
						long_tag("Texcoord 0 x"),
						long_tag("Texcoord 0 y"),
						long_tag("Texcoord 1 x"),
						long_tag("Texcoord 1 y"),
						undefined_tag("Color", 9999),
					}),
					block_tag("Decal Indices",
					{
						short_tag("Index"),
					}),
					undefined_tag("Decal Vertex Buffer", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					block_tag("Sprite Vertices",
					{
						long_tag("Position x"),
						long_tag("Position y"),
						long_tag("Position z"),
						long_tag("Offset i"),
						long_tag("Offset j"),
						long_tag("Offset k"),
						long_tag("Axis i"),
						long_tag("Axis j"),
						long_tag("Axis k"),
						long_tag("Texcoord x"),
						long_tag("Texcoord y"),
						undefined_tag("Color", 9999),
					}),
					block_tag("Sprite Indices",
					{
						short_tag("Index"),
					}),
					undefined_tag("Sprite Vertex Buffer", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Groups",
			{
				byte_tag("Decorator Set Index"),
				byte_tag("Decorator Type"),
				byte_tag("Shader Index"),
				byte_tag("Compressed Radius"),
				short_tag("Cluster"),
				short_tag("Cache Block Index"),
				short_tag("Decorator Start Index"),
				short_tag("Decorator Count"),
				short_tag("Vertex Start Offset"),
				short_tag("Vertex Count"),
				short_tag("Index Start Offset"),
				short_tag("Index Count"),
				long_tag("Compressed Bounding Center"),
			}),
			block_tag("Cells",
			{
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Cache Block Index"),
				short_tag("Group Count"),
				long_tag("Group Start Index"),
			}),
			block_tag("Decals",
			{
				byte_tag("Decorator Set Index"),
				byte_tag("Decorator Class"),
				byte_tag("Decorator Permutation"),
				byte_tag("Sprite Index"),
				long_tag("Position x"),
				long_tag("Position y"),
				long_tag("Position z"),
				long_tag("Left i"),
				long_tag("Left j"),
				long_tag("Left k"),
				long_tag("Up i"),
				long_tag("Up j"),
				long_tag("Up k"),
				long_tag("Extents i"),
				long_tag("Extents j"),
				long_tag("Extents k"),
				long_tag("Previous Position x"),
				long_tag("Previous Position y"),
				long_tag("Previous Position z"),
			}),
		}),
		block_tag("Decorator Palette",
		{
			undefined_tag("Decorator Set", 9999),
		}),
	});
};
