#include "effe.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* effe_group = new tag_collection(
	"effe",
	{
		
		undefined_tag("Flags", 9999),
		short_tag("Loop Start Event"),
		short_tag("Unknown"),
		undefined_tag("Unknown", 9999),
		block_tag("Locations",
		{
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("Marker Name", 9999),
		}),
		block_tag("Events",
		{
			undefined_tag("Flags", 9999),
			long_tag("Skip Fraction"),
			undefined_tag("Delay Bounds", 9999),
			undefined_tag("Duration Bounds", 9999),
			block_tag("Parts",
			{
				short_tag("Create In"),
				short_tag("Create In"),
				short_tag("Location Index"),
				short_tag("Flags"),
				undefined_tag("Runtime Base Group Tag", 9999),
				undefined_tag("Type", 9999),
				undefined_tag("Velocity Bound", 9999),
				undefined_tag("Velocity Cone Angle", 9999),
				undefined_tag("Angular Velocity Bounds", 9999),
				undefined_tag("Radius Modifier Bounds", 9999),
				undefined_tag("A Scales Values", 9999),
				undefined_tag("B Scales Values", 9999),
			}),
			block_tag("Beams",
			{
				undefined_tag("Shader", 9999),
				short_tag("Location Index"),
				short_tag("Unknown"),
				undefined_tag("Color", 9999),
				undefined_tag("Alpha", 9999),
				undefined_tag("Width", 9999),
				undefined_tag("Length", 9999),
				undefined_tag("Yaw", 9999),
				undefined_tag("Pitch", 9999),
			}),
			block_tag("Accelerations",
			{
				short_tag("Create In"),
				short_tag("Create In"),
				short_tag("Location"),
				short_tag("Unknown"),
				long_tag("Acceleration"),
				undefined_tag("Inner Cone Angle", 9999),
				undefined_tag("Outer Cone Angle", 9999),
			}),
			block_tag("Particle Systems",
			{
				undefined_tag("Particle", 9999),
				short_tag("Location"),
				short_tag("Unknown"),
				short_tag("Coordinate System"),
				short_tag("Environment"),
				short_tag("Disposition"),
				short_tag("Camera Mode"),
				short_tag("Sort Bias"),
				short_tag("Flags"),
				long_tag("LOD In Distance"),
				long_tag("LOD Feather In Delta"),
				long_tag("Inverse LOD Feather In"),
				long_tag("LOD Out Distance"),
				long_tag("LOD Feather Out Delta"),
				long_tag("Inverse LOD Feather Out"),
				block_tag("Emitters",
				{
					undefined_tag("Particle Physics", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					undefined_tag("Emission Shape", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					short_tag("Input"),
					short_tag("Range"),
					short_tag("Output Modifier Kind"),
					short_tag("Output Modifier"),
					undefined_tag("Function", 9999),
					undefined_tag("Translation Offset", 9999),
					undefined_tag("Relative Direction", 9999),
					long_tag("Unknown"),
					long_tag("Unknown"),
				}),
			}),
		}),
		undefined_tag("Looping Sound", 9999),
		short_tag("Location"),
		short_tag("Unknown"),
		long_tag("Always Play Distance"),
		long_tag("Never Play Distance"),
	});
};
