#include "goof.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* goof_group = new tag_collection(
	"goof",
	{
		
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Game Engine Settings",
		{
			undefined_tag("Setting Category", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("Options",
			{
				undefined_tag("Value Pairs", 9999),
			}),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("Default Variant Strings", 9999),
		block_tag("Default Variants",
		{
			undefined_tag("Variant Name", 9999),
			short_tag("Variant Type"),
			short_tag("Unknown"),
			block_tag("Settings",
			{
				undefined_tag("Setting Catergory", 9999),
				long_tag("Value"),
			}),
			short_tag("Description Index"),
			short_tag("Unknown"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New Slayer Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New King Of The Hill Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New Unknown Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New Oddball Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New Juggernaut Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New Unknown Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New Capture The Flag Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New Assault Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Create New Territories Variant",
		{
			undefined_tag("Setting Catergory", 9999),
			long_tag("Value"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
	});
};
