#include "hlmt.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* hlmt_group = new tag_collection(
	"hlmt",
	{
		
		undefined_tag("Render Model", 9999),
		undefined_tag("Collision Model", 9999),
		undefined_tag("Animation", 9999),
		undefined_tag("Physics", 9999),
		undefined_tag("Physics Model", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		long_tag("Disappear Distance"),
		long_tag("Begin Fade Distance"),
		undefined_tag("Unknown", 9999),
		long_tag("Reduce To L1"),
		long_tag("Reduce To L2"),
		long_tag("Reduce To L3"),
		long_tag("Reduce To L4"),
		long_tag("Reduce To L5"),
		undefined_tag("Unknown", 9999),
		short_tag("Shadow Fade Distance"),
		short_tag("Unknown"),
		block_tag("Variants",
		{
			undefined_tag("Name", 9999),
			byte_tag("Runtime Model Region 0 Index"),
			byte_tag("Runtime Model Region 1 Index"),
			byte_tag("Runtime Model Region 2 Index"),
			byte_tag("Runtime Model Region 3 Index"),
			byte_tag("Runtime Model Region 4 Index"),
			byte_tag("Runtime Model Region 5 Index"),
			byte_tag("Runtime Model Region 6 Index"),
			byte_tag("Runtime Model Region 7 Index"),
			byte_tag("Runtime Model Region 8 Index"),
			byte_tag("Runtime Model Region 9 Index"),
			byte_tag("Runtime Model Region 10 Index"),
			byte_tag("Runtime Model Region 11 Index"),
			byte_tag("Runtime Model Region 12 Index"),
			byte_tag("Runtime Model Region 13 Index"),
			byte_tag("Runtime Model Region 14 Index"),
			byte_tag("Runtime Model Region 15 Index"),
			block_tag("Regions",
			{
				undefined_tag("Region Name", 9999),
				byte_tag("Runtime Model Region Index"),
				undefined_tag("Runtime Flags", 9999),
				short_tag("Parent Variant Index"),
				block_tag("Permutations",
				{
					undefined_tag("Permutation Name", 9999),
					byte_tag("Model Permutation Index"),
					undefined_tag("Flags", 9999),
					short_tag("Unknown"),
					long_tag("Probability"),
					block_tag("States",
					{
						undefined_tag("Permutation Name", 9999),
						byte_tag("Permutation Index"),
						undefined_tag("Property Flags", 9999),
						short_tag("State"),
						undefined_tag("Looping Effect", 9999),
						undefined_tag("Looping Effect Marker Name", 9999),
						long_tag("Initial Probability"),
					}),
					byte_tag("Runtime Permutation Index"),
					byte_tag("Runtime Permutation Index"),
					byte_tag("Runtime Permutation Index"),
					byte_tag("Runtime Permutation Index"),
					byte_tag("Runtime Permutation Index"),
					byte_tag("Unknown"),
					short_tag("Unknown"),
					undefined_tag("Unknown", 9999),
				}),
				short_tag("Sort Order"),
				short_tag("Unknown"),
			}),
			block_tag("Objects",
			{
				undefined_tag("Parent Marker", 9999),
				undefined_tag("Child Marker", 9999),
				undefined_tag("Child Object", 9999),
			}),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Dialogue Sound Effect", 9999),
			undefined_tag("Dialogue", 9999),
		}),
		block_tag("Materials",
		{
			undefined_tag("Material Name", 9999),
			short_tag("Material Type"),
			short_tag("Damage Section Index"),
			short_tag("Collision Material Index"),
			short_tag("Damager Material Index"),
			undefined_tag("Global Material Name", 9999),
			short_tag("Global Material Index"),
			short_tag("Unknown"),
		}),
		block_tag("New Damage Info",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Global Indirect Material Name", 9999),
			short_tag("Indirect Damage Section Index"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			byte_tag("Collision Damage Reporting Type"),
			byte_tag("Response Damage Reporting Type"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Maximum Vitality"),
			long_tag("Minimum Stun Damage"),
			long_tag("Stun Time"),
			long_tag("Recharge Time"),
			long_tag("Recharge Fraction"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Shield Damaged First Person Shader", 9999),
			undefined_tag("Shield Damaged Shader", 9999),
			long_tag("Maximum Shield Vitality"),
			undefined_tag("Global Shield Material Name", 9999),
			long_tag("Minimum Stun Damage"),
			long_tag("Stun Time"),
			long_tag("Recharge Time"),
			long_tag("Shield Damaged Threshold"),
			undefined_tag("Shield Damaged Effect", 9999),
			undefined_tag("Shield Depleted Effect", 9999),
			undefined_tag("Shield Recharging Effect", 9999),
			block_tag("Damage Sections",
			{
				undefined_tag("Name", 9999),
				undefined_tag("Flags", 9999),
				long_tag("Vitality Percentage"),
				block_tag("Instant Responses",
				{
					short_tag("Response Type"),
					undefined_tag("", 9999),
					short_tag("Constraint Damage Type"),
					undefined_tag("Flags", 9999),
					long_tag("Damage Threshold"),
					undefined_tag("Transition Effect", 9999),
					undefined_tag("Transition Damage Effect", 9999),
					undefined_tag("Region", 9999),
					short_tag("New State"),
					short_tag("Runtime Region Index"),
					undefined_tag("Effect Marker Name", 9999),
					undefined_tag("Damage Effect Marker Name", 9999),
					long_tag("Response Delay"),
					undefined_tag("Delay Effect", 9999),
					undefined_tag("Delay Effect Marker Name", 9999),
					undefined_tag("", 9999),
					undefined_tag("Constraint/Group Name", 9999),
					undefined_tag("Ejecting Seat Label", 9999),
					long_tag("Skip Fraction"),
					undefined_tag("Destroyed Child Object Marker Name", 9999),
					long_tag("Total Damage Threshold"),
				}),
				undefined_tag("null block here 1", 9999),
				undefined_tag("null block here 1", 9999),
				undefined_tag("null block here 2", 9999),
				undefined_tag("null block here 2", 9999),
				long_tag("Stun Time"),
				long_tag("Recharge Time"),
				long_tag("Runtime Recharge Velocity"),
				undefined_tag("Resurrection Restored Region Name", 9999),
				short_tag("Ressurection Region Runtime Index"),
				short_tag("Unknown"),
			}),
			block_tag("Nodes",
			{
				short_tag("Runtime Damage Part"),
				short_tag("Unknown"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			short_tag("Global Shield Material Index"),
			short_tag("Global Indirect Material Index"),
			long_tag("Shield Recharge Velocity"),
			long_tag("Health Recharge Velocity"),
			block_tag("Damage Seats",
			{
				undefined_tag("Seat Label", 9999),
				long_tag("Direct Damage Scale"),
				long_tag("Damage Transfer Fall-Off Radius"),
				long_tag("Maximum Transfer Damage Scale"),
				long_tag("Minimum Transfer Damage Scale"),
			}),
			block_tag("Damage Constraints",
			{
				undefined_tag("Physics Model Constraint Name", 9999),
				undefined_tag("Damage Constraint Name", 9999),
				undefined_tag("Damage Constraint Group Name", 9999),
				long_tag("Group Probability Scale"),
				short_tag("Constraint Type"),
				short_tag("Constraint Index"),
			}),
			undefined_tag("Overshield First Person Shader", 9999),
			undefined_tag("Overshield Shader", 9999),
		}),
		block_tag("Targets",
		{
			undefined_tag("Marker Name", 9999),
			long_tag("Size"),
			undefined_tag("Cone Angle", 9999),
			short_tag("Damage Section Index"),
			short_tag("Variant Index"),
			long_tag("Targeting Relevance"),
			undefined_tag("Lock-On Flags", 9999),
			long_tag("Lock-On Distance"),
		}),
		block_tag("Collision Regions",
		{
			undefined_tag("Name", 9999),
			byte_tag("Collision Region Index"),
			byte_tag("Physics Region Index"),
			short_tag("Unknown"),
			block_tag("Permutations",
			{
				undefined_tag("Name", 9999),
				undefined_tag("Flags", 9999),
				byte_tag("Collision Permutation Index"),
				byte_tag("Physics Permutation Index"),
				byte_tag("Unknown"),
			}),
		}),
		block_tag("Nodes",
		{
			undefined_tag("Name", 9999),
			short_tag("Parent Node Index"),
			short_tag("First Child Node Index"),
			short_tag("Next Sibling Node Index"),
			short_tag("Unknown"),
			undefined_tag("Default Translation", 9999),
			undefined_tag("Default Rotation", 9999),
			long_tag("Default Inverse Scale"),
			undefined_tag("Default Inverse Forward", 9999),
			undefined_tag("Default Inverse Left", 9999),
			undefined_tag("Default Inverse Up", 9999),
			undefined_tag("Default Inverse Position", 9999),
		}),
		undefined_tag("Node List Checksum", 9999),
		block_tag("Model Object Data",
		{
			short_tag("Type"),
			short_tag("Unknown"),
			undefined_tag("Offset", 9999),
			long_tag("Radius"),
		}),
		undefined_tag("Default Dialogue", 9999),
		undefined_tag("Active Camo Shader", 9999),
		undefined_tag("Flags", 9999),
		undefined_tag("Default Dialogue Effect", 9999),
		undefined_tag("Render-Only Node Flags 1", 9999),
		undefined_tag("Render-Only Node Flags 2", 9999),
		undefined_tag("Render-Only Node Flags 3", 9999),
		undefined_tag("Render-Only Node Flags 4", 9999),
		undefined_tag("Render-Only Node Flags 5", 9999),
		undefined_tag("Render-Only Node Flags 6", 9999),
		undefined_tag("Render-Only Node Flags 7", 9999),
		undefined_tag("Render-Only Node Flags 8", 9999),
		undefined_tag("Render-Only Section Flags 1", 9999),
		undefined_tag("Render-Only Section Flags 2", 9999),
		undefined_tag("Render-Only Section Flags 3", 9999),
		undefined_tag("Render-Only Section Flags 4", 9999),
		undefined_tag("Render-Only Section Flags 5", 9999),
		undefined_tag("Render-Only Section Flags 6", 9999),
		undefined_tag("Render-Only Section Flags 7", 9999),
		undefined_tag("Render-Only Section Flags 8", 9999),
		undefined_tag("Runtime Flags", 9999),
		block_tag("Scenario Load Parameters",
		{
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("Scenario", 9999),
			undefined_tag("Parameters", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("Hologram Shader", 9999),
		undefined_tag("Hologram Control Function", 9999),
	});
};
