#include "hudg.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* hudg_group = new tag_collection(
	"hudg",
	{
		
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		short_tag("Anchor"),
		undefined_tag("Anchor Offset (y)", 9999),
		undefined_tag("Anchor Offset (x)", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("obsolete1", 9999),
		undefined_tag("obsolete2", 9999),
		long_tag("Message Up time"),
		long_tag("Message Fade time"),
		undefined_tag("Icon Color", 9999),
		undefined_tag("Text Color", 9999),
		long_tag("Text Spacing"),
		undefined_tag("Item message text", 9999),
		undefined_tag("Icon Bitmap", 9999),
		undefined_tag("Alternate Icon", 9999),
		block_tag("Button Icons",
		{
			short_tag("Sequence Index"),
			short_tag("Width Offset"),
			short_tag("Offset from Reference Corner (x)"),
			short_tag("Offset from Reference Corner (y)"),
			undefined_tag("Override Icon Color", 9999),
			undefined_tag("Frame Rate (0-30)", 9999),
			undefined_tag("Flags", 9999),
			short_tag("Text Index"),
		}),
		undefined_tag("HUD Help Default Color", 9999),
		undefined_tag("HUD Help Flashing Color", 9999),
		long_tag("HUD Help Flash Period"),
		long_tag("HUD Help Flash Delay"),
		short_tag("Number of Flashes"),
		short_tag("HUD Help Flash Flags"),
		long_tag("HUD Help Flash Length"),
		undefined_tag("Disabled Color", 9999),
		undefined_tag("Disabled Color", 9999),
		undefined_tag("HUD messages", 9999),
		undefined_tag("Objective Default", 9999),
		undefined_tag("Objective Flashing", 9999),
		long_tag("Objective Flash Period"),
		long_tag("Objective Flash Delay"),
		short_tag("Number of Flashes"),
		short_tag("HUD Help Flash Flags"),
		long_tag("Objective Flash Length"),
		undefined_tag("Disabled Color", 9999),
		short_tag("Objective uptime ticks"),
		short_tag("Objective fade ticks"),
		long_tag(" Waypoint Top offset"),
		long_tag("Waypoint Bottom offset"),
		long_tag("Waypoint Left offset"),
		long_tag("Waypoint Right offset"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Arrow bitmap", 9999),
		block_tag("Waypoint Arrows",
		{
			string_tag("Name"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Color", 9999),
			long_tag("Opacity"),
			long_tag("Translucency"),
			short_tag("On Screen Sequence Index"),
			short_tag("Off Screen Sequence Index"),
			short_tag("Occluded Sequence Index"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Flags", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Multiplayer HUD Scale"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Motion Sensor Range"),
		long_tag("Motion Sensor Velocity Sensitivity"),
		long_tag("Motion Sensor Scale"),
		short_tag("Default Title Chapter Bounds (top)"),
		short_tag("Default Title Chapter Bounds (left)"),
		short_tag("Default Title Chapter Bounds (bottom)"),
		short_tag("Default Title Chapter Bounds (right)"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		short_tag("HUD Damage Indicator Offset (top)"),
		short_tag("HUD Damage Indicator Offset (bottom)"),
		short_tag("HUD Damage Indicator Offset (left)"),
		short_tag("HUD Damage Indicator Offset (right)"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Damage Indicator Bitmap", 9999),
		short_tag("Sequence Index"),
		short_tag("Multiplayer Sequence Index"),
		undefined_tag("Damage Indicator Color", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Not Much Time Left Default Color", 9999),
		undefined_tag("Not Much Time Left Flash Color", 9999),
		long_tag("Not Much Time Left Flash Period"),
		long_tag("Not Much Time Left Flash Delay"),
		short_tag("Number of Flashes"),
		short_tag("Not Much Time Left Flash Flags"),
		long_tag("Not Much Time Left Flash Length"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Time Out Default Color", 9999),
		undefined_tag("Time Out Flashing Color", 9999),
		long_tag("Time Out Flash Period"),
		long_tag("Time Out Flash Delay"),
		short_tag("Number of Flashes"),
		short_tag("Time Out Flash Flags"),
		long_tag("Time Out Flash Length"),
		undefined_tag("Disabled Time Out Default Color", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Carnage Report Bitmap", 9999),
		short_tag("Loading Begin Text"),
		short_tag("Loading End Text"),
		short_tag("Checkpoint Begin Text"),
		short_tag("Checkpoint End Text"),
		undefined_tag("Checkpoint Sound", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("HUD text", 9999),
		block_tag("Dashlights",
		{
			undefined_tag("Bitmap", 9999),
			undefined_tag("Shader", 9999),
			short_tag("Sequence Index"),
			short_tag("Time Out Flash Flags"),
			undefined_tag("Sound", 9999),
		}),
		block_tag("Waypoint Arrows",
		{
			undefined_tag("Bitmap", 9999),
			undefined_tag("Shader", 9999),
			long_tag("Sequence Index"),
			long_tag("Smallest Size"),
			long_tag("Smallest Distance"),
			undefined_tag("Border Bitmap", 9999),
		}),
		block_tag("WayPoints",
		{
			undefined_tag("Bitmap", 9999),
			undefined_tag("Sahder", 9999),
			short_tag("Onscreen Sequence Index"),
			short_tag("Occluded Sequence Index"),
			short_tag("Offscreen Sequence Index"),
			short_tag("Unknown"),
		}),
		block_tag("HUD sounds",
		{
			undefined_tag("Chief sound", 9999),
			undefined_tag("Flags", 9999),
			long_tag("Scale"),
			undefined_tag("Dervish sound", 9999),
		}),
		block_tag("Player Training Data",
		{
			undefined_tag("Display String", 9999),
			undefined_tag("Display String 2", 9999),
			undefined_tag("Display String 3", 9999),
			short_tag("Maximum Display Time"),
			short_tag("Display Count"),
			short_tag("Dissapear Delay"),
			short_tag("Redisplay Delay"),
			long_tag("Display Delay"),
			short_tag("Flags"),
			short_tag("Unknown"),
		}),
		undefined_tag("Primary Message Sound", 9999),
		undefined_tag("Secondary Message Sound", 9999),
		undefined_tag("boot griefer string", 9999),
		undefined_tag("cannot boot griefer string", 9999),
		undefined_tag("Training Shader", 9999),
		undefined_tag("Human Training Top Right", 9999),
		undefined_tag("Human Training Top Center", 9999),
		undefined_tag("Human Training Top Left", 9999),
		undefined_tag("Human Training Center", 9999),
		undefined_tag("Elite Training Top Right", 9999),
		undefined_tag("Elite Training Top Center", 9999),
		undefined_tag("Elite Training Top Left", 9999),
		undefined_tag("Elite Training Center", 9999),
	});
};
