#include "jmad.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* jmad_group = new tag_collection(
	"jmad",
	{
		
		undefined_tag("Parent Animation Graph", 9999),
		undefined_tag("Inheritance Flags", 9999),
		undefined_tag("Private Flags", 9999),
		short_tag("Animation Codec Pack"),
		block_tag("Skeleton Nodes",
		{
			undefined_tag("Name", 9999),
			short_tag("Next Sibling Node Index"),
			short_tag("First Child Node Index"),
			short_tag("Parent Node Index"),
			undefined_tag("Model Flags", 9999),
			undefined_tag("Node Joint Flags", 9999),
			undefined_tag("Base Vector", 9999),
			long_tag("Vector Range"),
			long_tag("z Position"),
		}),
		block_tag("Sound References",
		{
			undefined_tag("Sound", 9999),
			short_tag("Flags"),
			short_tag("Unknown"),
		}),
		block_tag("Effect References",
		{
			undefined_tag("Effect", 9999),
			short_tag("Flags"),
			short_tag("Unknown"),
		}),
		block_tag("Blend Screens",
		{
			undefined_tag("Label", 9999),
			undefined_tag("Right Yaw Per Frame", 9999),
			undefined_tag("Left Yaw Per Frame", 9999),
			short_tag("Right Frame Count"),
			short_tag("Left Frame Count"),
			undefined_tag("Down Pitch Per Frame", 9999),
			undefined_tag("Up Pitch Per Frame", 9999),
			short_tag("Down Pitch Frame Count"),
			short_tag("Up Pitch Frame Count"),
		}),
		block_tag("Animations",
		{
			undefined_tag("Name", 9999),
			long_tag("Node List Checksum"),
			long_tag("Production Checksum"),
			long_tag("Import Checksum"),
			byte_tag("Type"),
			byte_tag("Frame Info Type"),
			byte_tag("Blend Screen"),
			undefined_tag("Node Count", 9999),
			short_tag("Frame Count"),
			undefined_tag("Internal Flags", 9999),
			undefined_tag("Production Flags", 9999),
			short_tag("Playback Flags"),
			byte_tag("Desired Compression"),
			byte_tag("Current Compression"),
			long_tag("Weight"),
			short_tag("Loop Frame Index"),
			short_tag("Parent Animation Index"),
			short_tag("Next Animation Index"),
			short_tag("Unknown"),
			undefined_tag("Resource", 9999),
			byte_tag("Unknown"),
			byte_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			block_tag("Frame Events",
			{
				short_tag("Type"),
				short_tag("Frame"),
			}),
			block_tag("Sound Events",
			{
				short_tag("Sound"),
				short_tag("Frame"),
				undefined_tag("Marker Name", 9999),
			}),
			block_tag("Effect Events",
			{
				short_tag("Effect"),
				short_tag("Frame"),
			}),
			block_tag("Object-Space Parent Nodes",
			{
				short_tag("Node Index"),
				short_tag("Component Flags"),
				undefined_tag("Rotation", 9999),
				undefined_tag("Default Translation", 9999),
				long_tag("Default Scale"),
			}),
		}),
		block_tag("Modes",
		{
			undefined_tag("Label", 9999),
			block_tag("Weapon Class",
			{
				undefined_tag("Label", 9999),
				block_tag("Weapon Type",
				{
					undefined_tag("Label", 9999),
					block_tag("Actions",
					{
						undefined_tag("Label", 9999),
						short_tag("Graph Index"),
						short_tag("Animation Index"),
					}),
					block_tag("Overlays",
					{
						undefined_tag("Label", 9999),
						short_tag("Graph Index"),
						short_tag("Animation Index"),
					}),
					block_tag("Death and Damage",
					{
						undefined_tag("Label", 9999),
						block_tag("Directions",
						{
							block_tag("Regions",
							{
								short_tag("Graph Index"),
								short_tag("Animation Index"),
							}),
						}),
					}),
					block_tag("Transitions",
					{
						undefined_tag("Full Name", 9999),
						undefined_tag("State Name", 9999),
						short_tag("Unknown"),
						byte_tag("Index A"),
						byte_tag("Index B"),
						block_tag("Destinations",
						{
							undefined_tag("Full Name", 9999),
							undefined_tag("Mode Name", 9999),
							undefined_tag("State Name", 9999),
							byte_tag("Frame Event Link"),
							byte_tag("Unknown"),
							byte_tag("Index A"),
							byte_tag("Index B"),
							short_tag("Graph Index"),
							short_tag("Animation Index"),
						}),
					}),
					block_tag("High Precache",
					{
						long_tag("Cache Block Index"),
					}),
					block_tag("Low Precache",
					{
						long_tag("Cache Block Index"),
					}),
				}),
				block_tag("Weapon ik",
				{
					undefined_tag("Marker", 9999),
					undefined_tag("Attach To Marker", 9999),
				}),
			}),
			block_tag("Mode ik",
			{
				undefined_tag("Marker", 9999),
				undefined_tag("Attach To Marker", 9999),
			}),
		}),
		block_tag("Vehicle Suspension",
		{
			undefined_tag("Label", 9999),
			short_tag("Graph Index"),
			short_tag("Animation"),
			undefined_tag("Marker Name", 9999),
			long_tag("Mass Point Offset"),
			long_tag("Full Extension Ground Depth"),
			long_tag("Full Compression Ground Depth"),
			undefined_tag("Region Name", 9999),
			long_tag("Mass Point Offset"),
			long_tag("Expression Ground Depth"),
			long_tag("Compression Ground Depth"),
		}),
		block_tag("Object Overlays",
		{
			undefined_tag("Label", 9999),
			short_tag("Graph Index"),
			short_tag("Animation"),
			short_tag("Unknown"),
			short_tag("Function Controls"),
			undefined_tag("Function", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		block_tag("Inheritance List",
		{
			undefined_tag("Inherited Graph", 9999),
			block_tag("Node Map",
			{
				short_tag("Local Node"),
			}),
			block_tag("Node Map Flags",
			{
				undefined_tag("Local Node Flags", 9999),
			}),
			long_tag("Root z Offset"),
			undefined_tag("Inheritance Flags", 9999),
		}),
		block_tag("Weapon List",
		{
			undefined_tag("Weapon Name", 9999),
			undefined_tag("Weapon Class", 9999),
		}),
		undefined_tag("Left Arm Nodes Nodes 1", 9999),
		undefined_tag("Left Arm Nodes 2", 9999),
		undefined_tag("Left Arm Nodes 3", 9999),
		undefined_tag("Left Arm Nodes 4", 9999),
		undefined_tag("Left Arm Nodes 5", 9999),
		undefined_tag("Left Arm Nodes 6", 9999),
		undefined_tag("Left Arm Nodes 7", 9999),
		undefined_tag("Left Arm Nodes 8", 9999),
		undefined_tag("Right Arm Nodes 1", 9999),
		undefined_tag("Right Arm Nodes 2", 9999),
		undefined_tag("Right Arm Nodes 3", 9999),
		undefined_tag("Right Arm Nodes 4", 9999),
		undefined_tag("Right Arm Nodes 5", 9999),
		undefined_tag("Right Arm Nodes 6", 9999),
		undefined_tag("Right Arm Nodes 7", 9999),
		undefined_tag("Right Arm Nodes 8", 9999),
		undefined_tag("Last Import Results", 9999),
		block_tag("Additional Node Data",
		{
			undefined_tag("Node Name", 9999),
			undefined_tag("Default Rotation", 9999),
			undefined_tag("Default Translation", 9999),
			long_tag("Default Scale"),
			undefined_tag("Minimum Bounds", 9999),
			undefined_tag("Maximum Bounds", 9999),
		}),
	});
};
