#include "jpt!.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* jpt__group = new tag_collection(
	"jpt!",
	{
		
		undefined_tag("Radius", 9999),
		long_tag("Cutoff Scale"),
		undefined_tag("Flags", 9999),
		short_tag("Side Effect"),
		short_tag("Category"),
		undefined_tag("Flags", 9999),
		long_tag("Area Of Effect Core Radius"),
		long_tag("Damage Lower Bound"),
		undefined_tag("Damage Upper Bound", 9999),
		undefined_tag("Damage Inner Cone Angle", 9999),
		undefined_tag("Damage Outer Cone Angle", 9999),
		long_tag("Active Camoflage Damage"),
		long_tag("Stun"),
		long_tag("Maximum Stun"),
		long_tag("Stun Time"),
		long_tag("Instantaneous Acceleration"),
		long_tag("Rider Direct Damage Scale"),
		long_tag("Rider Maximum Transfer Damage Scale"),
		long_tag("Rider Minimum Transfer Damage Scale"),
		undefined_tag("General Damage", 9999),
		undefined_tag("Specific Damage", 9999),
		long_tag("AI Stun Radius"),
		undefined_tag("AI Stun Bounds", 9999),
		long_tag("Shake Radius"),
		long_tag("EMP Radius"),
		block_tag("Player Responses",
		{
			short_tag("Response Type"),
			short_tag("Unknown"),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			short_tag("Type"),
			short_tag("Priority"),
			long_tag("Duration"),
			short_tag("Fade Function"),
			short_tag("Unknown"),
			long_tag("Maximum Intensity"),
			undefined_tag("Color", 9999),
			long_tag("Low Frequency Vibration Duration"),
			undefined_tag("Low Frequency Vibration Function", 9999),
			long_tag("High Frequency Vibration Duration"),
			undefined_tag("High Frequency Vibration Function", 9999),
			undefined_tag("Effect Name", 9999),
			long_tag("Duration"),
			undefined_tag("Effect Scale Function", 9999),
		}),
		long_tag("Duration"),
		short_tag("Fade Function"),
		short_tag("Unknown"),
		undefined_tag("Rotation", 9999),
		long_tag("Pushback"),
		undefined_tag("Jitter", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		long_tag("Duration"),
		short_tag("Falloff Function"),
		short_tag("Unknown"),
		long_tag("Random Translation"),
		undefined_tag("Random Rotation", 9999),
		short_tag("Wobble Function"),
		short_tag("Unknown"),
		long_tag("Wobble Function Period"),
		long_tag("Wobble Weight"),
		undefined_tag("Sound", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		long_tag("Forward Velocity"),
		long_tag("Forward Radius"),
		long_tag("Forward Exponent"),
		long_tag("Outward Velocity"),
		long_tag("Outward Radius"),
		long_tag("Outward Exponent"),
	});
};
