#include "ltmp.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* ltmp_group = new tag_collection(
	"ltmp",
	{
		
		long_tag("Search Distance Lower Bound"),
		long_tag("Search Distance Upper Bound"),
		long_tag("Luminels Per World Unit"),
		long_tag("Output White Reference"),
		long_tag("Output Black Reference"),
		long_tag("Output Schlick Reference"),
		long_tag("Diffuse Map Scale"),
		long_tag("Sun Scale"),
		long_tag("Sky Scale"),
		long_tag("Indirect Scale"),
		long_tag("Prt Scale"),
		long_tag("Surface Light Scale"),
		long_tag("Scenario Light Scale"),
		long_tag("Lightprobe Interpolation Override"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Lightmap Groups",
		{
			short_tag("Type"),
			short_tag("Flags"),
			long_tag("Structure Checksum"),
			block_tag("Section Palette",
			{
				long_tag("First Palette Color"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Writable Palettes",
			{
				long_tag("First Palette Color"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			undefined_tag("Bitmap Group", 9999),
			block_tag("Clusters",
			{
				short_tag("Total Vertex Count"),
				short_tag("Total Triangle Count"),
				short_tag("Total Part Count"),
				short_tag("Shadow-Casting Triangle Count"),
				short_tag("Shadow-Casting Part Count"),
				short_tag("Opaque Point Count"),
				short_tag("Opaque Vertex Count"),
				short_tag("Opaque Part Count"),
				byte_tag("Opague Max Nodes/Vertex"),
				byte_tag("Transparent Max Nodes/Vertex"),
				short_tag("Shadow-Casting Rigid Triangle"),
				short_tag("Geometry Classification"),
				short_tag("Geometry Compression Flags"),
				block_tag("Compression",
				{
					undefined_tag("Position Bounds X", 9999),
					undefined_tag("Position Bounds Y", 9999),
					undefined_tag("Position Bounds Z", 9999),
					undefined_tag("Texcoord Bounds X", 9999),
					undefined_tag("Texcoord Bounds Y", 9999),
					undefined_tag("Secondary Texcoord Bounds X", 9999),
					undefined_tag("Secondary Texcoord Bounds Y", 9999),
				}),
				byte_tag("Hardware Node Count"),
				byte_tag("Node Map Size"),
				short_tag("Software Plane Count"),
				short_tag("Total Subpart Count"),
				short_tag("Section Lighting Flags"),
				long_tag("Resource Block Offset"),
				undefined_tag("Resource Block Size", 9999),
				undefined_tag("Section Data Size", 9999),
				undefined_tag("Resource Data Size", 9999),
				block_tag("Resources",
				{
					byte_tag("Type"),
					byte_tag("Unknown"),
					short_tag("Unknown"),
					short_tag("Primary Locator"),
					short_tag("Secondary Locator"),
					undefined_tag("Resource Data Size", 9999),
					undefined_tag("Resource Data Offset", 9999),
				}),
				tagref_tag("Owner Tag"),
				short_tag("Owner Tag Section Offset"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				block_tag("Cache Data",
				{
					block_tag("Parts",
					{
						short_tag("Type"),
						short_tag("Flags"),
						short_tag("Material Index"),
						short_tag("Strip Start Index"),
						short_tag("Strip Length"),
						short_tag("First Subpart Index"),
						short_tag("Subpart Count"),
						byte_tag("Max Nodes/Vertex"),
						byte_tag("Contributing Compound Node Count"),
						undefined_tag("Position", 9999),
						byte_tag("Node Index 1"),
						byte_tag("Node Index 2"),
						byte_tag("Node Index 3"),
						byte_tag("Node Index 4"),
						long_tag("Node Weight 1"),
						long_tag("Node Weight 2"),
						long_tag("Node Weight 3"),
						long_tag("LOD Mipmap Magic Number"),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
					}),
					block_tag("Subparts",
					{
						short_tag("Indices Start Index"),
						short_tag("Indices Length"),
						short_tag("Visibility Bounds Index"),
						short_tag("Part Index"),
					}),
					block_tag("Visibility Bounds",
					{
						long_tag("Position X"),
						long_tag("Position Y"),
						long_tag("Position Z"),
						long_tag("Radius"),
						byte_tag("Node 0"),
						byte_tag("Unknown"),
						short_tag("Unknown"),
					}),
					block_tag("Raw Vertices",
					{
						undefined_tag("Position", 9999),
						long_tag("Old Node Index 1"),
						long_tag("Old Node Index 2"),
						long_tag("Old Node Index 3"),
						long_tag("Old Node Index 4"),
						long_tag("Old Node Weight 1"),
						long_tag("Old Node Weight 2"),
						long_tag("Old Node Weight 3"),
						long_tag("Old Node Weight 4"),
						long_tag("New Node Index 1"),
						long_tag("New Node Index 2"),
						long_tag("New Node Index 3"),
						long_tag("New Node Index 4"),
						long_tag("Use New Node Indices"),
						long_tag("Adjusted Compound Node Index"),
						undefined_tag("Texcoord", 9999),
						undefined_tag("Normal", 9999),
						undefined_tag("Binormal", 9999),
						undefined_tag("Tangent", 9999),
						undefined_tag("Anisotropic Binormal", 9999),
						undefined_tag("Secondary Texcoord", 9999),
						undefined_tag("Primary Lightmap Color", 9999),
						undefined_tag("Primary Lightmap Texcoord", 9999),
						undefined_tag("Primary Lightmap Incident Direction", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
					}),
					block_tag("Strip Indices",
					{
						short_tag("Index"),
					}),
					undefined_tag("Visibility MOPP Code", 9999),
					block_tag("MOPP Reorder Table",
					{
						short_tag("Index"),
					}),
					block_tag("Vertex Buffers",
					{
						undefined_tag("Vertex Buffer", 9999),
					}),
					undefined_tag("Unknown", 9999),
				}),
			}),
			block_tag("Cluster Render Info",
			{
				short_tag("Bitmap Index"),
				short_tag("Palette Index"),
			}),
			block_tag("Poop Definitions",
			{
				short_tag("Total Vertex Count"),
				short_tag("Total Triangle Count"),
				short_tag("Total Part Count"),
				short_tag("Shadow-Casting Triangle Count"),
				short_tag("Shadow-Casting Part Count"),
				short_tag("Opaque Point Count"),
				short_tag("Opaque Vertex Count"),
				short_tag("Opaque Part Count"),
				byte_tag("Opague Max Nodes/Vertex"),
				byte_tag("Transparent Max Nodes/Vertex"),
				short_tag("Shadow-Casting Rigid Triangle"),
				short_tag("Geometry Classification"),
				short_tag("Geometry Compression Flags"),
				block_tag("Compression",
				{
					undefined_tag("Position Bounds X", 9999),
					undefined_tag("Position Bounds Y", 9999),
					undefined_tag("Position Bounds Z", 9999),
					undefined_tag("Texcoord Bounds X", 9999),
					undefined_tag("Texcoord Bounds Y", 9999),
					undefined_tag("Secondary Texcoord Bounds X", 9999),
					undefined_tag("Secondary Texcoord Bounds Y", 9999),
				}),
				byte_tag("Hardware Node Count"),
				byte_tag("Node Map Size"),
				short_tag("Software Plane Count"),
				short_tag("Total Subpart Count"),
				short_tag("Section Lighting Flags"),
				long_tag("Resource Block Offset"),
				undefined_tag("Resource Block Size", 9999),
				undefined_tag("Section Data Size", 9999),
				undefined_tag("Resource Data Size", 9999),
				block_tag("Resources",
				{
					byte_tag("Type"),
					byte_tag("Unknown"),
					short_tag("Unknown"),
					short_tag("Primary Locator"),
					short_tag("Secondary Locator"),
					undefined_tag("Resource Data Size", 9999),
					undefined_tag("Resource Data Offset", 9999),
				}),
				tagref_tag("Owner Tag"),
				short_tag("Owner Tag Section Offset"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				block_tag("Cache Data",
				{
					block_tag("Parts",
					{
						short_tag("Type"),
						short_tag("Flags"),
						short_tag("Material Index"),
						short_tag("Strip Start Index"),
						short_tag("Strip Length"),
						short_tag("First Subpart Index"),
						short_tag("Subpart Count"),
						byte_tag("Max Nodes/Vertex"),
						byte_tag("Contributing Compound Node Count"),
						undefined_tag("Position", 9999),
						byte_tag("Node Index 1"),
						byte_tag("Node Index 2"),
						byte_tag("Node Index 3"),
						byte_tag("Node Index 4"),
						long_tag("Node Weight 1"),
						long_tag("Node Weight 2"),
						long_tag("Node Weight 3"),
						long_tag("LOD Mipmap Magic Number"),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
					}),
					block_tag("Subparts",
					{
						short_tag("Indices Start Index"),
						short_tag("Indices Length"),
						short_tag("Visibility Bounds Index"),
						short_tag("Part Index"),
					}),
					block_tag("Visibility Bounds",
					{
						long_tag("Position X"),
						long_tag("Position Y"),
						long_tag("Position Z"),
						long_tag("Radius"),
						byte_tag("Node 0"),
						byte_tag("Unknown"),
						short_tag("Unknown"),
					}),
					block_tag("Raw Vertices",
					{
						undefined_tag("Position", 9999),
						long_tag("Old Node Index 1"),
						long_tag("Old Node Index 2"),
						long_tag("Old Node Index 3"),
						long_tag("Old Node Index 4"),
						long_tag("Old Node Weight 1"),
						long_tag("Old Node Weight 2"),
						long_tag("Old Node Weight 3"),
						long_tag("Old Node Weight 4"),
						long_tag("New Node Index 1"),
						long_tag("New Node Index 2"),
						long_tag("New Node Index 3"),
						long_tag("New Node Index 4"),
						long_tag("Use New Node Indices"),
						long_tag("Adjusted Compound Node Index"),
						undefined_tag("Texcoord", 9999),
						undefined_tag("Normal", 9999),
						undefined_tag("Binormal", 9999),
						undefined_tag("Tangent", 9999),
						undefined_tag("Anisotropic Binormal", 9999),
						undefined_tag("Secondary Texcoord", 9999),
						undefined_tag("Primary Lightmap Color", 9999),
						undefined_tag("Primary Lightmap Texcoord", 9999),
						undefined_tag("Primary Lightmap Incident Direction", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
					}),
					block_tag("Strip Indices",
					{
						short_tag("Index"),
					}),
					undefined_tag("Visibility MOPP Code", 9999),
					block_tag("MOPP Reorder Table",
					{
						short_tag("Index"),
					}),
					block_tag("Vertex Buffers",
					{
						undefined_tag("Vertex Buffer", 9999),
					}),
					undefined_tag("Unknown", 9999),
				}),
			}),
			block_tag("Lighting Environments",
			{
				long_tag("Sample Point X"),
				long_tag("Sample Point Y"),
				long_tag("Sample Point Z"),
				long_tag("Red Coefficient"),
				long_tag("Red Coefficient"),
				long_tag("Red Coefficient"),
				long_tag("Red Coefficient"),
				long_tag("Red Coefficient"),
				long_tag("Red Coefficient"),
				long_tag("Red Coefficient"),
				long_tag("Red Coefficient"),
				long_tag("Red Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Green Coefficient"),
				long_tag("Blue Coefficient"),
				long_tag("Blue Coefficient"),
				long_tag("Blue Coefficient"),
				long_tag("Blue Coefficient"),
				long_tag("Blue Coefficient"),
				long_tag("Blue Coefficient"),
				long_tag("Blue Coefficient"),
				long_tag("Blue Coefficient"),
				long_tag("Blue Coefficient"),
				undefined_tag("Mean Incoming Light Direction i", 9999),
				undefined_tag("Mean Incoming Light Direction j", 9999),
				undefined_tag("Mean Incoming Light Direction k", 9999),
				long_tag("Incoming Light Intensity X"),
				long_tag("Incoming Light Intensity Y"),
				long_tag("Incoming Light Intensity Z"),
				long_tag("Specular Bitmap Index"),
				undefined_tag("Rotation Axis i", 9999),
				undefined_tag("Rotation Axis j", 9999),
				undefined_tag("Rotation Axis k", 9999),
				long_tag("Rotation Speed"),
				undefined_tag("Bump Direction i", 9999),
				undefined_tag("Bump Direction j", 9999),
				undefined_tag("Bump Direction k", 9999),
				long_tag("Color Tint"),
				undefined_tag("Procedural Overide", 9999),
				undefined_tag("Flags", 9999),
				undefined_tag("Procedural Param0 i", 9999),
				undefined_tag("Procedural Param0 j", 9999),
				undefined_tag("Procedural Param0 k", 9999),
				undefined_tag("Procedural Param1.XYZ i", 9999),
				undefined_tag("Procedural Param1.XYZ j", 9999),
				undefined_tag("Procedural Param1.XYZ k", 9999),
				undefined_tag("Procedural Param1.w", 9999),
			}),
			block_tag("Geometry Buckets",
			{
				undefined_tag("Flags", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Resource Block Offset"),
				undefined_tag("Resource Block Size", 9999),
				undefined_tag("Section Data Size", 9999),
				undefined_tag("Resource Data Size", 9999),
				block_tag("Resources",
				{
					byte_tag("Type"),
					byte_tag("Unknown"),
					short_tag("Unknown"),
					short_tag("Primary Locator"),
					short_tag("Secondary Locator"),
					undefined_tag("Resource Data Size", 9999),
					undefined_tag("Resource Data Offset", 9999),
				}),
				tagref_tag("Owner Tag"),
				short_tag("Owner Tag Section Offset"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Instance Render Info",
			{
				short_tag("Bitmap Index"),
				short_tag("Palette Index"),
			}),
			block_tag("Instance Bucket Refs",
			{
				short_tag("Flags"),
				short_tag("Bucket Index"),
				block_tag("Section Offsets",
				{
					long_tag("Section Offset"),
				}),
			}),
			block_tag("Scenary Object Info",
			{
				long_tag("Unique ID"),
				short_tag("Origin BSP Index"),
				undefined_tag("Type", 9999),
				undefined_tag("Source", 9999),
				long_tag("Render Model Checksum"),
			}),
			block_tag("Scenary Object Bucket Refs",
			{
				short_tag("Flags"),
				short_tag("Bucket Index"),
				block_tag("Section Offsets",
				{
					long_tag("Section Offset"),
				}),
			}),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
	});
};
