#include "matg.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* matg_group = new tag_collection(
	"matg",
	{
		
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Language", 9999),
		block_tag("Havok Cleanup Resources",
		{
			undefined_tag("Object Cleanup Effect", 9999),
		}),
		block_tag("Collision Damage",
		{
			undefined_tag("Collision Damage", 9999),
			long_tag("Minimum Game Acceleration"),
			long_tag("Maximum Game Acceleration"),
			long_tag("Minimum Game Scale"),
			long_tag("Maximum Game Scale"),
			long_tag("Minimum Absolute Acceleration"),
			long_tag("Maximum Absolute Acceleration"),
			long_tag("Minimum Absolute Scale"),
			long_tag("Maximum Absolute Scale"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Sound Globals",
		{
			undefined_tag("Sound Classes", 9999),
			undefined_tag("Sound Effects", 9999),
			undefined_tag("Sound Mix", 9999),
			undefined_tag("Sound Combat Dialogue Constants", 9999),
			tagref_tag("Sound Gestalt"),
		}),
		block_tag("AI Globals",
		{
			long_tag("Danger Broadly Facing"),
			undefined_tag("Unknown", 9999),
			long_tag("Danger Shooting Near"),
			undefined_tag("Unknown", 9999),
			long_tag("Danger Shooting At"),
			undefined_tag("Unknown", 9999),
			long_tag("Danger Extremely Close"),
			undefined_tag("Unknown", 9999),
			long_tag("Danger Shield Damage"),
			long_tag("Danger Extended Shield Damage"),
			long_tag("Danger Body Damage"),
			long_tag("Danger Extended Body Damage"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Global Dialogue Tag", 9999),
			undefined_tag("Default Mission Dialogue Sound Effect", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Jump Down"),
			long_tag("Jump Step"),
			long_tag("Jump Crouch"),
			long_tag("Jump Stand"),
			long_tag("Jump Storey"),
			long_tag("Jump Tower"),
			long_tag("Maximum Jump Down Height Down"),
			long_tag("Maximum Jump Down Height Step"),
			long_tag("Maximum Jump Down Height Crouch"),
			long_tag("Maximum Jump Down Height Stand"),
			long_tag("Maximum Jump Down Height Storey"),
			long_tag("Maximum Jump Down Height Tower"),
			undefined_tag("Hoist Step", 9999),
			undefined_tag("Hoist Crouch", 9999),
			undefined_tag("Hoist Stand", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Vault Step", 9999),
			undefined_tag("Vault Crouch", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("Gravemind Properties",
			{
				long_tag("Minimum Retreat Time"),
				long_tag("Ideal Retreat Time"),
				long_tag("Maximum Retreat Time"),
			}),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Scary Target Threshold"),
			long_tag("Scary Weapon Threshold"),
			long_tag("Player Scariness"),
			long_tag("Berserking Actor Scariness"),
		}),
		block_tag("Damage Table",
		{
			block_tag("Damage Groups",
			{
				undefined_tag("Name", 9999),
				block_tag("Armor Modifiers",
				{
					undefined_tag("Name", 9999),
					long_tag("Damage Multiplier"),
				}),
			}),
		}),
		block_tag("Unknown",
		{
			block_tag("Sounds",
			{
				undefined_tag("Sound (Obsolete)", 9999),
			}),
			block_tag("Camera",
			{
				undefined_tag("Default Unit Camera Track", 9999),
				long_tag("Default Change Pause"),
				long_tag("First Person Change Pause"),
				long_tag("Following Camera Change Pause"),
			}),
			block_tag("Player Control",
			{
				long_tag("Magnetism Friction"),
				long_tag("Magnetism Adhesion"),
				long_tag("Inconsequential Target Scale"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Crosshair Location", 9999),
				long_tag("Seconds to Start"),
				long_tag("Seconds to Full Speed"),
				long_tag("Decay Rate"),
				long_tag("Full Speed Multiplier"),
				long_tag("Pegged Magnitude"),
				long_tag("Pegged Angular Threshold"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Look Default Pitch Rate"),
				long_tag("Look Default Yaw Rate"),
				long_tag("Look Peg Threshold"),
				long_tag("Look Yaw Acceleration Time"),
				long_tag("Look Yaw Acceleration Scale"),
				long_tag("Look Pitch Acceleration Time"),
				long_tag("Look Pitch Acceleration Scale"),
				long_tag("Look Autoleveling Scale"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Gravity Scale"),
				short_tag("Unknown"),
				short_tag("Minimum Autoleveling Ticks"),
				undefined_tag("Minimum Angle For Vehicle Flipping", 9999),
				block_tag("Look Function",
				{
					long_tag("Scale"),
				}),
				long_tag("Minimum Action Hold Time"),
			}),
			block_tag("Difficulty",
			{
				long_tag("Easy Enemy Damage"),
				long_tag("Normal Enemy Damage"),
				long_tag("Hard Enemy Damage"),
				long_tag("Impossible Enemy Damage"),
				long_tag("Easy Enemy Vitality"),
				long_tag("Normal Enemy Vitality"),
				long_tag("Hard Enemy Vitality"),
				long_tag("Impossible Enemy Vitality"),
				long_tag("Easy Enemy Shield"),
				long_tag("Normal Enemy Shield"),
				long_tag("Hard Enemy Shield"),
				long_tag("Impossible Enemy Shield"),
				long_tag("Easy Enemy Recharge"),
				long_tag("Normal Enemy Recharge"),
				long_tag("Hard Enemy Recharge"),
				long_tag("Impossible Enemy Recharge"),
				long_tag("Easy Friend Damage"),
				long_tag("Normal Friend Damage"),
				long_tag("Hard Friend Damage"),
				long_tag("Impossible Friend Damage"),
				long_tag("Easy Friend Vitality"),
				long_tag("Normal Friend Vitality"),
				long_tag("Hard Friend Vitality"),
				long_tag("Impossible Friend Vitality"),
				long_tag("Easy Friend Shield"),
				long_tag("Normal Friend Shield"),
				long_tag("Hard Friend Shield"),
				long_tag("Impossible Friend Shield"),
				long_tag("Easy Friend Recharge"),
				long_tag("Normal Friend Recharge"),
				long_tag("Hard Friend Recharge"),
				long_tag("Impossible Friend Recharge"),
				long_tag("Easy Infection Forms"),
				long_tag("Normal Infection Forms"),
				long_tag("Hard Infection Forms"),
				long_tag("Impossible Infection Forms"),
				long_tag("Easy Unknown"),
				long_tag("Normal Unknown"),
				long_tag("Hard Unknown"),
				long_tag("Impossible Unknown"),
				long_tag("Easy Rate of Fire"),
				long_tag("Normal Rate of Fire"),
				long_tag("Hard Rate of Fire"),
				long_tag("Impossible Rate of Fire"),
				long_tag("Easy Projectile Error"),
				long_tag("Normal Projectile Error"),
				long_tag("Hard Projectile Error"),
				long_tag("Impossible Projectile Error"),
				long_tag("Easy Burst Error"),
				long_tag("Normal Burst Error"),
				long_tag("Hard Burst Error"),
				long_tag("Impossible Burst Error"),
				long_tag("Easy New Target Delay"),
				long_tag("Normal New Target Delay"),
				long_tag("Hard New Target Delay"),
				long_tag("Impossible New Target Delay"),
				long_tag("Easy Burst Separation"),
				long_tag("Normal Burst Separation"),
				long_tag("Hard Burst Separation"),
				long_tag("Impossible Burst Separation"),
				long_tag("Easy Target Tracking"),
				long_tag("Normal Target Tracking"),
				long_tag("Hard Target Tracking"),
				long_tag("Impossible Target Tracking"),
				long_tag("Easy Target Leading"),
				long_tag("Normal Target Leading"),
				long_tag("Hard Target Leading"),
				long_tag("Impossible Target Leading"),
				long_tag("Easy Overcharge Chance"),
				long_tag("Normal Overcharge Chance"),
				long_tag("Hard Overcharge Chance"),
				long_tag("Impossible Overcharge Chance"),
				long_tag("Easy Special Fire Delay"),
				long_tag("Normal Special Fire Delay"),
				long_tag("Hard Special Fire Delay"),
				long_tag("Impossible Special Fire Delay"),
				long_tag("Easy Guidance vs Player"),
				long_tag("Normal Guidance vs Player"),
				long_tag("Hard Guidance vs Player"),
				long_tag("Impossible Guidance vs Player"),
				long_tag("Easy Melee Delay Base"),
				long_tag("Normal Melee Delay Base"),
				long_tag("Hard Melee Delay Base"),
				long_tag("Impossible Melee Delay Base"),
				long_tag("Easy Melee Delay Scale"),
				long_tag("Normal Melee Delay Scale"),
				long_tag("Hard Melee Delay Scale"),
				long_tag("Impossible Melee Delay Scale"),
				long_tag("Easy Unknown"),
				long_tag("Normal Unknown"),
				long_tag("Hard Unknown"),
				long_tag("Impossible Unknown"),
				long_tag("Easy Grenade Chance Scale"),
				long_tag("Normal Grenade Chance Scale"),
				long_tag("Hard Grenade Chance Scale"),
				long_tag("Impossible Grenade Chance Scale"),
				long_tag("Easy Grenade Timer Scale"),
				long_tag("Normal Grenade Timer Scale"),
				long_tag("Hard Grenade Timer Scale"),
				long_tag("Impossible Grenade Timer Scale"),
				long_tag("Easy Unknown"),
				long_tag("Normal Unknown"),
				long_tag("Hard Unknown"),
				long_tag("Impossible Unknown"),
				long_tag("Easy Unknown"),
				long_tag("Normal Unknown"),
				long_tag("Hard Unknown"),
				long_tag("Impossible Unknown"),
				long_tag("Easy Unknown"),
				long_tag("Normal Unknown"),
				long_tag("Hard Unknown"),
				long_tag("Impossible Unknown"),
				long_tag("Easy Major Upgrade (Normal)"),
				long_tag("Normal Major Upgrade (Normal)"),
				long_tag("Hard Major Upgrade (Normal)"),
				long_tag("Impossible Major Upgrade (Normal)"),
				long_tag("Easy Major Upgrade (Few)"),
				long_tag("Normal Major Upgrade (Few)"),
				long_tag("Hard Major Upgrade (Few)"),
				long_tag("Impossible Major Upgrade (Few)"),
				long_tag("Easy Major Upgrade (Many)"),
				long_tag("Normal Major Upgrade (Many)"),
				long_tag("Hard Major Upgrade (Many)"),
				long_tag("Impossible Major Upgrade (Many)"),
				long_tag("Easy Player Vehicle Ram Chance"),
				long_tag("Normal Player Vehicle Ram Chance"),
				long_tag("Hard Player Vehicle Ram Chance"),
				long_tag("Impossible Player Vehicle Ram Chance"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Grenades",
			{
				short_tag("Maximum Count"),
				short_tag("Unknown"),
				undefined_tag("Throwing Effect", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Equipment", 9999),
				undefined_tag("Projectile", 9999),
			}),
			block_tag("Rasterizer Data",
			{
				undefined_tag("Distance Attenuation", 9999),
				undefined_tag("Vector Normalization", 9999),
				undefined_tag("Gradients", 9999),
				undefined_tag("Unused", 9999),
				undefined_tag("Unused", 9999),
				undefined_tag("Unused", 9999),
				undefined_tag("Glow", 9999),
				undefined_tag("Unused", 9999),
				undefined_tag("Unused", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Global Vertex Shaders",
				{
					undefined_tag("Vertex Shader", 9999),
				}),
				undefined_tag("Default 2D", 9999),
				undefined_tag("Default 3D", 9999),
				undefined_tag("Default Cube Map", 9999),
				undefined_tag("UNUSED", 9999),
				undefined_tag("UNUSED", 9999),
				undefined_tag("UNUSED", 9999),
				undefined_tag("UNUSED", 9999),
				undefined_tag("UNUSED", 9999),
				undefined_tag("UNUSED", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Global Shader", 9999),
				short_tag("Flags"),
				short_tag("Unknown"),
				long_tag("Refraction Amount"),
				long_tag("Distance Falloff"),
				undefined_tag("Tint Color", 9999),
				long_tag("Hyper-Stealth Refraction"),
				long_tag("Hyper-Stealth Distance Falloff"),
				undefined_tag("Hyper-Stealth Tint Color", 9999),
				undefined_tag("Unused", 9999),
			}),
			block_tag("Interface Tags",
			{
				undefined_tag("Spinner", 9999),
				undefined_tag("Obsolete", 9999),
				undefined_tag("Screen Color Table", 9999),
				undefined_tag("HUD Color Table", 9999),
				undefined_tag("Editor Color Table", 9999),
				undefined_tag("Dialog Color Table", 9999),
				undefined_tag("HUD Globals", 9999),
				undefined_tag("Motion Sensor Sweep Bitmap", 9999),
				undefined_tag("Motion Sensor Sweep Bitmap Mask", 9999),
				undefined_tag("Multiplayer HUD Bitmap", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("HUD Digits Definition", 9999),
				undefined_tag("Motion Sensor Blip Bitmap", 9999),
				undefined_tag("Interface Goo Map 1", 9999),
				undefined_tag("Interface Goo Map 2", 9999),
				undefined_tag("Interface Goo Map 3", 9999),
				undefined_tag("Main Menu UI Globals", 9999),
				undefined_tag("Single Player UI Globals", 9999),
				undefined_tag("Multiplayer UI Globals", 9999),
			}),
			block_tag("Weapon List",
			{
				undefined_tag("Weapon", 9999),
			}),
			block_tag("Cheat Powerups",
			{
				undefined_tag("Powerup", 9999),
			}),
			block_tag("Multiplayer Information",
				{
					undefined_tag("Flag", 9999),
					undefined_tag("Unit", 9999),
					block_tag("Vehicles",
					{
						undefined_tag("Vehicle", 9999),
					}),
					undefined_tag("Hill Shader", 9999),
					undefined_tag("Flag Shader", 9999),
					undefined_tag("Ball", 9999),
					block_tag("Sounds",
					{
						undefined_tag("Sound", 9999),
					}),
					undefined_tag("In Game Text", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					block_tag("General Events",
					{
						short_tag("Flags"),
						short_tag("Unknown"),
						short_tag("Event"),
						short_tag("Audience"),
						short_tag("Unknown"),
						short_tag("Unknown"),
						undefined_tag("Display String", 9999),
						short_tag("Required Field"),
						short_tag("Excluded Audience"),
						undefined_tag("Primary String", 9999),
						long_tag("Primary String Duration"),
						undefined_tag("Plural Display String", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						long_tag("Sound Delay (Announcer Only)"),
						short_tag("Sound Flags"),
						short_tag("Unknown"),
						undefined_tag("Sound", 9999),
						undefined_tag("Japanese Sound", 9999),
						undefined_tag("German Sound", 9999),
						undefined_tag("French Sound", 9999),
						undefined_tag("Spanish Sound", 9999),
						undefined_tag("Italian Sound", 9999),
						undefined_tag("Korean Sound", 9999),
						undefined_tag("Chinese Sound", 9999),
						undefined_tag("Portuguese Sound", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						block_tag("Sound Permutations",
						{
							short_tag("Sound Flags"),
							short_tag("Unknown"),
							undefined_tag("English Sound", 9999),
							undefined_tag("Japanese Sound", 9999),
							undefined_tag("German Sound", 9999),
							undefined_tag("French Sound", 9999),
							undefined_tag("Spanish Sound", 9999),
							undefined_tag("Italian Sound", 9999),
							undefined_tag("Korean Sound", 9999),
							undefined_tag("Chinese Sound", 9999),
							undefined_tag("Portuguese Sound", 9999),
							long_tag("Probability"),
						}),
					}),
					block_tag("Slayer Events",
					{
						short_tag("Flags"),
						short_tag("Unknown"),
						short_tag("Event"),
						short_tag("Audience"),
						short_tag("Unknown"),
						short_tag("Unknown"),
						undefined_tag("Display String", 9999),
						short_tag("Required Field"),
						short_tag("Excluded Audience"),
						undefined_tag("Primary String", 9999),
						long_tag("Primary String Duration"),
						undefined_tag("Plural Display String", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						long_tag("Sound Delay (Announcer Only)"),
						short_tag("Sound Flags"),
						short_tag("Unknown"),
						undefined_tag("Sound", 9999),
						undefined_tag("Japanese Sound", 9999),
						undefined_tag("German Sound", 9999),
						undefined_tag("French Sound", 9999),
						undefined_tag("Spanish Sound", 9999),
						undefined_tag("Italian Sound", 9999),
						undefined_tag("Korean Sound", 9999),
						undefined_tag("Chinese Sound", 9999),
						undefined_tag("Portuguese Sound", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						block_tag("Sound Permutations",
						{
							short_tag("Sound Flags"),
							short_tag("Unknown"),
							undefined_tag("English Sound", 9999),
							undefined_tag("Japanese Sound", 9999),
							undefined_tag("German Sound", 9999),
							undefined_tag("French Sound", 9999),
							undefined_tag("Spanish Sound", 9999),
							undefined_tag("Italian Sound", 9999),
							undefined_tag("Korean Sound", 9999),
							undefined_tag("Chinese Sound", 9999),
							undefined_tag("Portuguese Sound", 9999),
							long_tag("Probability"),
						}),
					}),
					block_tag("CTF Events",
					{
						short_tag("Flags"),
						short_tag("Unknown"),
						short_tag("Event"),
						short_tag("Audience"),
						short_tag("Unknown"),
						short_tag("Unknown"),
						undefined_tag("Display String", 9999),
						short_tag("Required Field"),
						short_tag("Excluded Audience"),
						undefined_tag("Primary String", 9999),
						long_tag("Primary String Duration"),
						undefined_tag("Plural Display String", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						long_tag("Sound Delay (Announcer Only)"),
						short_tag("Sound Flags"),
						short_tag("Unknown"),
						undefined_tag("Sound", 9999),
						undefined_tag("Japanese Sound", 9999),
						undefined_tag("German Sound", 9999),
						undefined_tag("French Sound", 9999),
						undefined_tag("Spanish Sound", 9999),
						undefined_tag("Italian Sound", 9999),
						undefined_tag("Korean Sound", 9999),
						undefined_tag("Chinese Sound", 9999),
						undefined_tag("Portuguese Sound", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						block_tag("Sound Permutations",
						{
							short_tag("Sound Flags"),
							short_tag("Unknown"),
							undefined_tag("English Sound", 9999),
							undefined_tag("Japanese Sound", 9999),
							undefined_tag("German Sound", 9999),
							undefined_tag("French Sound", 9999),
							undefined_tag("Spanish Sound", 9999),
							undefined_tag("Italian Sound", 9999),
							undefined_tag("Korean Sound", 9999),
							undefined_tag("Chinese Sound", 9999),
							undefined_tag("Portuguese Sound", 9999),
							long_tag("Probability"),
						}),
					}),
					block_tag("Oddball Events",
					{
						short_tag("Flags"),
						short_tag("Unknown"),
						short_tag("Event"),
						short_tag("Audience"),
						short_tag("Unknown"),
						short_tag("Unknown"),
						undefined_tag("Display String", 9999),
						short_tag("Required Field"),
						short_tag("Excluded Audience"),
						undefined_tag("Primary String", 9999),
						long_tag("Primary String Duration"),
						undefined_tag("Plural Display String", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						long_tag("Sound Delay (Announcer Only)"),
						short_tag("Sound Flags"),
						short_tag("Unknown"),
						undefined_tag("Sound", 9999),
						undefined_tag("Japanese Sound", 9999),
						undefined_tag("German Sound", 9999),
						undefined_tag("French Sound", 9999),
						undefined_tag("Spanish Sound", 9999),
						undefined_tag("Italian Sound", 9999),
						undefined_tag("Korean Sound", 9999),
						undefined_tag("Chinese Sound", 9999),
						undefined_tag("Portuguese Sound", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						block_tag("Sound Permutations",
						{
							short_tag("Sound Flags"),
							short_tag("Unknown"),
							undefined_tag("English Sound", 9999),
							undefined_tag("Japanese Sound", 9999),
							undefined_tag("German Sound", 9999),
							undefined_tag("French Sound", 9999),
							undefined_tag("Spanish Sound", 9999),
							undefined_tag("Italian Sound", 9999),
							undefined_tag("Korean Sound", 9999),
							undefined_tag("Chinese Sound", 9999),
							undefined_tag("Portuguese Sound", 9999),
							long_tag("Probability"),
						}),
					}),
					block_tag("Unknown",
					{
						block_tag("King Events",
						{
							short_tag("Flags"),
							short_tag("Unknown"),
							short_tag("Event"),
							short_tag("Audience"),
							short_tag("Unknown"),
							short_tag("Unknown"),
							undefined_tag("Display String", 9999),
							short_tag("Required Field"),
							short_tag("Excluded Audience"),
							undefined_tag("Primary String", 9999),
							long_tag("Primary String Duration"),
							undefined_tag("Plural Display String", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							long_tag("Sound Delay (Announcer Only)"),
							short_tag("Sound Flags"),
							short_tag("Unknown"),
							undefined_tag("Sound", 9999),
							undefined_tag("Japanese Sound", 9999),
							undefined_tag("German Sound", 9999),
							undefined_tag("French Sound", 9999),
							undefined_tag("Spanish Sound", 9999),
							undefined_tag("Italian Sound", 9999),
							undefined_tag("Korean Sound", 9999),
							undefined_tag("Chinese Sound", 9999),
							undefined_tag("Portuguese Sound", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							undefined_tag("Unknown", 9999),
							block_tag("Sound Permutations",
							{
								short_tag("Sound Flags"),
								short_tag("Unknown"),
								undefined_tag("English Sound", 9999),
								undefined_tag("Japanese Sound", 9999),
								undefined_tag("German Sound", 9999),
								undefined_tag("French Sound", 9999),
								undefined_tag("Spanish Sound", 9999),
								undefined_tag("Italian Sound", 9999),
								undefined_tag("Korean Sound", 9999),
								undefined_tag("Chinese Sound", 9999),
								undefined_tag("Portuguese Sound", 9999),
								long_tag("Probability"),
							}),
						}),
					}),
					block_tag("Player Information",
					{
						undefined_tag("Unused", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						long_tag("Walking Speed"),
						undefined_tag("Unknown", 9999),
						long_tag("Run Forward"),
						long_tag("Run Backward"),
						long_tag("Run Sideways"),
						long_tag("Run Acceleration"),
						long_tag("Sneak Forward"),
						long_tag("Sneak Backward"),
						long_tag("Sneak Sideways"),
						long_tag("Sneak Acceleration"),
						long_tag("Airborne Acceleration"),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Grenade Origin", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						long_tag("Stun Movement Penalty"),
						long_tag("Stun Turning Penalty"),
						long_tag("Stun Jumping Penalty"),
						long_tag("Minimum Stun Time"),
						long_tag("Maximum Stun Time"),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("First Person Idle Time", 9999),
						long_tag("First Person Skip Fraction"),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Coop Respawn Effect", 9999),
						long_tag("Binoculars Zoom Count"),
						undefined_tag("Binoculars Zoom Range", 9999),
						undefined_tag("Binoculars Zoom In Sound", 9999),
						undefined_tag("Binoculars Zoom Out Sound", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Active Camouflage On", 9999),
						undefined_tag("Active Camouflage Off", 9999),
						undefined_tag("Active Camouflage Error", 9999),
						undefined_tag("Active Camouflage Ready", 9999),
						undefined_tag("Flashlight On", 9999),
						undefined_tag("Flashlight Off", 9999),
						undefined_tag("Ice Cream", 9999),
					}),
					block_tag("Player Representation",
					{
						undefined_tag("First Person Hands Model", 9999),
						undefined_tag("First Person Body Model", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Third Person Unit", 9999),
						undefined_tag("Third Person Variant", 9999),
					}),
					block_tag("Falling Damage",
					{
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Harmful Falling Distance", 9999),
						undefined_tag("Falling Damage", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						long_tag("Maximum Falling Distance"),
						undefined_tag("Distance Damage", 9999),
						undefined_tag("Vehicle Environment Collision Damage Effect", 9999),
						undefined_tag("Vehicle Killed Unit Damage Effect", 9999),
						undefined_tag("Vehicle Collision Damage", 9999),
						undefined_tag("Flaming Death Damage", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Unknown", 9999),
						long_tag("Unknown"),
						long_tag("Unknown"),
						long_tag("Unknown"),
					}),
					block_tag("Old Materials",
					{
						undefined_tag("New Material Name", 9999),
						undefined_tag("New General Material Name", 9999),
						long_tag("Ground Friction Scale"),
						long_tag("Ground Friction Normal k1 Scale"),
						long_tag("Ground Friction Normal k0 Scale"),
						long_tag("Ground Depth Scale"),
						long_tag("Ground Damp Fraction Scale"),
						undefined_tag("Melee Hit Sound", 9999),
					}),
					block_tag("Materials",
					{
						undefined_tag("Name", 9999),
						undefined_tag("Parent Name", 9999),
						short_tag("Unknown"),
						short_tag("Flags"),
						short_tag("Old Material Type"),
						short_tag("Unknown"),
						undefined_tag("General Armor", 9999),
						undefined_tag("Specific Armor", 9999),
						undefined_tag("Flags", 9999),
						long_tag("Friction"),
						long_tag("Restitution"),
						long_tag("Density"),
						undefined_tag("Old Material Physics", 9999),
						undefined_tag("Breakable Surface", 9999),
						undefined_tag("Sound Sweetener Small", 9999),
						undefined_tag("Sound Sweetener Medium", 9999),
						undefined_tag("Sound Sweetener Large", 9999),
						undefined_tag("Sound Sweetener Rolling", 9999),
						undefined_tag("Sound Sweetener Grinding", 9999),
						undefined_tag("Sound Sweetener Melee", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Effect Sweetener Small", 9999),
						undefined_tag("Effect Sweetener Medium", 9999),
						undefined_tag("Effect Sweetener Large", 9999),
						undefined_tag("Effect Sweetener Rolling", 9999),
						undefined_tag("Effect Sweetener Grinding", 9999),
						undefined_tag("Effect Sweetener Melee", 9999),
						undefined_tag("Unknown", 9999),
						undefined_tag("Sweetener Inheritance Flags", 9999),
						undefined_tag("Material Effects", 9999),
					}),
					block_tag("Multiplayer UI",
					{
						undefined_tag("Random Player Names", 9999),
						block_tag("Obsolete Profile Colors",
						{
							undefined_tag("Color", 9999),
						}),
						block_tag("Team Colors",
						{
							undefined_tag("Color", 9999),
						}),
						undefined_tag("Team Names", 9999),
					}),
					block_tag("Profile Colors",
					{
						undefined_tag("Color", 9999),
					}),
					undefined_tag("Multiplayer Globals", 9999),
					block_tag("Runtime Level Data",
					{
						block_tag("Campaign Levels",
						{
							long_tag("Campaign ID"),
							long_tag("Map ID"),
							string_tag("Path"),
						}),
					}),
					block_tag("UI Level Data",
					{
						block_tag("Campaigns",
						{
							long_tag("Campaign ID"),
							undefined_tag("English Name", 9999),
							undefined_tag("Japanese Name", 9999),
							undefined_tag("German Name", 9999),
							undefined_tag("French Name", 9999),
							undefined_tag("Spanish Name", 9999),
							undefined_tag("Italian Name", 9999),
							undefined_tag("Korean Name", 9999),
							undefined_tag("Chinese Name", 9999),
							undefined_tag("Portuguese Name", 9999),
							undefined_tag("English Description", 9999),
							undefined_tag("Japanese Description", 9999),
							undefined_tag("German Description", 9999),
							undefined_tag("French Description", 9999),
							undefined_tag("Spanish Description", 9999),
							undefined_tag("Italian Description", 9999),
							undefined_tag("Korean Description", 9999),
							undefined_tag("Chinese Description", 9999),
							undefined_tag("Portuguese Description", 9999),
						}),
						block_tag("Campaign Levels",
						{
							long_tag("Campaign ID"),
							long_tag("Map ID"),
							undefined_tag("Bitmap", 9999),
							undefined_tag("English Name", 9999),
							undefined_tag("Japanese Name", 9999),
							undefined_tag("German Name", 9999),
							undefined_tag("French Name", 9999),
							undefined_tag("Spanish Name", 9999),
							undefined_tag("Italian Name", 9999),
							undefined_tag("Korean Name", 9999),
							undefined_tag("Chinese Name", 9999),
							undefined_tag("Portuguese Name", 9999),
							undefined_tag("English Description", 9999),
							undefined_tag("Japanese Description", 9999),
							undefined_tag("German Description", 9999),
							undefined_tag("French Description", 9999),
							undefined_tag("Spanish Description", 9999),
							undefined_tag("Italian Description", 9999),
							undefined_tag("Korean Description", 9999),
							undefined_tag("Chinese Description", 9999),
							undefined_tag("Portuguese Description", 9999),
						}),
						block_tag("Multiplayer Levels",
						{
							long_tag("Map ID"),
							undefined_tag("Bitmap", 9999),
							undefined_tag("English Name", 9999),
							undefined_tag("Japanese Name", 9999),
							undefined_tag("German Name", 9999),
							undefined_tag("French Name", 9999),
							undefined_tag("Spanish Name", 9999),
							undefined_tag("Italian Name", 9999),
							undefined_tag("Korean Name", 9999),
							undefined_tag("Chinese Name", 9999),
							undefined_tag("Portuguese Name", 9999),
							undefined_tag("English Description", 9999),
							undefined_tag("Japanese Description", 9999),
							undefined_tag("German Description", 9999),
							undefined_tag("French Description", 9999),
							undefined_tag("Spanish Description", 9999),
							undefined_tag("Italian Description", 9999),
							undefined_tag("Korean Description", 9999),
							undefined_tag("Chinese Description", 9999),
							undefined_tag("Portuguese Description", 9999),
							string_tag("Path"),
							long_tag("Sort Order"),
							undefined_tag("Flags", 9999),
							byte_tag("Unknown"),
							short_tag("Unknown"),
							byte_tag("Max Teams None"),
							byte_tag("Max Teams CTF"),
							byte_tag("Max Teams Slayer"),
							byte_tag("Max Teams Oddball"),
							byte_tag("Max Teams KOTH"),
							byte_tag("Max Teams Race"),
							byte_tag("Max Teams Headhunter"),
							byte_tag("Max Teams Juggernaut"),
							byte_tag("Max Teams Territories"),
							byte_tag("Max Teams Assault"),
							byte_tag("Max Teams Stub 10"),
							byte_tag("Max Teams Stub 11"),
							byte_tag("Max Teams Stub 12"),
							byte_tag("Max Teams Stub 13"),
							byte_tag("Max Teams Stub 14"),
							byte_tag("Max Teams Stub 15"),
						}),
					}),
					undefined_tag("Default Global Lighting", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
					undefined_tag("String Reference Pointer", 9999),
					undefined_tag("String Data Pointer", 9999),
					undefined_tag("Number of Strings", 9999),
					undefined_tag("String Data Size", 9999),
					undefined_tag("String Reference Cache Offset", 9999),
					undefined_tag("String Data Cache Offset", 9999),
					undefined_tag("Data Loaded Boolean", 9999),
				}),
		}),
	});
};
