#include "mode.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* mode_group = new tag_collection(
	"mode",
	{
		
		undefined_tag("Name", 9999),
		short_tag("Flags"),
		short_tag("Unknown"),
		long_tag("Model Checksum"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Compression Info",
		{
			long_tag("Position Bounds X min"),
			long_tag("Position Bounds X max"),
			long_tag("Position Bounds Y min"),
			long_tag("Position Bounds Y max"),
			long_tag("Position Bounds Z min"),
			long_tag("Position Bounds Z max"),
			long_tag("Texcoord Bounds X min"),
			long_tag("Texcoord Bounds X max"),
			long_tag("Texcoord Bounds Y min"),
			long_tag("Texcoord Bounds Y max"),
			long_tag("Secondary Texcoord Bounds X min"),
			long_tag("Secondary Texcoord Bounds X max"),
			long_tag("Secondary Texcoord Bounds Y min"),
			long_tag("Secondary Texcoord Bounds Y max"),
		}),
		block_tag("Regions",
		{
			undefined_tag("Name", 9999),
			short_tag("Old Node Map Offset"),
			short_tag("Old Node Map Size"),
			block_tag("Permutations",
			{
				undefined_tag("Name", 9999),
				short_tag("L1 Section Index (Super Low)"),
				short_tag("L2 Section Index (Low)"),
				short_tag("L3 Section Index (Medium)"),
				short_tag("L4 Section Index (High)"),
				short_tag("L5 Section Index (Super High)"),
				short_tag("L6 Section Index (Hollywood)"),
			}),
		}),
		block_tag("Sections",
		{
			short_tag("Global Geometry Classification"),
			short_tag("Unknown"),
			undefined_tag("Total Vertex Count", 9999),
			undefined_tag("Total Triangle Count", 9999),
			undefined_tag("Total Part Count", 9999),
			undefined_tag("Shadow-Casting Triangle Count", 9999),
			undefined_tag("Shadow-Casting Part Count", 9999),
			undefined_tag("Opaque Point Count", 9999),
			undefined_tag("Opaque Vertex Count", 9999),
			undefined_tag("Opaque Part Count", 9999),
			undefined_tag("Opaque Max Nodes/Vertex", 9999),
			undefined_tag("Shadow-Casting Rigid Triangle Count", 9999),
			short_tag("Geometry Classification"),
			short_tag("Geometry Compression Flags"),
			block_tag("Compression Info",
			{
				long_tag("Position Bounds X min"),
				long_tag("Position Bounds X max"),
				long_tag("Position Bounds Y min"),
				long_tag("Position Bounds Y max"),
				long_tag("Position Bounds Z min"),
				long_tag("Position Bounds Z max"),
				long_tag("Texcoord Bounds X min"),
				long_tag("Texcoord Bounds X max"),
				long_tag("Texcoord Bounds Y min"),
				long_tag("Texcoord Bounds Y max"),
				long_tag("Secondary Texcoord Bounds X min"),
				long_tag("Secondary Texcoord Bounds X max"),
				long_tag("Secondary Texcoord Bounds Y min"),
				long_tag("Secondary Texcoord Bounds Y max"),
			}),
			undefined_tag("Hardware Node Count", 9999),
			undefined_tag("Node Map Size", 9999),
			undefined_tag("Software Plane Sount", 9999),
			undefined_tag("Total Subpart Count", 9999),
			short_tag("Section Lighting Flags"),
			short_tag("Rigid Node"),
			short_tag("Flags"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Resource Block Offset"),
			undefined_tag("Resource Block Size", 9999),
			undefined_tag("Section Data Size", 9999),
			undefined_tag("Resource Data Size", 9999),
			block_tag("Resources",
			{
				byte_tag("Type"),
				byte_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Primary Locator"),
				short_tag("Secondary Locator"),
				undefined_tag("Resource Data Size", 9999),
				undefined_tag("Resource Data Offset", 9999),
			}),
			tagref_tag("Owner Tag"),
			short_tag("Owner Tag Section Offset"),
			short_tag("Unknown"),
			long_tag("Unknown"),
		}),
		block_tag("Invalid Section Pair Bits",
		{
			long_tag("Bits"),
		}),
		block_tag("Section Groups",
		{
			short_tag("Detail Levels"),
			short_tag("Unknown"),
			block_tag("Compound Nodes",
			{
				byte_tag("Node Index"),
				byte_tag("Node Index"),
				byte_tag("Node Index"),
				byte_tag("Node Index"),
				long_tag("Node Weight"),
				long_tag("Node Weight"),
				long_tag("Node Weight"),
			}),
		}),
		byte_tag("L1 Section Index (Super Low)"),
		byte_tag("L2 Section Index (Low)"),
		byte_tag("L3 Section Index (Medium)"),
		byte_tag("L4 Section Index (High)"),
		byte_tag("L5 Section Index (Super High)"),
		byte_tag("L6 Section Index (Hollywood)"),
		short_tag("Unknown"),
		long_tag("Node List Checksum"),
		block_tag("Nodes",
		{
			undefined_tag("Name", 9999),
			short_tag("Parent Node"),
			short_tag("First Child Node"),
			short_tag("Next Sibling Node"),
			short_tag("Import Node Index"),
			long_tag("Default Translation x"),
			long_tag("Default Translation y"),
			long_tag("Default Translation z"),
			long_tag("Default Rotation i"),
			long_tag("Default Rotation j"),
			long_tag("Default Rotation k"),
			long_tag("Default Rotation w"),
			long_tag("Default Scale"),
			long_tag("Inverse Forward i"),
			long_tag("Inverse Forward j"),
			long_tag("Inverse Forward k"),
			long_tag("Inverse Left i"),
			long_tag("Inverse Left j"),
			long_tag("Inverse Left k"),
			long_tag("Inverse Up i"),
			long_tag("Inverse Up j"),
			long_tag("Inverse Up k"),
			long_tag("Inverse Position x"),
			long_tag("Inverse Position y"),
			long_tag("Inverse Position z"),
			long_tag("Distance from Parent"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Marker Groups",
		{
			undefined_tag("Name", 9999),
			block_tag("Markers",
			{
				byte_tag("Region Index"),
				byte_tag("Permutation Index"),
				byte_tag("Node Index"),
				byte_tag("Unknown"),
				long_tag("Translation x"),
				long_tag("Translation y"),
				long_tag("Translation z"),
				long_tag("Rotation i"),
				long_tag("Rotation j"),
				long_tag("Rotation k"),
				long_tag("Rotation w"),
				long_tag("Scale"),
			}),
		}),
		block_tag("Materials",
		{
			undefined_tag("Old Shader", 9999),
			undefined_tag("Shader", 9999),
			block_tag("Properties",
			{
				short_tag("Type"),
				short_tag("Int Value"),
				long_tag("Real Value"),
			}),
			undefined_tag("Unknown", 9999),
			byte_tag("Breakable Surface Index"),
			byte_tag("Unknown"),
			byte_tag("Unknown"),
			byte_tag("Unknown"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Don't Draw Over Camera Cosine Angle"),
		block_tag("PRT Info",
		{
			undefined_tag("SH Order", 9999),
			undefined_tag("Number Of Clusters", 9999),
			undefined_tag("PCA Vectors Per Cluster", 9999),
			undefined_tag("Number Of Rays", 9999),
			undefined_tag("Number Of Bounces", 9999),
			undefined_tag("Material Index For SBSFC Scattering", 9999),
			long_tag("Length Scale"),
			undefined_tag("Number Of LODs In Model", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("LOD Info",
			{
				undefined_tag("Cluster Offset", 9999),
				block_tag("Section Info",
				{
					long_tag("Section Index"),
					undefined_tag("PCA Data Offset", 9999),
				}),
			}),
			block_tag("Cluster Basis",
			{
				long_tag("Basis Data"),
			}),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Resource Block Offset"),
			undefined_tag("Resource Block Size", 9999),
			undefined_tag("Section Data Size", 9999),
			undefined_tag("Resource Data Size", 9999),
			block_tag("Resources",
			{
				byte_tag("Type"),
				byte_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Primary Locator"),
				short_tag("Secondary Locator"),
				undefined_tag("Resource Data Size", 9999),
				undefined_tag("Resource Data Offset", 9999),
			}),
			tagref_tag("Owner Tag"),
			short_tag("Owner Tag Section Offset"),
			short_tag("Unknown"),
			long_tag("Unknown"),
		}),
		block_tag("Section Render Leaves",
		{
			block_tag("Node Render Leaves",
			{
				block_tag("Collision Leaves",
				{
					short_tag("Cluster"),
					short_tag("Surface Reference Count"),
					long_tag("First Surface Reference Index"),
				}),
				block_tag("Surface References",
				{
					short_tag("Strip Index"),
					short_tag("Lightmap Triangle Index"),
					long_tag("BSP Node Index"),
				}),
			}),
		}),
	});
};
