#include "mulg.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* mulg_group = new tag_collection(
	"mulg",
	{
		
		block_tag("Universal",
		{
			undefined_tag("Random Player Names", 9999),
			undefined_tag("Team Names", 9999),
			block_tag("Team Colors",
			{
				undefined_tag("Color", 9999),
			}),
			undefined_tag("Multiplayer Text", 9999),
		}),
		block_tag("Runtime",
		{
			undefined_tag("Flag", 9999),
			undefined_tag("Ball", 9999),
			undefined_tag("Unit", 9999),
			undefined_tag("Flag Shader", 9999),
			undefined_tag("Hill Shader", 9999),
			undefined_tag("Head", 9999),
			undefined_tag("Juggernaut Powerup", 9999),
			undefined_tag("Bomb", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("Weapons",
			{
				undefined_tag("Weapon", 9999),
			}),
			block_tag("Vehicles",
			{
				undefined_tag("Vehicle", 9999),
			}),
			block_tag("Grenades",
			{
				undefined_tag("Weapon", 9999),
			}),
			block_tag("Powerups",
			{
				undefined_tag("Weapon", 9999),
			}),
			undefined_tag("In Game Text", 9999),
			block_tag("Sounds",
			{
				undefined_tag("Sound", 9999),
			}),
			block_tag("General Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			block_tag("Flavor Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			block_tag("Slayer Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			block_tag("CTF Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			block_tag("Oddball Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			block_tag("King Of The Hill Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			block_tag("Juggernaut Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			block_tag("Territories Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			block_tag("Assualt Events",
			{
				short_tag("Flags"),
				short_tag("Type"),
				short_tag("Event"),
				short_tag("Audience"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Display String", 9999),
				short_tag("Required Field"),
				short_tag("Excluded Audience"),
				undefined_tag("Primary String", 9999),
				long_tag("Primary String Duration"),
				undefined_tag("Pural Display String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Sound Delay (Announcer Only)"),
				short_tag("Sound Flags"),
				short_tag("Unknown"),
				undefined_tag("Sound", 9999),
				undefined_tag("Japanese Sound", 9999),
				undefined_tag("German Sound", 9999),
				undefined_tag("French Sound", 9999),
				undefined_tag("Spanish Sound", 9999),
				undefined_tag("Italian Sound", 9999),
				undefined_tag("Korean Sound", 9999),
				undefined_tag("Chinese Sound", 9999),
				undefined_tag("Portuguese Sound", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Sound Permutations",
				{
					short_tag("Sound Flags"),
					short_tag("Unknown"),
					undefined_tag("English Sound", 9999),
					undefined_tag("Japanese Sound", 9999),
					undefined_tag("German Sound", 9999),
					undefined_tag("French Sound", 9999),
					undefined_tag("Spanish Sound", 9999),
					undefined_tag("Italian Sound", 9999),
					undefined_tag("Korean Sound", 9999),
					undefined_tag("Chinese Sound", 9999),
					undefined_tag("Portuguese Sound", 9999),
					long_tag("Probability"),
				}),
			}),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			undefined_tag("Null Block", 9999),
			undefined_tag("Default Item Collection 1", 9999),
			undefined_tag("Default Item Collection 2", 9999),
			long_tag("Default Frag Grenade Count"),
			long_tag("Default Plasma Grenade Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Upper Height"),
			long_tag("Lower Height"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Vehicle Inner Radius"),
			long_tag("Vehicle Outer Radius"),
			long_tag("Vehicle Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Inner Radius"),
			long_tag("Outer Radius"),
			long_tag("Weight"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("Multiplayer Constants",
			{
				long_tag("Maximum Random Spawn Bias"),
				long_tag("Teleporter Recharge Time"),
				long_tag("Grenade Danger Weight"),
				long_tag("Grenade Danger Inner Radius"),
				long_tag("Grenade Danger Outer Radius"),
				long_tag("Grenade Danger Lead Time"),
				long_tag("Vehicle Danger Minimum Speed"),
				long_tag("Vehicle Danger Weight"),
				long_tag("Vehicle Danger Radius"),
				long_tag("Vehicle Danger Lead Time"),
				long_tag("Vehicle Nearby Player Distance"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Hill Shader", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Flag Reset Stop Distance"),
				undefined_tag("Bomb Explode Effect", 9999),
				undefined_tag("Bomb Explode Damage Effect", 9999),
				undefined_tag("Bomb Defuse Effect", 9999),
				undefined_tag("Bomb Defusal String", 9999),
				undefined_tag("Blocked Teleporter String", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("State Responses",
			{
				short_tag("Flags"),
				short_tag("Unknown"),
				short_tag("State"),
				short_tag("Unknown"),
				undefined_tag("Free For All Message", 9999),
				undefined_tag("Team Message", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			undefined_tag("Scoreboard HUD Definition", 9999),
			undefined_tag("Scoreboard Emblem Shader", 9999),
			undefined_tag("Scoreboard Emblem Bitmap", 9999),
			undefined_tag("Scoreboard Dead Emblem Shader", 9999),
			undefined_tag("Scoreboard Dead Emblem Bitmap", 9999),
		}),
	});
};
