#include "nhdt.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* nhdt_group = new tag_collection(
	"nhdt",
	{
		
		undefined_tag("Unknown", 9999),
		block_tag("Bitmap Widgets",
		{
			undefined_tag("Name", 9999),
			byte_tag("Input 1"),
			byte_tag("Input 2"),
			byte_tag("Input 3"),
			byte_tag("Input 4"),
			undefined_tag("", 9999),
			short_tag("[Yes] Unit Flags"),
			short_tag("[Yes] Extra Flags"),
			short_tag("[Yes] Weapon Flags"),
			short_tag("[Yes] Game Engine State Flags"),
			short_tag("[No] Unit Flags"),
			short_tag("[No] Extra Flags"),
			short_tag("[No] Weapon Flags"),
			short_tag("[No] Game Engine State Flags"),
			byte_tag("Age Cutoff"),
			byte_tag("Clip Cutoff"),
			byte_tag("Total Cutoff"),
			byte_tag("Unknown"),
			short_tag("Anchor"),
			short_tag("Flags"),
			undefined_tag("Bitmap", 9999),
			undefined_tag("Shader", 9999),
			byte_tag("Fullscreen Sequence Index"),
			byte_tag("Halfscreen Sequence Index"),
			byte_tag("Quarterscreen Sequence Index"),
			byte_tag("Unknown"),
			point16_tag("Fullscreen Offset"),
			point16_tag("Halfscreen Offset"),
			point16_tag("Quarterscreen Offset"),
			undefined_tag("Fullscreen Registration Point", 9999),
			undefined_tag("Halfscreen Registration Point", 9999),
			undefined_tag("Quarterscreen Registration Point", 9999),
			block_tag("Effect",
			{
				short_tag("Flags"),
				short_tag("Unknown"),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
			}),
			short_tag("Special HUD Type"),
			short_tag("Unknown"),
		}),
		block_tag("Text Widgets",
		{
			undefined_tag("Name", 9999),
			byte_tag("Input 1"),
			byte_tag("Input 2"),
			byte_tag("Input 3"),
			byte_tag("Input 4"),
			undefined_tag("", 9999),
			short_tag("[Yes] Unit Flags"),
			short_tag("[Yes] Extra Flags"),
			short_tag("[Yes] Weapon Flags"),
			short_tag("[Yes] Game Engine State Flags"),
			short_tag("[No] Unit Flags"),
			short_tag("[No] Extra Flags"),
			short_tag("[No] Weapon Flags"),
			short_tag("[No] Game Engine State Flags"),
			byte_tag("Age Cutoff"),
			byte_tag("Clip Cutoff"),
			byte_tag("Total Cutoff"),
			byte_tag("Unknown"),
			short_tag("Anchor"),
			short_tag("Flags"),
			undefined_tag("Shader", 9999),
			undefined_tag("String", 9999),
			short_tag("Justification"),
			short_tag("Unknown"),
			byte_tag("Fullscreen Font Index"),
			byte_tag("Halfscreen Font Index"),
			byte_tag("Quarterscreen Font Index"),
			byte_tag("Unknown"),
			long_tag("Fullscreen Scale"),
			long_tag("Halfscreen Scale"),
			long_tag("Quarterscreen Scale"),
			point16_tag("Fullscreen Offset"),
			point16_tag("Halfscreen Offset"),
			point16_tag("Quarterscreen Offset"),
			block_tag("Effect",
			{
				short_tag("Flags"),
				short_tag("Unknown"),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
			}),
		}),
		short_tag("Low Clip Cutoff"),
		short_tag("Low Ammo Cutoff"),
		long_tag("Age Cutoff"),
		block_tag("Screen Effect Widgets",
		{
			undefined_tag("Name", 9999),
			byte_tag("Input 1"),
			byte_tag("Input 2"),
			byte_tag("Input 3"),
			byte_tag("Input 4"),
			undefined_tag("", 9999),
			short_tag("[Yes] Unit Flags"),
			short_tag("[Yes] Extra Flags"),
			short_tag("[Yes] Weapon Flags"),
			short_tag("[Yes] Game Engine State Flags"),
			short_tag("[No] Unit Flags"),
			short_tag("[No] Extra Flags"),
			short_tag("[No] Weapon Flags"),
			short_tag("[No] Game Engine State Flags"),
			byte_tag("Age Cutoff"),
			byte_tag("Clip Cutoff"),
			byte_tag("Total Cutoff"),
			byte_tag("Unknown"),
			short_tag("Anchor"),
			short_tag("Flags"),
			undefined_tag("Bitmap", 9999),
			undefined_tag("Fullscreen Screen Effect", 9999),
			undefined_tag("Halfscreen Screen Effect", 9999),
			undefined_tag("Quarterscreen Screen Effect", 9999),
			byte_tag("Fullscreen Sequence Index"),
			byte_tag("Halfscreen Sequence Index"),
			byte_tag("Quarterscreen Sequence Index"),
			byte_tag("Unknown"),
			point16_tag("Fullscreen Offset"),
			point16_tag("Halfscreen Offset"),
			point16_tag("Quarterscreen Offset"),
		}),
	});
};
