#include "phmo.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* phmo_group = new tag_collection(
	"phmo",
	{
		
		undefined_tag("Flags", 9999),
		long_tag("Mass"),
		long_tag("Low Frequency Deactivation Scale"),
		long_tag("High Frequency Deactivation Scale"),
		long_tag("Unknown"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Phantom Types",
		{
			undefined_tag("Flags", 9999),
			byte_tag("Minimum Size"),
			byte_tag("Maximum Size"),
			short_tag("Unknown"),
			undefined_tag("Marker Name", 9999),
			undefined_tag("Alignment Marker Name", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Hooke's Law E"),
			long_tag("Linear Dead Radius"),
			long_tag("Center Acceleration"),
			long_tag("Center Maximum Velocity"),
			long_tag("Axis Acceleration"),
			long_tag("Axis Maximum Velocity"),
			long_tag("Direction Acceleration"),
			long_tag("Direction Maximum Velocity"),
			long_tag("Orbit Acceleration"),
			long_tag("Orbit Maximum Velocity"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Alignment Hooke's Law E"),
			long_tag("Alignment Acceleration"),
			long_tag("Alignment Maximum Velocity"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Node Edges",
		{
			short_tag("Node A Material Global Index"),
			short_tag("Node B Material Global Index"),
			short_tag("Node A Index"),
			short_tag("Node B Index"),
			block_tag("Constraints",
			{
				short_tag("Type"),
				short_tag("Index"),
				undefined_tag("Flags", 9999),
				long_tag("Friction"),
			}),
			undefined_tag("Node A Material Name", 9999),
			undefined_tag("Node B Material Name", 9999),
		}),
		block_tag("Rigid Bodies",
		{
			short_tag("Node Index"),
			short_tag("Region Index"),
			short_tag("Permutation Index"),
			short_tag("Unknown"),
			undefined_tag("Bounding Sphere Offset", 9999),
			long_tag("Bounding Sphere Radius"),
			short_tag("Flags"),
			short_tag("Motion Type"),
			short_tag("No Phantom Power Alternative Rigid Body Index"),
			short_tag("Size"),
			long_tag("Inertia Tensor Scale"),
			long_tag("Linear Damping"),
			long_tag("Angular Damping"),
			undefined_tag("Center Of Mass Offset", 9999),
			short_tag("Shape Type"),
			short_tag("Shape Index"),
			long_tag("Mass"),
			undefined_tag("Center Of Mass", 9999),
			long_tag("w Center Of Mass"),
			undefined_tag("Inertia Tensor x", 9999),
			long_tag("w Inertia Tensor x"),
			undefined_tag("Inertia Tensor y", 9999),
			long_tag("w Inertia Tensor y"),
			undefined_tag("Inertia Tensor z", 9999),
			long_tag("w Inertia Tensor z"),
			long_tag("Bounding Sphere Pad"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			byte_tag("Collision Quality Override Type"),
			byte_tag("Unknown"),
			short_tag("Runtime Flags"),
		}),
		block_tag("Materials",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Global Material Name", 9999),
			short_tag("Phantom Type Index"),
			short_tag("Flags"),
		}),
		block_tag("Spheres",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("User Data", 9999),
			undefined_tag("Rotation i", 9999),
			long_tag("w Rotation i"),
			undefined_tag("Rotation j", 9999),
			long_tag("w Rotation j"),
			undefined_tag("Rotation k", 9999),
			long_tag("w Rotation k"),
			undefined_tag("Translation", 9999),
			long_tag("w Translation"),
		}),
		block_tag("Multi Spheres",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Number Of Spheres"),
			undefined_tag("Sphere 0", 9999),
			long_tag("w Sphere 0"),
			undefined_tag("Sphere 1", 9999),
			long_tag("w Sphere 1"),
			undefined_tag("Sphere 2", 9999),
			long_tag("w Sphere 2"),
			undefined_tag("Sphere 3", 9999),
			long_tag("w Sphere 3"),
			undefined_tag("Sphere 4", 9999),
			long_tag("w Sphere 4"),
			undefined_tag("Sphere 5", 9999),
			long_tag("w Sphere 5"),
			undefined_tag("Sphere 6", 9999),
			long_tag("w Sphere 6"),
			undefined_tag("Sphere 7", 9999),
			long_tag("w Sphere 7"),
		}),
		block_tag("Pills",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Bottom", 9999),
			long_tag("w Bottom"),
			undefined_tag("Top", 9999),
			long_tag("w Top"),
		}),
		block_tag("Boxes",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Half Extents", 9999),
			long_tag("w Half Extents"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("User Data", 9999),
			undefined_tag("Rotation i", 9999),
			long_tag("w Rotation i"),
			undefined_tag("Rotation j", 9999),
			long_tag("w Rotation j"),
			undefined_tag("Rotation k", 9999),
			long_tag("w Rotation k"),
			undefined_tag("Translation", 9999),
			long_tag("w Translation"),
		}),
		block_tag("Triangles",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Point a", 9999),
			long_tag("w Point a"),
			undefined_tag("Point b", 9999),
			long_tag("w Point b"),
			undefined_tag("Point c", 9999),
			long_tag("w Point c"),
		}),
		block_tag("Polyhedra",
		{
			undefined_tag("Name", 9999),
			short_tag("Material Index"),
			short_tag("Flags"),
			long_tag("Relative Mass Scale"),
			long_tag("Friction"),
			long_tag("Restitution"),
			long_tag("Volume"),
			long_tag("Mass"),
			short_tag("Mass Distribution Index"),
			byte_tag("Phantom Type Index"),
			byte_tag("Collision Group"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			long_tag("Radius"),
			undefined_tag("Axis-Aligned Bounding Box Half Extents", 9999),
			long_tag("w Axis-Aligned Bounding Box Half Extents"),
			undefined_tag("Axis-Aligned Bounding Box Center", 9999),
			long_tag("w Axis-Aligned Bounding Box Center"),
			undefined_tag("Runtime Four Vectors Pointer", 9999),
			long_tag("Four Vectors Size"),
			undefined_tag("Four Vectors Capacity", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Four Vectors 0 x", 9999),
			long_tag("w Four Vectors 0 x"),
			undefined_tag("Four Vectors 0 y", 9999),
			long_tag("w Four Vectors 0 y"),
			undefined_tag("Four Vectors 0 z", 9999),
			long_tag("w Four Vectors 0 z"),
			undefined_tag("Four Vectors 1 x", 9999),
			long_tag("w Four Vectors 1 x"),
			undefined_tag("Four Vectors 1 y", 9999),
			long_tag("w Four Vectors 1 y"),
			undefined_tag("Four Vectors 1 z", 9999),
			long_tag("w Four Vectors 1 z"),
			undefined_tag("Four Vectors 2 x", 9999),
			long_tag("w Four Vectors 2 x"),
			undefined_tag("Four Vectors 2 y", 9999),
			long_tag("w Four Vectors 2 y"),
			undefined_tag("Four Vectors 2 z", 9999),
			long_tag("w Four Vectors 2 z"),
			long_tag("Number Of Vertices"),
			undefined_tag("Runtime Plane Equations Pointer", 9999),
			long_tag("Plane Equations Size"),
			undefined_tag("Plane Equations Capacity", 9999),
		}),
		block_tag("Polyhedron Four Vectors",
		{
			undefined_tag("Four Vectors x", 9999),
			long_tag("w Four Vectors x"),
			undefined_tag("Four Vectors y", 9999),
			long_tag("w Four Vectors y"),
			undefined_tag("Four Vectors z", 9999),
			long_tag("w Four Vectors z"),
		}),
		block_tag("Polyhedron Plane Equations",
		{
			undefined_tag("Plane Equations", 9999),
			long_tag("w Plane Equations"),
		}),
		block_tag("Mass Distributions",
		{
			undefined_tag("Center Of Mass", 9999),
			long_tag("w Center Of Mass"),
			undefined_tag("Inertia Tensor i", 9999),
			long_tag("w Inertia Tensor i"),
			undefined_tag("Inertia Tensor j", 9999),
			long_tag("w Inertia Tensor j"),
			undefined_tag("Inertia Tensor k", 9999),
			long_tag("w Inertia Tensor k"),
		}),
		block_tag("Lists",
		{
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("User Data", 9999),
			long_tag("Child Shapes Size"),
			undefined_tag("Child Shapes Capacity", 9999),
			short_tag("Shape Type 0"),
			short_tag("Shape Index 0"),
			long_tag("Collision Filter 0"),
			short_tag("Shape Type 1"),
			short_tag("Shape Index 1"),
			long_tag("Collision Filter 1"),
			short_tag("Shape Type 2"),
			short_tag("Shape Index 2"),
			long_tag("Collision Filter 2"),
			short_tag("Shape Type 3"),
			short_tag("Shape Index 3"),
			long_tag("Collision Filter 3"),
		}),
		block_tag("List Shapes",
		{
			short_tag("Shape Type"),
			short_tag("Shape Index"),
			long_tag("Collision Filter"),
		}),
		block_tag("MOPPs",
		{
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			short_tag("Shape Type"),
			short_tag("Shape Index"),
			undefined_tag("Runtime MOPP Code Pointer", 9999),
		}),
		undefined_tag("MOPP Codes", 9999),
		block_tag("Hinge Constraints",
		{
			undefined_tag("Name", 9999),
			short_tag("Node A Index"),
			short_tag("Node B Index"),
			long_tag("A Scale"),
			undefined_tag("A Forward", 9999),
			undefined_tag("A Left", 9999),
			undefined_tag("A Up", 9999),
			undefined_tag("A Position", 9999),
			long_tag("B Scale"),
			undefined_tag("B Forward", 9999),
			undefined_tag("B Left", 9999),
			undefined_tag("B Up", 9999),
			undefined_tag("B Position", 9999),
			short_tag("Edge Index"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Ragdoll Constraints",
		{
			undefined_tag("Name", 9999),
			short_tag("Node A Index"),
			short_tag("Node B Index"),
			long_tag("A Scale"),
			undefined_tag("A Forward", 9999),
			undefined_tag("A Left", 9999),
			undefined_tag("A Up", 9999),
			undefined_tag("A Position", 9999),
			long_tag("B Scale"),
			undefined_tag("B Forward", 9999),
			undefined_tag("B Left", 9999),
			undefined_tag("B Up", 9999),
			undefined_tag("B Position", 9999),
			short_tag("Edge Index"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Twist", 9999),
			undefined_tag("Cone", 9999),
			undefined_tag("Plane", 9999),
			long_tag("Maximum Friciton Torque"),
		}),
		block_tag("Regions",
		{
			undefined_tag("Name", 9999),
			block_tag("Permutations",
			{
				undefined_tag("Name", 9999),
				block_tag("Rigid Bodies",
				{
					short_tag("Rigid Body Index"),
				}),
			}),
		}),
		block_tag("Nodes",
		{
			undefined_tag("Name", 9999),
			short_tag("Flags"),
			short_tag("Parent Index"),
			short_tag("Sibling Index"),
			short_tag("Child Index"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Point To Path Curves",
		{
			undefined_tag("Name", 9999),
			short_tag("Node Index"),
			short_tag("Unknown"),
			block_tag("Points",
			{
				undefined_tag("Position", 9999),
				long_tag("t Value"),
			}),
		}),
		block_tag("Limited Hinge Constraints",
		{
			undefined_tag("Name", 9999),
			short_tag("Node A Index"),
			short_tag("Node B Index"),
			long_tag("A Scale"),
			undefined_tag("A Forward", 9999),
			undefined_tag("A Left", 9999),
			undefined_tag("A Up", 9999),
			undefined_tag("A Position", 9999),
			long_tag("B Scale"),
			undefined_tag("B Forward", 9999),
			undefined_tag("B Left", 9999),
			undefined_tag("B Up", 9999),
			undefined_tag("B Position", 9999),
			short_tag("Edge Index"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			long_tag("Limit Friction"),
			undefined_tag("Limit Angle", 9999),
		}),
		block_tag("Ball And Socket Constraints",
		{
			undefined_tag("Name", 9999),
			short_tag("Node A Index"),
			short_tag("Node B Index"),
			long_tag("A Scale"),
			undefined_tag("A Forward", 9999),
			undefined_tag("A Left", 9999),
			undefined_tag("A Up", 9999),
			undefined_tag("A Position", 9999),
			long_tag("B Scale"),
			undefined_tag("B Forward", 9999),
			undefined_tag("B Left", 9999),
			undefined_tag("B Up", 9999),
			undefined_tag("B Position", 9999),
			short_tag("Edge Index"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Stiff Spring Constraints",
		{
			undefined_tag("Name", 9999),
			short_tag("Node A Index"),
			short_tag("Node B Index"),
			long_tag("A Scale"),
			undefined_tag("A Forward", 9999),
			undefined_tag("A Left", 9999),
			undefined_tag("A Up", 9999),
			undefined_tag("A Position", 9999),
			long_tag("B Scale"),
			undefined_tag("B Forward", 9999),
			undefined_tag("B Left", 9999),
			undefined_tag("B Up", 9999),
			undefined_tag("B Position", 9999),
			short_tag("Edge Index"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			long_tag("Spring Length"),
		}),
		block_tag("Prismatic Constraints",
		{
			undefined_tag("Name", 9999),
			short_tag("Node A Index"),
			short_tag("Node B Index"),
			long_tag("A Scale"),
			undefined_tag("A Forward", 9999),
			undefined_tag("A Left", 9999),
			undefined_tag("A Up", 9999),
			undefined_tag("A Position", 9999),
			long_tag("B Scale"),
			undefined_tag("B Forward", 9999),
			undefined_tag("B Left", 9999),
			undefined_tag("B Up", 9999),
			undefined_tag("B Position", 9999),
			short_tag("Edge Index"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Limit Angle", 9999),
			long_tag("Maximum Friction Force"),
		}),
		block_tag("Phantoms",
		{
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			short_tag("Shape Type"),
			short_tag("Shape Index"),
			long_tag("Collision Filter"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
		}),
	});
};
