#include "phys.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* phys_group = new tag_collection(
	"phys",
	{
		
		long_tag("Radius"),
		long_tag("Moment Scale"),
		long_tag("Mass"),
		long_tag("Center of mass x"),
		long_tag("Center of mass y"),
		long_tag("Center of mass z"),
		long_tag("Density"),
		long_tag("Gravity scale"),
		long_tag("Ground friction"),
		long_tag("Ground Depth"),
		long_tag("Ground damp function"),
		long_tag("Normal K1"),
		long_tag("Normal K0"),
		undefined_tag("Unknown", 9999),
		long_tag("Water Friction"),
		long_tag("Water Depth"),
		long_tag("Water Density"),
		undefined_tag("Unknown", 9999),
		long_tag("Air friction"),
		undefined_tag("Unknown", 9999),
		long_tag("xx movement"),
		long_tag("yy movement"),
		long_tag("zz movement"),
		block_tag("Internal Matrix",
		{
			long_tag("yy+zz"),
			long_tag("-xy"),
			long_tag("-zx"),
			long_tag("-xy"),
			long_tag("zz+xx"),
			long_tag("-yz"),
			long_tag("-zx"),
			long_tag("-yz"),
			long_tag("xx+yy"),
		}),
		block_tag("Mass Points",
		{
			string_tag("Name"),
			undefined_tag("flags", 9999),
			long_tag("strength"),
			long_tag("offset real"),
			long_tag("height real"),
			long_tag("damp fraction"),
			long_tag("normal k1"),
			long_tag("normal k0"),
		}),
		block_tag("Mass Points",
		{
			string_tag("Name"),
			short_tag("Model Node"),
			short_tag("Powered Mass Point"),
			undefined_tag("flags", 9999),
			long_tag("Relative Mass"),
			long_tag("Mass"),
			long_tag("Relative Density"),
			long_tag("Density"),
			long_tag("Pos X"),
			long_tag("Pos Y"),
			long_tag("Pos Z"),
			undefined_tag("Forward i", 9999),
			undefined_tag("Forward j", 9999),
			undefined_tag("Forward k", 9999),
			undefined_tag("Up i", 9999),
			undefined_tag("Up j", 9999),
			undefined_tag("Up k", 9999),
			undefined_tag("friction type", 9999),
			long_tag("Friction Parallel Scale"),
			long_tag("Friction Perpendicular Scale"),
			long_tag("Radius"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
	});
};
