#include "proj.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* proj_group = new tag_collection(
	"proj",
	{
		
		short_tag("Object Type"),
		short_tag("Flags"),
		long_tag("Bounding Radius"),
		undefined_tag("Bounding Offset", 9999),
		long_tag("Acceleration Scale"),
		short_tag("Lightmap Shadow Mode"),
		byte_tag("Sweetener Size"),
		byte_tag("Unknown"),
		undefined_tag("Runtime Flags", 9999),
		long_tag("Dynamic Light Sphere Radius"),
		undefined_tag("Dynamic Light Sphere Offset", 9999),
		undefined_tag("Default Model Variant", 9999),
		undefined_tag("Model", 9999),
		undefined_tag("Crate Object", 9999),
		undefined_tag("Modifier Shader", 9999),
		undefined_tag("Creation Effect", 9999),
		undefined_tag("Material Effects", 9999),
		block_tag("AI Properties",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("AI Type Name", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("AI Size"),
			short_tag("Leap Jump Speed"),
		}),
		block_tag("Functions",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Import Name", 9999),
			undefined_tag("Export Name", 9999),
			undefined_tag("Turn Off With", 9999),
			long_tag("Minimum Value"),
			undefined_tag("Default Function", 9999),
			undefined_tag("Scale By", 9999),
		}),
		long_tag("Apply Collision Damage Scale"),
		undefined_tag("Game Acceleration", 9999),
		undefined_tag("Game Scale", 9999),
		undefined_tag("Absolute Acceleration", 9999),
		undefined_tag("Absolute Scale", 9999),
		short_tag("HUD Text Message Index"),
		short_tag("Unknown"),
		block_tag("Attachments",
		{
			undefined_tag("Type", 9999),
			undefined_tag("Marker", 9999),
			short_tag("Change Color"),
			short_tag("Unknown"),
			undefined_tag("Primary Scale", 9999),
			undefined_tag("Secondary Scale", 9999),
		}),
		block_tag("Widgets",
		{
			undefined_tag("Type", 9999),
		}),
		block_tag("Old Functions",
		{
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Change Colors",
		{
			block_tag("Initial Permutations",
			{
				long_tag("Weight"),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Variant Name", 9999),
			}),
			block_tag("Functions",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Scale Flags", 9999),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Darken By", 9999),
				undefined_tag("Scale By", 9999),
			}),
		}),
		block_tag("Predicted Resources",
		{
			short_tag("Type"),
			short_tag("Resource Index"),
			tagref_tag("Tag Index"),
		}),
		undefined_tag("Flags", 9999),
		short_tag("Detonation Timer Starts"),
		short_tag("Impact Noise"),
		long_tag("AI Perception Radius"),
		long_tag("Collision Radius"),
		long_tag("Arming Time"),
		long_tag("Danger Radius"),
		undefined_tag("Timer", 9999),
		long_tag("Minimum Velocity"),
		long_tag("Maximum Range"),
		short_tag("Detonation Noise"),
		short_tag("Super Detonation Projectile Count"),
		undefined_tag("Detonation Started", 9999),
		undefined_tag("Airborne Detonation Effect", 9999),
		undefined_tag("Ground Detonation Effect", 9999),
		undefined_tag("Detonation Damage", 9999),
		undefined_tag("Attached Detonation Damage", 9999),
		undefined_tag("Super Detonation", 9999),
		undefined_tag("Super Detonation Damage", 9999),
		undefined_tag("Detonation Sound", 9999),
		byte_tag("Damage Reporting Type"),
		byte_tag("Unknown"),
		short_tag("Unknown"),
		undefined_tag("Attached Super Detonation Damage", 9999),
		long_tag("Material Effect Radius"),
		undefined_tag("Flyby Sound", 9999),
		undefined_tag("Impact Effect", 9999),
		undefined_tag("Impact Damage", 9999),
		long_tag("Boarding Detonation Time"),
		undefined_tag("Boarding Detonation Damage", 9999),
		undefined_tag("Boarding Attached Detonation Damage", 9999),
		long_tag("Air Gravity Scale"),
		undefined_tag("Air Damage Range", 9999),
		long_tag("Water Gravity Scale"),
		undefined_tag("Water Damage Range", 9999),
		long_tag("Initial Velocity"),
		long_tag("Final Velocity"),
		undefined_tag("Guided Angular Velocity Lower", 9999),
		undefined_tag("Guided Angular Velocity Upper", 9999),
		undefined_tag("Acceleration Range", 9999),
		long_tag("Runtime Acceleration Bound Inverse"),
		long_tag("Targeted Leading Fraction"),
		block_tag("Material Responses",
		{
			short_tag("Flags"),
			short_tag("Default Response"),
			undefined_tag("DO NOT USE (OLD Effect)", 9999),
			undefined_tag("Material Name", 9999),
			short_tag("Global Material Index"),
			short_tag("Unknown"),
			short_tag("Potential Response"),
			short_tag("Response Flags"),
			long_tag("Chance Fraction"),
			undefined_tag("Between Angle", 9999),
			undefined_tag("And Velocity", 9999),
			undefined_tag("Old Effect", 9999),
			short_tag("Scale Effects By"),
			short_tag("Unknown"),
			undefined_tag("Angular Noise", 9999),
			long_tag("Velocity Noise"),
			undefined_tag("Old Effect", 9999),
			long_tag("Initial Friction"),
			long_tag("Maximum Distance"),
			long_tag("Parallel Friction"),
			long_tag("Perpendicular Friction"),
		}),
	});
};
