#include "prt3.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* prt3_group = new tag_collection(
	"prt3",
	{
		
		undefined_tag("Flags", 9999),
		undefined_tag("Particle Billboard Style", 9999),
		short_tag("First Billboard Style"),
		short_tag("Sequence Count"),
		undefined_tag("Shader Template", 9999),
		block_tag("Shader",
		{
			undefined_tag("Name", 9999),
			short_tag("Type"),
			short_tag("Unknown"),
			undefined_tag("Bitmap", 9999),
			long_tag("Constant Value"),
			undefined_tag("Constant Color", 9999),
			block_tag("Animation Properties",
			{
				short_tag("Type"),
				short_tag("Unknown"),
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period"),
				undefined_tag("Animation Function", 9999),
			}),
		}),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Function", 9999),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Function", 9999),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Function", 9999),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Function", 9999),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Function", 9999),
		undefined_tag("Collision Effect", 9999),
		undefined_tag("Death Effect", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		block_tag("Locations",
		{
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("Marker Name", 9999),
		}),
		block_tag("Attached Particle Systems",
		{
			undefined_tag("Particle", 9999),
			long_tag("Location Index"),
			short_tag("Coordinate System"),
			short_tag("Environment"),
			short_tag("Disposition"),
			short_tag("Camera Mode"),
			short_tag("Sort Bias"),
			short_tag("Flags"),
			long_tag("LOD In Distance"),
			long_tag("LOD Feather In Delta"),
			undefined_tag("Unknown", 9999),
			long_tag("LOD Out Distance"),
			long_tag("LOD Feather Out Delta"),
			undefined_tag("Unknown", 9999),
			block_tag("Emitters",
			{
				undefined_tag("Particle Physics", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				undefined_tag("Emission Shape", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				short_tag("Input Variable"),
				short_tag("Range Variable"),
				short_tag("Output Modifier"),
				short_tag("Output Modifier Input"),
				undefined_tag("Function", 9999),
				undefined_tag("Translational Offset", 9999),
				undefined_tag("Relative Direction", 9999),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
		}),
		block_tag("Postprocess Definition",
		{
			undefined_tag("Shader Template", 9999),
			block_tag("Bitmaps",
			{
				undefined_tag("Bitmap Group", 9999),
				long_tag("Bitmap Index"),
				long_tag("Log Bitmap Dimension"),
			}),
			block_tag("Pixel Constants",
			{
				undefined_tag("Color", 9999),
			}),
			block_tag("Vertex Constants",
			{
				undefined_tag("vector", 9999),
				long_tag("w"),
			}),
			block_tag("Levels Of Detail",
			{
				long_tag("Available Layer Flags"),
				short_tag("Layers Block Index Data"),
			}),
			block_tag("Layers",
			{
				short_tag("Indices Block Index Data"),
			}),
			block_tag("Passes",
			{
				short_tag("Indices Block Index Data"),
			}),
			block_tag("Implementations",
			{
				short_tag("Bitmap Transforms Block Index Data"),
				short_tag("Render States Block Index Data"),
				short_tag("Texture States Block Index Data"),
				short_tag("Pixel Constants Block Index Data"),
				short_tag("Vertex Constants Block Index Data"),
			}),
			block_tag("Overlays",
			{
				undefined_tag("Input Name", 9999),
				undefined_tag("Range Name", 9999),
				long_tag("Time Period In Seconds"),
				undefined_tag("Function", 9999),
			}),
			block_tag("Overlay References",
			{
				short_tag("Overlay Index"),
				short_tag("Transform Index"),
			}),
			block_tag("Animated Parameters",
			{
				short_tag("Overlay References Block Index Data"),
			}),
			block_tag("Animated Parameter References",
			{
				short_tag("Unknown"),
				byte_tag("Unknown"),
				byte_tag("Parameter Index"),
			}),
			block_tag("Bitmap Properties",
			{
				short_tag("Bitmap Index"),
				short_tag("Animated Parameter Index"),
			}),
			block_tag("Color Properties",
			{
				undefined_tag("Color", 9999),
			}),
			block_tag("Value Properties",
			{
				long_tag("Value"),
			}),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Unknown"),
		long_tag("Unknown"),
		long_tag("Unknown"),
		long_tag("Unknown"),
		long_tag("Unknown"),
		long_tag("Unknown"),
	});
};
