#include "PRTM.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* PRTM_group = new tag_collection(
	"PRTM",
	{
		
		undefined_tag("Flags", 9999),
		undefined_tag("Orientation", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Shader", 9999),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Scale X", 9999),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Scale Y", 9999),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Scale Z", 9999),
		short_tag("Input Variable"),
		short_tag("Range Variable"),
		short_tag("Output Modifier"),
		short_tag("Output Modifier Input"),
		undefined_tag("Rotation", 9999),
		undefined_tag("Collision Effect", 9999),
		undefined_tag("Death Effect", 9999),
		block_tag("Locations",
		{
			undefined_tag("Marker Name", 9999),
		}),
		block_tag("Attached Particle System",
		{
			undefined_tag("Particle", 9999),
			long_tag("Location Index"),
			short_tag("Coordinate System"),
			short_tag("Environment"),
			short_tag("Disposition"),
			short_tag("Camera Mode"),
			short_tag("Sort Bias"),
			short_tag("Flags"),
			long_tag("LOD In Distance"),
			long_tag("LOD Feather In Delta"),
			undefined_tag("Unknown", 9999),
			long_tag("LOD Out Distance"),
			long_tag("LOD Feather Out Delta"),
			undefined_tag("Unknown", 9999),
			block_tag("Emitters",
			{
				undefined_tag("Particle Physics", 9999),
				short_tag("Input"),
				short_tag("Range"),
				short_tag("Output Modifier Kind"),
				short_tag("Output Modifier"),
				undefined_tag("Particle Emission Rate", 9999),
				short_tag("Input"),
				short_tag("Range"),
				short_tag("Output Modifier Kind"),
				short_tag("Output Modifier"),
				undefined_tag("Particle Lifespan (sec)", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Particle Velocity (World Units Per Sec)", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Particle Angular Velocity (Degrees Per Sec)", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Particle Size (World Units)", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Particle Tint", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Particle Alpha", 9999),
				undefined_tag("Emission Shape", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Emission Radius (World Units)", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Output Modifier", 9999),
				undefined_tag("Emission Angle (Degrees)", 9999),
				long_tag("Translation Offset X"),
				long_tag("Translation Offset Y"),
				long_tag("Translation Offset Z"),
				long_tag("Relative Direction Yaw"),
				long_tag("Relative Direction Pitch"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
		}),
		block_tag("Models",
		{
			undefined_tag("Model Name", 9999),
			short_tag("Index Start"),
			short_tag("Index Count"),
		}),
		block_tag("Raw Vertices",
		{
			long_tag("Pos X"),
			long_tag("Pos Y"),
			long_tag("Pos Z"),
			undefined_tag("Normal i", 9999),
			undefined_tag("Normal j", 9999),
			undefined_tag("Normal k", 9999),
			undefined_tag("Tangent i", 9999),
			undefined_tag("Tangent j", 9999),
			undefined_tag("Tangent k", 9999),
			undefined_tag("Binormal i", 9999),
			undefined_tag("Binormal j", 9999),
			undefined_tag("Binormal k", 9999),
			long_tag("Texture Coord X"),
			long_tag("Texture Coord Y"),
		}),
		block_tag("Indices",
		{
			short_tag("Index"),
		}),
		block_tag("Cached Data",
		{
			undefined_tag("Vertex Buffer", 9999),
		}),
		long_tag("Resource Block Offset"),
		undefined_tag("Resource Block Size", 9999),
		undefined_tag("Section Data Size", 9999),
		undefined_tag("Resource Data Size", 9999),
		block_tag("Resources",
		{
			byte_tag("Type"),
			byte_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Primary Locator"),
			short_tag("Secondary Locator"),
			undefined_tag("Resource Data Size", 9999),
			undefined_tag("Resource Data Offset", 9999),
		}),
		tagref_tag("Owner Tag"),
		short_tag("Owner Tag Section Offset"),
		short_tag("Unknown"),
		long_tag("Unknown"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
	});
};
