#include "sbsp.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* sbsp_group = new tag_collection(
	"sbsp",
	{
		
		undefined_tag("Import Info", 9999),
		undefined_tag("Import Info", 9999),
		long_tag("BSP Checksum"),
		block_tag("Collision Materials",
		{
			undefined_tag("Old Shader", 9999),
			short_tag("Global Material Index"),
			short_tag("Conveyor Surface Index"),
			undefined_tag("New Shader", 9999),
		}),
		block_tag("Collision BSP",
		{
			block_tag("3D Nodes",
			{
				short_tag("Plane"),
				short_tag("Back child"),
				undefined_tag("Flag/padding/Unknown", 9999),
				short_tag("Front Child"),
				undefined_tag("Flag/padding/Unknown2", 9999),
			}),
			block_tag("Planes",
			{
				long_tag("Plane i"),
				long_tag("Plane j"),
				long_tag("Plane k"),
				long_tag("Plane d"),
			}),
			block_tag("Leaves",
			{
				undefined_tag("Flags", 9999),
				undefined_tag("BSP 2D Reference Count", 9999),
				short_tag("First BSP 2D Reference"),
			}),
			block_tag("BSP 2D References",
			{
				short_tag("Plane"),
				short_tag("BSP 2D Node"),
			}),
			block_tag("BSP 2D Nodes",
			{
				long_tag("Plane i"),
				long_tag("Plane j"),
				long_tag("Plane d"),
				short_tag("Left Child"),
				short_tag("Right Child"),
			}),
			block_tag("Surfaces",
			{
				short_tag("Plane"),
				short_tag("First Edge"),
				undefined_tag("Flags", 9999),
				undefined_tag("Breakable Surface Index", 9999),
				short_tag("Material Index"),
			}),
			block_tag("Edges",
			{
				short_tag("Start Vertex"),
				short_tag("End Vertex"),
				short_tag("Forward Edge"),
				short_tag("Backward Edge"),
				short_tag("Left Surface"),
				short_tag("Right Surface"),
			}),
			block_tag("Vertices",
			{
				long_tag("Point X"),
				long_tag("Point Y"),
				long_tag("Point Z"),
				short_tag("First Edge"),
				short_tag("Unknown"),
			}),
		}),
		long_tag("Vehicle Floor"),
		long_tag("Vehicle Ceiling"),
		undefined_tag("Unused Nodes", 9999),
		undefined_tag("Unused Nodes", 9999),
		block_tag("Leaves",
		{
			short_tag("Cluster"),
			short_tag("Surface Reference Count"),
			long_tag("First Surface Refrence Index"),
		}),
		long_tag("World Bounds X min"),
		long_tag("World Bounds X max"),
		long_tag("World Bounds Y min"),
		long_tag("World Bounds Y max"),
		long_tag("World Bounds Z min"),
		long_tag("World Bounds Z max"),
		block_tag("Surface References",
		{
			short_tag("Strip Index"),
			short_tag("Lightmap Triangle Index"),
			long_tag("BSP Node Index"),
		}),
		undefined_tag("Cluster Data", 9999),
		block_tag("Cluster Portals",
		{
			short_tag("Back Cluster"),
			short_tag("Front Cluster"),
			long_tag("Plane Index"),
			long_tag("Centroid X"),
			long_tag("Centroid Y"),
			long_tag("Centroid Z"),
			long_tag("Bounding Radius"),
			undefined_tag("Flags", 9999),
			block_tag("Vertices",
			{
				long_tag("Point X"),
				long_tag("Point Y"),
				long_tag("Point Z"),
			}),
		}),
		block_tag("Fog Planes",
		{
			short_tag("Scenario Planar Fog Index"),
			short_tag("Unknown"),
			long_tag("Plane i"),
			long_tag("Plane j"),
			long_tag("Plane k"),
			long_tag("Plane d"),
			short_tag("Flags"),
			short_tag("Priority"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Weather Palette",
		{
			string_tag("Name"),
			undefined_tag("Weather System", 9999),
			short_tag("Unknown"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Wind", 9999),
			undefined_tag("Wind Direction", 9999),
			long_tag("Wind Magnitude"),
			undefined_tag("Unknown", 9999),
			string_tag("Wind Scale Function"),
		}),
		block_tag("Weather Polyhedra",
		{
			long_tag("Bounding Sphere Center X"),
			long_tag("Bounding Sphere Center Y"),
			long_tag("Bounding Sphere Center Z"),
			long_tag("Bounding Sphere Radius"),
			block_tag("Planes",
			{
				undefined_tag("Plane i", 9999),
				undefined_tag("Plane j", 9999),
				undefined_tag("Plane k", 9999),
				undefined_tag("Plane d", 9999),
			}),
		}),
		block_tag("Detail Objects",
		{
			block_tag("Cells",
			{
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Instances",
			{
				byte_tag("Unknown"),
				byte_tag("Unknown"),
				byte_tag("Unknown"),
				byte_tag("Unknown"),
				short_tag("Unknown"),
			}),
			block_tag("Counts",
			{
				short_tag("Unknown"),
			}),
			block_tag("Z Reference Vectors",
			{
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
			byte_tag("Unknown"),
			byte_tag("Unknown"),
			short_tag("Unknown"),
		}),
		block_tag("Clusters",
		{
			undefined_tag("Total Vertex Count", 9999),
			undefined_tag("Total Triangle Count", 9999),
			undefined_tag("Total Part Count", 9999),
			undefined_tag("Shadow-Casting Triangle Count", 9999),
			undefined_tag("Shadow-Casting Part Count", 9999),
			undefined_tag("Opaque Point Count", 9999),
			undefined_tag("Opaque Vertex Count", 9999),
			undefined_tag("Opaque Part Count", 9999),
			undefined_tag("Opaque Max Nodes/Vertex", 9999),
			undefined_tag("Shadow-Casting Rigid Triangle Count", 9999),
			short_tag("Geometry Classification"),
			short_tag("Geometry Compression Flags"),
			block_tag("Compression Info",
			{
				long_tag("Position Bounds X min"),
				long_tag("Position Bounds X max"),
				long_tag("Position Bounds Y min"),
				long_tag("Position Bounds Y max"),
				long_tag("Position Bounds Z min"),
				long_tag("Position Bounds Z max"),
				long_tag("Texcoord Bounds X min"),
				long_tag("Texcoord Bounds X max"),
				long_tag("Texcoord Bounds Y min"),
				long_tag("Texcoord Bounds Y max"),
				long_tag("Secondary Texcoord Bounds X min"),
				long_tag("Secondary Texcoord Bounds X max"),
				long_tag("Secondary Texcoord Bounds Y min"),
				long_tag("Secondary Texcoord Bounds Y max"),
			}),
			undefined_tag("Hardware Node Count", 9999),
			undefined_tag("Node Map Size", 9999),
			undefined_tag("Software Plane Sount", 9999),
			undefined_tag("Total Subpart Count", 9999),
			short_tag("Section Lighting Flags"),
			long_tag("Resource Block Offset"),
			undefined_tag("Resource Block Size", 9999),
			undefined_tag("Section Data Size", 9999),
			undefined_tag("Resource Data Size", 9999),
			block_tag("Resources",
			{
				byte_tag("Type"),
				byte_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Primary Locator"),
				short_tag("Secondary Locator"),
				undefined_tag("Resource Data Size", 9999),
				undefined_tag("Resource Data Offset", 9999),
			}),
			tagref_tag("Owner Tag"),
			short_tag("Owner Tag Section Offset"),
			short_tag("Unknown"),
			long_tag("Unknown"),
			block_tag("Cluster Data",
			{
				block_tag("Parts",
				{
					short_tag("Type"),
					short_tag("Flags"),
					short_tag("Material Index"),
					short_tag("Strip Start Index"),
					short_tag("Strip Length"),
					short_tag("First Subpart Index"),
					short_tag("Subpart Count"),
					byte_tag("Max Nodes/Vertex"),
					byte_tag("Contributing Compound Node Count"),
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("LOD Mipmap Magic"),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				block_tag("Subparts",
				{
					short_tag("Indices Start Index"),
					short_tag("Indices Length"),
					short_tag("Visibility Bounds Index"),
					short_tag("Part Index"),
				}),
				block_tag("Visibility Bounds",
				{
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					long_tag("Radius"),
					byte_tag("Node 0"),
					byte_tag("Unknown"),
					byte_tag("Unknown"),
					byte_tag("Unknown"),
				}),
				block_tag("Raw Vertices",
				{
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Use New Node Indices"),
					long_tag("Adjusted Compound Node Index"),
					long_tag("Texcoord X"),
					long_tag("Texcoord Y"),
					long_tag("Normal i"),
					long_tag("Normal j"),
					long_tag("Normal k"),
					long_tag("Binormal i"),
					long_tag("Binormal j"),
					long_tag("Binormal k"),
					long_tag("Tangent i"),
					long_tag("Tangent j"),
					long_tag("Tangent k"),
					long_tag("Anisotropic Binormal i"),
					long_tag("Anisotropic Binormal j"),
					long_tag("Anisotropic Binormal k"),
					long_tag("Secondary Texcoord X"),
					long_tag("Secondary Texcoord Y"),
					undefined_tag("Primary Lightmap Color", 9999),
					long_tag("Primary Lightmap Texcoord X"),
					long_tag("Primary Lightmap Texcoord Y"),
					long_tag("Primary Lightmap Incident Direction i"),
					long_tag("Primary Lightmap Incident Direction j"),
					long_tag("Primary Lightmap Incident Direction k"),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				block_tag("Strip Indices",
				{
					short_tag("Index"),
				}),
				undefined_tag("Visibility MOPP Codes", 9999),
				block_tag("MOPP Reorder Table",
				{
					short_tag("Index"),
				}),
				block_tag("Vertex Buffers",
				{
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				undefined_tag("Unknown", 9999),
			}),
			long_tag("Bounds X min"),
			long_tag("Bounds X max"),
			long_tag("Bounds Y min"),
			long_tag("Bounds Y max"),
			long_tag("Bounds Z min"),
			long_tag("Bounds Z max"),
			byte_tag("Scenario Sky Index"),
			byte_tag("Media Index"),
			byte_tag("Scenario Visible Sky Index"),
			byte_tag("Scenario Atmospheric Fog Index"),
			byte_tag("Planar Fog Designator"),
			byte_tag("Visible Fog Plane Index"),
			short_tag("Background Sound Index"),
			short_tag("Sound Environment Index"),
			short_tag("Weather Index"),
			short_tag("Transition Structure BSP"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Flags"),
			short_tag("Unknown"),
			block_tag("Predicted Resources",
			{
				short_tag("Type"),
				short_tag("Resource Index"),
				tagref_tag("Tag Index"),
			}),
			block_tag("Portals",
			{
				short_tag("Portal Index"),
			}),
			long_tag("Checksum From Structure"),
			block_tag("Instanced Geometry Indeces",
			{
				short_tag("Instanced Geometry Index"),
			}),
			block_tag("Index Reorder Table",
			{
				short_tag("Index"),
			}),
			undefined_tag("Collision MOPP Codes", 9999),
		}),
		block_tag("Materials",
		{
			undefined_tag("Old Shader", 9999),
			undefined_tag("Shader", 9999),
			block_tag("Properties",
			{
				short_tag("Type"),
				short_tag("Int Value"),
				long_tag("Real Value"),
			}),
			undefined_tag("Unknown", 9999),
			byte_tag("Breakable Surface Index"),
			byte_tag("Unknown"),
			byte_tag("Unknown"),
			byte_tag("Unknown"),
		}),
		block_tag("Sky Owner Cluster",
		{
			short_tag("Cluster Owner"),
		}),
		block_tag("Conveyor Surfaces",
		{
			long_tag("U i"),
			long_tag("U j"),
			long_tag("U k"),
			long_tag("V i"),
			long_tag("V j"),
			long_tag("V k"),
		}),
		block_tag("Breakable Surfaces",
		{
			short_tag("Instanced Geometry Instance"),
			short_tag("Breakable Surface Index"),
			long_tag("Centroid X"),
			long_tag("Centroid Y"),
			long_tag("Centroid Z"),
			long_tag("Radius"),
			long_tag("Collision Surface Index"),
		}),
		block_tag("Pathfinding Data",
		{
			block_tag("Sectors",
			{
				short_tag("Pathfinding Sector Flags"),
				short_tag("Hint Index"),
				long_tag("First Link"),
			}),
			block_tag("Links",
			{
				short_tag("Vertex 1"),
				short_tag("Vertex 2"),
				short_tag("Link Flags"),
				short_tag("Hint Index"),
				short_tag("Forward Link"),
				short_tag("Reverse Link"),
				short_tag("Left Sector"),
				short_tag("Right Sector"),
			}),
			block_tag("Refs",
			{
				long_tag("Node Ref Or Sector Ref"),
			}),
			block_tag("BSP 2D Nodes",
			{
				long_tag("Plane i"),
				long_tag("Plane j"),
				long_tag("Plane d"),
				short_tag("Left Child"),
				short_tag("Right Child"),
				short_tag("Unknown"),
				short_tag("Unknown"),
			}),
			block_tag("Surface Flags",
			{
				long_tag("Flags"),
			}),
			block_tag("Vertices",
			{
				long_tag("Point X"),
				long_tag("Point Y"),
				long_tag("Point Z"),
			}),
			block_tag("Object Refs",
			{
				short_tag("Flags"),
				short_tag("Unknown"),
				long_tag("First Sector"),
				long_tag("Last Sector"),
				block_tag("BSPs",
				{
					long_tag("BSP Reference"),
					long_tag("First Sector"),
					long_tag("Last Sector"),
					short_tag("Node Index"),
					short_tag("Unknown"),
				}),
				block_tag("Nodes",
				{
					short_tag("Reference Frame Index"),
					undefined_tag("Projection Axis", 9999),
					byte_tag("Projection Sign"),
				}),
			}),
			block_tag("Pathfinding Hints",
			{
				short_tag("Hint Type"),
				short_tag("Next Hint Index"),
				short_tag("Hint Data 0"),
				short_tag("Hint Data 1"),
				short_tag("Hint Data 2"),
				short_tag("Hint Data 3"),
				short_tag("Hint Data 4"),
				short_tag("Hint Data 5"),
				short_tag("Hint Data 6"),
				short_tag("Hint Data 7"),
			}),
			block_tag("Instanced Geometry Refs",
			{
				short_tag("Pathfinding Object Index"),
				short_tag("Unknown"),
			}),
			long_tag("Structure Checksum"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("User Placed Hints",
			{
				block_tag("Point Geometry",
				{
					long_tag("Point X"),
					long_tag("Point Y"),
					long_tag("Point Z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
				}),
				block_tag("Ray Geometry",
				{
					long_tag("Point X"),
					long_tag("Point Y"),
					long_tag("Point Z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
					undefined_tag("Vector i", 9999),
					undefined_tag("Vector j", 9999),
					undefined_tag("Vector k", 9999),
				}),
				block_tag("Line Segment Geometry",
				{
					undefined_tag("Flags", 9999),
					long_tag("Point 0 X"),
					long_tag("Point 0 Y"),
					long_tag("Point 0 Z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
					long_tag("Point 1 X"),
					long_tag("Point 1 Y"),
					long_tag("Point 1 Z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
				}),
				block_tag("Parallelogram Geometry",
				{
					undefined_tag("Flags", 9999),
					long_tag("Point 0 X"),
					long_tag("Point 0 Y"),
					long_tag("Point 0 Z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
					long_tag("Point 1 X"),
					long_tag("Point 1 Y"),
					long_tag("Point 1 Z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
					long_tag("Point 2 X"),
					long_tag("Point 2 Y"),
					long_tag("Point 2 Z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
					long_tag("Point 3 X"),
					long_tag("Point 3 Y"),
					long_tag("Point 3 Z"),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
				}),
				block_tag("Polygon Geometry",
				{
					undefined_tag("Flags", 9999),
					block_tag("Points",
					{
						long_tag("Point X"),
						long_tag("Point Y"),
						long_tag("Point Z"),
						short_tag("Reference Frame"),
						short_tag("Unknown"),
					}),
					undefined_tag("Unknown", 9999),
				}),
				block_tag("Jump Hints",
				{
					short_tag("Flags"),
					short_tag("Geometry Index"),
					short_tag("Force Jump Height"),
					short_tag("Control Flags"),
				}),
				block_tag("Climb Hints",
				{
					short_tag("Flags"),
					short_tag("Geometry Index"),
				}),
				block_tag("Well Hints",
				{
					undefined_tag("Flags", 9999),
					block_tag("Points",
					{
						short_tag("Type"),
						short_tag("Unknown"),
						undefined_tag("Point", 9999),
						short_tag("Reference Frame"),
						short_tag("Unknown"),
						long_tag("Sector Index"),
						undefined_tag("Normal", 9999),
					}),
				}),
				block_tag("Flight Hints",
				{
					block_tag("Points",
					{
						undefined_tag("Point", 9999),
					}),
				}),
			}),
		}),
		block_tag("Pathfinding Edges",
		{
			byte_tag("Midpoint"),
		}),
		block_tag("Background Sound Palette",
		{
			string_tag("Name"),
			undefined_tag("Background Sound", 9999),
			undefined_tag("Inside Cluster Sound", 9999),
			long_tag("Cutoff Distance"),
			undefined_tag("Scale Flags", 9999),
			long_tag("Interior Scale"),
			long_tag("Portal Scale"),
			long_tag("Exterior Scale"),
			long_tag("Interpolation Speed"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Sound Environment Palette",
		{
			string_tag("Name"),
			undefined_tag("Sound Environment", 9999),
			long_tag("Cutoff Distance"),
			long_tag("Interpolation Speed"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("Sound PAS Data", 9999),
		block_tag("Markers",
		{
			string_tag("Name"),
			long_tag("Rotation i"),
			long_tag("Rotation j"),
			long_tag("Rotation k"),
			long_tag("Rotation w"),
			long_tag("Position X"),
			long_tag("Position Y"),
			long_tag("Position Z"),
		}),
		block_tag("Runtime Decals",
		{
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Environment Object Palette",
		{
			undefined_tag("Definition", 9999),
			undefined_tag("Model", 9999),
			undefined_tag("Object Type", 9999),
		}),
		block_tag("Environment Objects",
		{
			string_tag("Name"),
			long_tag("Rotation i"),
			long_tag("Rotation j"),
			long_tag("Rotation k"),
			long_tag("Rotation w"),
			long_tag("Translation X"),
			long_tag("Translation Y"),
			long_tag("Translation Z"),
			short_tag("Palette Index"),
			short_tag("Unknown"),
			long_tag("Unique ID"),
			string_tag("Exported Object Type"),
			string_tag("Scenario Object Name"),
		}),
		undefined_tag("Lightmaps", 9999),
		undefined_tag("Lightmaps", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Leaf Map Leaves", 9999),
		undefined_tag("Leaf Map Leaves", 9999),
		undefined_tag("Leaf Map Connections", 9999),
		undefined_tag("Leaf Map Connections", 9999),
		undefined_tag("Errors", 9999),
		undefined_tag("Errors", 9999),
		undefined_tag("Precomputed Lighting", 9999),
		undefined_tag("Precomputed Lighting", 9999),
		block_tag("Instanced Geometry Definitions",
		{
			undefined_tag("Total Vertex Count", 9999),
			undefined_tag("Total Triangle Count", 9999),
			undefined_tag("Total Part Count", 9999),
			undefined_tag("Shadow-Casting Triangle Count", 9999),
			undefined_tag("Shadow-Casting Part Count", 9999),
			undefined_tag("Opaque Point Count", 9999),
			undefined_tag("Opaque Vertex Count", 9999),
			undefined_tag("Opaque Part Count", 9999),
			undefined_tag("Opaque Max Nodes/Vertex", 9999),
			undefined_tag("Shadow-Casting Rigid Triangle Count", 9999),
			short_tag("Geometry Classification"),
			short_tag("Geometry Compression Flags"),
			block_tag("Compression Info",
			{
				long_tag("Position Bounds X min"),
				long_tag("Position Bounds X max"),
				long_tag("Position Bounds Y min"),
				long_tag("Position Bounds Y max"),
				long_tag("Position Bounds Z min"),
				long_tag("Position Bounds Z max"),
				long_tag("Texcoord Bounds X min"),
				long_tag("Texcoord Bounds X max"),
				long_tag("Texcoord Bounds Y min"),
				long_tag("Texcoord Bounds Y max"),
				long_tag("Secondary Texcoord Bounds X min"),
				long_tag("Secondary Texcoord Bounds X max"),
				long_tag("Secondary Texcoord Bounds Y min"),
				long_tag("Secondary Texcoord Bounds Y max"),
			}),
			undefined_tag("Hardware Node Count", 9999),
			undefined_tag("Node Map Size", 9999),
			undefined_tag("Software Plane Sount", 9999),
			undefined_tag("Total Subpart Count", 9999),
			short_tag("Section Lighting Flags"),
			long_tag("Resource Block Offset"),
			undefined_tag("Resource Block Size", 9999),
			undefined_tag("Section Data Size", 9999),
			undefined_tag("Resource Data Size", 9999),
			block_tag("Resources",
			{
				byte_tag("Type"),
				byte_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Primary Locator"),
				short_tag("Secondary Locator"),
				undefined_tag("Resource Data Size", 9999),
				undefined_tag("Resource Data Offset", 9999),
			}),
			tagref_tag("Owner Tag"),
			short_tag("Owner Tag Section Offset"),
			short_tag("Unknown"),
			long_tag("Unknown"),
			block_tag("Render Data",
			{
				block_tag("Parts",
				{
					short_tag("Type"),
					short_tag("Flags"),
					short_tag("Material Index"),
					short_tag("Strip Start Index"),
					short_tag("Strip Length"),
					short_tag("First Subpart Index"),
					short_tag("Subpart Count"),
					byte_tag("Max Nodes/Vertex"),
					byte_tag("Contributing Compound Node Count"),
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("LOD Mipmap Magic"),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				block_tag("Subparts",
				{
					short_tag("Indices Start Index"),
					short_tag("Indices Length"),
					short_tag("Visibility Bounds Index"),
					short_tag("Part Index"),
				}),
				block_tag("Visibility Bounds",
				{
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					long_tag("Radius"),
					byte_tag("Node 0"),
					byte_tag("Unknown"),
					byte_tag("Unknown"),
					byte_tag("Unknown"),
				}),
				block_tag("Raw Vertices",
				{
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Use New Node Indices"),
					long_tag("Adjusted Compound Node Index"),
					long_tag("Texcoord X"),
					long_tag("Texcoord Y"),
					long_tag("Normal i"),
					long_tag("Normal j"),
					long_tag("Normal k"),
					long_tag("Binormal i"),
					long_tag("Binormal j"),
					long_tag("Binormal k"),
					long_tag("Tangent i"),
					long_tag("Tangent j"),
					long_tag("Tangent k"),
					long_tag("Anisotropic Binormal i"),
					long_tag("Anisotropic Binormal j"),
					long_tag("Anisotropic Binormal k"),
					long_tag("Secondary Texcoord X"),
					long_tag("Secondary Texcoord Y"),
					undefined_tag("Primary Lightmap Color", 9999),
					long_tag("Primary Lightmap Texcoord X"),
					long_tag("Primary Lightmap Texcoord Y"),
					long_tag("Primary Lightmap Incident Direction i"),
					long_tag("Primary Lightmap Incident Direction j"),
					long_tag("Primary Lightmap Incident Direction k"),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				block_tag("Strip Indices",
				{
					short_tag("Index"),
				}),
				undefined_tag("Visibility MOPP Codes", 9999),
				block_tag("MOPP Reorder Table",
				{
					short_tag("Index"),
				}),
				block_tag("Vertex Buffers",
				{
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Index Reorder Table",
			{
				short_tag("Index"),
			}),
			long_tag("Checksum"),
			long_tag("Bounding Sphere X"),
			long_tag("Bounding Sphere Y"),
			long_tag("Bounding Sphere Z"),
			long_tag("Bounding Sphere Radius"),
			block_tag("BSP 3D Nodes",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Planes",
			{
				long_tag("Plane i"),
				long_tag("Plane j"),
				long_tag("Plane k"),
				long_tag("Plane d"),
			}),
			block_tag("Leaves",
			{
				undefined_tag("Flags", 9999),
				undefined_tag("BSP 2D Reference Count", 9999),
				short_tag("First BSP 2D Reference"),
			}),
			block_tag("BSP 2D References",
			{
				short_tag("Plane"),
				short_tag("BSP 2D Node"),
			}),
			block_tag("BSP 2D Nodes",
			{
				long_tag("Plane i"),
				long_tag("Plane j"),
				long_tag("Plane d"),
				short_tag("Left Child"),
				short_tag("Right Child"),
			}),
			block_tag("Surfaces",
			{
				short_tag("Plane"),
				short_tag("First Edge"),
				undefined_tag("Flags", 9999),
				undefined_tag("Breakable Surface Index", 9999),
				short_tag("Material Index"),
			}),
			block_tag("Edges",
			{
				short_tag("Start Vertex"),
				short_tag("End Vertex"),
				short_tag("Forward Edge"),
				short_tag("Backward Edge"),
				short_tag("Left Surface"),
				short_tag("Right Surface"),
			}),
			block_tag("Vertices",
			{
				long_tag("Point X"),
				long_tag("Point Y"),
				long_tag("Point Z"),
				short_tag("First Edge"),
				short_tag("Unknown"),
			}),
			block_tag("BSP Physics",
			{
				undefined_tag("Runtime Code Pointer", 9999),
				short_tag("Size"),
				short_tag("Count"),
				undefined_tag("User Data", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Center", 9999),
				long_tag("w Center"),
				undefined_tag("Half Extent", 9999),
				long_tag("w Half Extent"),
				tagref_tag("Runtime Model Tag"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Runtime Code Pointer", 9999),
				short_tag("Size"),
				short_tag("Count"),
				undefined_tag("User Data", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Runtime Code Pointer", 9999),
				short_tag("Size"),
				short_tag("Count"),
				undefined_tag("User Data", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("MOPP Code Data", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Render Leaves",
			{
				short_tag("Cluster"),
				short_tag("Surface Reference Count"),
				long_tag("First Surface Reference Index"),
			}),
			block_tag("Surface References",
			{
				short_tag("Strip Index"),
				short_tag("Lightmap Triangle"),
				long_tag("BSP Node Index"),
			}),
		}),
		block_tag("Instanced Geometry Instances",
		{
			long_tag("Scale"),
			long_tag("Forward i"),
			long_tag("Forward j"),
			long_tag("Forward k"),
			long_tag("Left i"),
			long_tag("Left j"),
			long_tag("Left k"),
			long_tag("Up i"),
			long_tag("Up j"),
			long_tag("Up k"),
			long_tag("Position X"),
			long_tag("Position Y"),
			long_tag("Position Z"),
			short_tag("Instance Definition Index"),
			short_tag("Flags"),
			long_tag("Checksum"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Name", 9999),
			short_tag("Pathfinding Policy"),
			short_tag("Lightmapping Policy"),
		}),
		block_tag("Ambience Sound Clusters",
		{
			short_tag("Unknown"),
			short_tag("Unknown"),
			block_tag("Enclosing Portal Designators",
			{
				short_tag("Portal Designator"),
			}),
			block_tag("Interior Cluster Indices",
			{
				short_tag("Interior Cluster Index"),
			}),
		}),
		block_tag("Reverb Sound Clusters",
		{
			short_tag("Unknown"),
			short_tag("Unknown"),
			block_tag("Enclosing Portal Designators",
			{
				short_tag("Portal Designator"),
			}),
			block_tag("Interior Cluster Indices",
			{
				short_tag("Interior Cluster Index"),
			}),
		}),
		block_tag("Transparent Planes",
		{
			short_tag("Section Index"),
			short_tag("Part Index"),
			long_tag("Plane i"),
			long_tag("Plane j"),
			long_tag("Plane k"),
			long_tag("Plane d"),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Vehicle Sperical Limit Radius"),
		long_tag("Vehicle Sperical Limit X"),
		long_tag("Vehicle Sperical Limit Y"),
		long_tag("Vehicle Sperical Limit Z"),
		block_tag("Debug Info",
		{
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("Clusters",
			{
				short_tag("Errors"),
				short_tag("Warnings"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Lines",
				{
					short_tag("Type"),
					short_tag("Code"),
					short_tag("Pad Thai"),
					short_tag("Unknown"),
					long_tag("Point 0 X"),
					long_tag("Point 0 Y"),
					long_tag("Point 0 Z"),
					long_tag("Point 1 X"),
					long_tag("Point 1 Y"),
					long_tag("Point 1 Z"),
				}),
				block_tag("Fog Plane Indices",
				{
					long_tag("Index"),
				}),
				block_tag("Visible Fog Plane Indices",
				{
					long_tag("Index"),
				}),
				block_tag("Visible Fog Omission Cluster Indices",
				{
					long_tag("Index"),
				}),
				block_tag("Containing Fog Zone Indices",
				{
					long_tag("Index"),
				}),
			}),
			block_tag("Fog Planes",
			{
				long_tag("Fog Zone Index"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				long_tag("Connected Plane Designator"),
				block_tag("Lines",
				{
					short_tag("Type"),
					short_tag("Code"),
					short_tag("Pad Thai"),
					short_tag("Unknown"),
					long_tag("Point 0 X"),
					long_tag("Point 0 Y"),
					long_tag("Point 0 Z"),
					long_tag("Point 1 X"),
					long_tag("Point 1 Y"),
					long_tag("Point 1 Z"),
				}),
				block_tag("Intersected Cluster Indices",
				{
					long_tag("Index"),
				}),
				block_tag("Infinite Extent Cluster Indices",
				{
					long_tag("Index"),
				}),
			}),
			block_tag("Fog Zones",
			{
				long_tag("Media Index: Scenario Fog Plane"),
				long_tag("Base Fog Plane Index"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				block_tag("Lines",
				{
					short_tag("Type"),
					short_tag("Code"),
					short_tag("Pad Thai"),
					short_tag("Unknown"),
					long_tag("Point 0 X"),
					long_tag("Point 0 Y"),
					long_tag("Point 0 Z"),
					long_tag("Point 1 X"),
					long_tag("Point 1 Y"),
					long_tag("Point 1 Z"),
				}),
				block_tag("Immersed Cluster Indices",
				{
					long_tag("Index"),
				}),
				block_tag("Bounding Fog Plane Indices",
				{
					long_tag("Index"),
				}),
				block_tag("Collision Fog Plane Indices",
				{
					long_tag("Index"),
				}),
			}),
		}),
		undefined_tag("Decorators", 9999),
		undefined_tag("MOPP Codes", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("MOPP Bounds Min X"),
		long_tag("MOPP Bounds Min Y"),
		long_tag("MOPP Bounds Min Z"),
		long_tag("MOPP Bounds Max X"),
		long_tag("MOPP Bounds Max Y"),
		long_tag("MOPP Bounds Max Z"),
		undefined_tag("Breakable Surface MOPP Codes", 9999),
		block_tag("Breakable Surface Key Table",
		{
			short_tag("Instance Geometry Index"),
			short_tag("Breakable Surface Index"),
			long_tag("Seed Surface Index"),
			long_tag("X0"),
			long_tag("X1"),
			long_tag("Y0"),
			long_tag("Y1"),
			long_tag("Z0"),
			long_tag("Z1"),
		}),
		block_tag("Water Definitions",
		{
			undefined_tag("Shader", 9999),
			block_tag("Section",
			{
				block_tag("Parts",
				{
					short_tag("Type"),
					short_tag("Flags"),
					short_tag("Material Index"),
					short_tag("Strip Start Index"),
					short_tag("Strip Length"),
					short_tag("First Subpart Index"),
					short_tag("Subpart Count"),
					byte_tag("Max Nodes/Vertex"),
					byte_tag("Contributing Compound Node Count"),
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					byte_tag("Node Index"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("LOD Mipmap Magic"),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				block_tag("Subparts",
				{
					short_tag("Indices Start Index"),
					short_tag("Indices Length"),
					short_tag("Visibility Bounds Index"),
					short_tag("Part Index"),
				}),
				block_tag("Visibility Bounds",
				{
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					long_tag("Radius"),
					byte_tag("Node 0"),
					byte_tag("Unknown"),
					byte_tag("Unknown"),
					byte_tag("Unknown"),
				}),
				block_tag("Raw Vertices",
				{
					long_tag("Position X"),
					long_tag("Position Y"),
					long_tag("Position Z"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Index (Old)"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Weight"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Node Index (New)"),
					long_tag("Use New Node Indices"),
					long_tag("Adjusted Compound Node Index"),
					long_tag("Texcoord X"),
					long_tag("Texcoord Y"),
					long_tag("Normal i"),
					long_tag("Normal j"),
					long_tag("Normal k"),
					long_tag("Binormal i"),
					long_tag("Binormal j"),
					long_tag("Binormal k"),
					long_tag("Tangent i"),
					long_tag("Tangent j"),
					long_tag("Tangent k"),
					long_tag("Anisotropic Binormal i"),
					long_tag("Anisotropic Binormal j"),
					long_tag("Anisotropic Binormal k"),
					long_tag("Secondary Texcoord X"),
					long_tag("Secondary Texcoord Y"),
					undefined_tag("Primary Lightmap Color", 9999),
					long_tag("Primary Lightmap Texcoord X"),
					long_tag("Primary Lightmap Texcoord Y"),
					long_tag("Primary Lightmap Incident Direction i"),
					long_tag("Primary Lightmap Incident Direction j"),
					long_tag("Primary Lightmap Incident Direction k"),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				block_tag("Strip Indices",
				{
					short_tag("Index"),
				}),
				undefined_tag("Visibility MOPP Codes", 9999),
				block_tag("MOPP Reorder Table",
				{
					short_tag("Index"),
				}),
				block_tag("Vertex Buffers",
				{
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				undefined_tag("Unknown", 9999),
			}),
			long_tag("Resource Block Offset"),
			undefined_tag("Resource Block Size", 9999),
			undefined_tag("Section Data Size", 9999),
			undefined_tag("Resource Data Size", 9999),
			block_tag("Resources",
			{
				byte_tag("Type"),
				byte_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Primary Locator"),
				short_tag("Secondary Locator"),
				undefined_tag("Resource Data Size", 9999),
				undefined_tag("Resource Data Offset", 9999),
			}),
			tagref_tag("Owner Tag"),
			short_tag("Owner Tag Section Offset"),
			short_tag("Unknown"),
			long_tag("Unknown"),
			undefined_tag("Sun Spot Color", 9999),
			undefined_tag("Reflection Tint", 9999),
			undefined_tag("Refraction Tint", 9999),
			undefined_tag("Horizon Color", 9999),
			long_tag("Sun Specular Power"),
			long_tag("Reflection Bump Scale"),
			long_tag("Refraction Bump Scale"),
			long_tag("Fresnel Scale"),
			long_tag("Sun Dir Heading"),
			long_tag("Sun Dir Pitch"),
			long_tag("FOV"),
			long_tag("Aspect"),
			long_tag("Height"),
			long_tag("Farz"),
			long_tag("Rotate Offset"),
			long_tag("Center i"),
			long_tag("Center j"),
			long_tag("Extents i"),
			long_tag("Extents j"),
			long_tag("Fog Near"),
			long_tag("Fog Far"),
			long_tag("Dynamic Height Bias"),
		}),
		block_tag("Portal Device Mapping",
		{
			block_tag("Device Portal Association",
			{
				long_tag("Unique ID"),
				short_tag("Origin BSP Index"),
				byte_tag("Type"),
				byte_tag("Source"),
				short_tag("First Game Potal Index"),
				short_tag("Game Portal Count"),
			}),
			block_tag("Game Portal To Portal Map",
			{
				short_tag("Portal Index"),
			}),
		}),
		block_tag("Audibility",
		{
			long_tag("Door Portal Count"),
			long_tag("Cluster Distance Bounds min"),
			long_tag("Cluster Distance Bounds max"),
			block_tag("Encoded Door PAS",
			{
				long_tag("Unknown"),
			}),
			block_tag("Cluster Door Portal Encoded PAS",
			{
				long_tag("Unknown"),
			}),
			block_tag("AI Deafening PAS",
			{
				long_tag("Unknown"),
			}),
			block_tag("Cluster Distances",
			{
				byte_tag("Unknown"),
			}),
			block_tag("Machine Door Mapping",
			{
				byte_tag("Machine Door Index"),
			}),
		}),
		block_tag("Object Fake Lightprobes",
		{
			long_tag("Unique ID"),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			undefined_tag("Ambient", 9999),
			long_tag("Shadow Direction i"),
			long_tag("Shadow Direction j"),
			long_tag("Shadow Direction k"),
			long_tag("Lighting Accuracy"),
			long_tag("Shadow Opacity"),
			undefined_tag("Primary Direction Color", 9999),
			long_tag("Primary Direction i"),
			long_tag("Primary Direction j"),
			long_tag("Primary Direction k"),
			undefined_tag("Secondary Direction Color", 9999),
			long_tag("Secondary Direction i"),
			long_tag("Secondary Direction j"),
			long_tag("Secondary Direction k"),
			short_tag("SH Index"),
			short_tag("Unknown"),
		}),
		block_tag("Decorators",
		{
			long_tag("Grid Origin X"),
			long_tag("Grid Origin Y"),
			long_tag("Grid Origin Z"),
			long_tag("Cell Count Per Dimension"),
			block_tag("Cache Blocks",
			{
				long_tag("Resource Block Offset"),
				undefined_tag("Resource Block Size", 9999),
				undefined_tag("Section Data Size", 9999),
				undefined_tag("Resource Data Size", 9999),
				block_tag("Resources",
				{
					byte_tag("Type"),
					byte_tag("Unknown"),
					short_tag("Unknown"),
					short_tag("Primary Locator"),
					short_tag("Secondary Locator"),
					undefined_tag("Resource Data Size", 9999),
					undefined_tag("Resource Data Offset", 9999),
				}),
				tagref_tag("Owner Tag"),
				short_tag("Owner Tag Section Offset"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				block_tag("Cache Block Data",
				{
					block_tag("Placements",
					{
						long_tag("Internal Data 1"),
						long_tag("Compressed Position"),
						undefined_tag("Tint Color", 9999),
						undefined_tag("Lightmap Color", 9999),
						long_tag("Compressed Light Direction"),
						long_tag("Compressed Light 2 Direction"),
					}),
					block_tag("Decal Vertices",
					{
						long_tag("Position X"),
						long_tag("Position Y"),
						long_tag("Position Z"),
						long_tag("Texcoord 0 X"),
						long_tag("Texcoord 0 Y"),
						long_tag("Texcoord 1 X"),
						long_tag("Texcoord 1 Y"),
						undefined_tag("Color", 9999),
					}),
					block_tag("Decal Indices",
					{
						short_tag("Index"),
					}),
					undefined_tag("Decal Vertex Buffer", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					block_tag("Sprite Vertices",
					{
						undefined_tag("Position", 9999),
						undefined_tag("Offset", 9999),
						undefined_tag("Axis", 9999),
						undefined_tag("Texcoord", 9999),
						undefined_tag("Color", 9999),
					}),
					block_tag("Sprite Indices",
					{
						short_tag("Index"),
					}),
					undefined_tag("Sprite Vertex Buffer", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
					undefined_tag("Unknown", 9999),
				}),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Groups",
			{
				byte_tag("Decorator Set"),
				byte_tag("Decorator Type"),
				byte_tag("Shader Index"),
				byte_tag("Compressed Radius"),
				short_tag("Cluster Index"),
				short_tag("Cache Block Index"),
				short_tag("Decorator Start Index"),
				short_tag("Decorator Count"),
				short_tag("Vertex Start Offset"),
				short_tag("Vertex Count"),
				short_tag("Index Start Offset"),
				short_tag("Index Count"),
				long_tag("Compressed Bounding Center"),
			}),
			block_tag("Cells",
			{
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Child Index"),
				short_tag("Cache Block Index"),
				short_tag("Group Count"),
				long_tag("Group Start Index"),
			}),
			block_tag("Decals",
			{
				byte_tag("Decorator Set Index"),
				byte_tag("Decorator Class"),
				byte_tag("Decorator Permutation"),
				byte_tag("Sprite Index"),
				long_tag("Position X"),
				long_tag("Position Y"),
				long_tag("Position Z"),
				long_tag("Left i"),
				long_tag("Left j"),
				long_tag("Left k"),
				long_tag("Up i"),
				long_tag("Up j"),
				long_tag("Up k"),
				long_tag("Extents i"),
				long_tag("Extents j"),
				long_tag("Extents k"),
				long_tag("Previous Position X"),
				long_tag("Previous Position Y"),
				long_tag("Previous Position Z"),
			}),
		}),
	});
};
