#include "scnr.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* scnr_group = new tag_collection(
	"scnr",
	{
		
		undefined_tag("Do Not Use", 9999),
		block_tag("Skies",
		{
			undefined_tag("Sky", 9999),
		}),
		short_tag("Map Type"),
		short_tag("Flags"),
		block_tag("@Child Scenarios",
		{
			undefined_tag("Child Scenario", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("Local North", 9999),
		block_tag("Predicted Resource",
		{
			short_tag("Type"),
			short_tag("Resource Index"),
			tagref_tag("Tag Index"),
		}),
		undefined_tag("Functions Block", 9999),
		undefined_tag("Functions Block", 9999),
		undefined_tag("Editor Scenario Data", 9999),
		block_tag("Comments",
		{
			undefined_tag("Position", 9999),
			undefined_tag("Type", 9999),
			string_tag("Name"),
			string_tag("Comment"),
		}),
		undefined_tag("Don't-Use Environment Objects Block", 9999),
		undefined_tag("Don't-Use Environment Objects Block", 9999),
		block_tag("Object Names",
		{
			string_tag("Name"),
			short_tag("Type"),
			short_tag("Placement Index"),
		}),
		block_tag("Scenery",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			undefined_tag("Variant Name", 9999),
			undefined_tag("Active Change Colors", 9999),
			undefined_tag("Primary Color", 9999),
			undefined_tag("Secondary Color", 9999),
			undefined_tag("Tertiary Color", 9999),
			undefined_tag("Quaternary Color", 9999),
			short_tag("Pathfinding Policy"),
			short_tag("Lightmapping Policy"),
			block_tag("Pathfinding References",
			{
				short_tag("BSP Index"),
				short_tag("Pathfinding Object Index"),
			}),
			short_tag("Valid Multiplayer Games"),
			short_tag("Unknown"),
		}),
		block_tag("Scenery Palette",
		{
			undefined_tag("Scenery", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Bipeds",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			undefined_tag("Variant Name", 9999),
			undefined_tag("Active Change Colors", 9999),
			undefined_tag("Primary Color", 9999),
			undefined_tag("Secondary Color", 9999),
			undefined_tag("Tertiary Color", 9999),
			undefined_tag("Quaternary Color", 9999),
			long_tag("Body Vitality"),
			undefined_tag("Flags", 9999),
		}),
		block_tag("Biped Palette",
		{
			undefined_tag("Biped", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Vehicles",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			undefined_tag("Variant Name", 9999),
			undefined_tag("Active Change Colors", 9999),
			undefined_tag("Primary Color", 9999),
			undefined_tag("Secondary Color", 9999),
			undefined_tag("Tertiary Color", 9999),
			undefined_tag("Quaternary Color", 9999),
			long_tag("Body Vitality"),
			undefined_tag("Flags", 9999),
		}),
		block_tag("Vehicle Palette",
		{
			undefined_tag("Vehicle", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Equipment",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			undefined_tag("Equipment Flags", 9999),
		}),
		block_tag("Equipment Palette",
		{
			undefined_tag("Equipment", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Weapons",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			undefined_tag("Variant Name", 9999),
			undefined_tag("Active Change Colors", 9999),
			undefined_tag("Primary Color", 9999),
			undefined_tag("Secondary Color", 9999),
			undefined_tag("Tertiary Color", 9999),
			undefined_tag("Quaternary Color", 9999),
			short_tag("Rounds Left"),
			short_tag("Rounds Loaded"),
			undefined_tag("Flags", 9999),
		}),
		block_tag("Weapon Palette",
		{
			undefined_tag("Weapon", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Device Groups",
		{
			string_tag("Name"),
			long_tag("Inital Value"),
			undefined_tag("Flags", 9999),
		}),
		block_tag("Machines",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			short_tag("Power Group"),
			short_tag("Position Group"),
			undefined_tag("Flags", 9999),
			undefined_tag("Flags", 9999),
			block_tag("Pathfinding References",
			{
				short_tag("BSP Index"),
				short_tag("Pathfinding Object Index"),
			}),
		}),
		block_tag("Machine Palette",
		{
			undefined_tag("Machine", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Controls",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			short_tag("Power Group"),
			short_tag("Position Group"),
			undefined_tag("Flags", 9999),
			undefined_tag("Flags", 9999),
			short_tag("Don't Touch This"),
			short_tag("Unknown"),
		}),
		block_tag("Control Palette",
		{
			undefined_tag("Control", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Light Fixtures",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			short_tag("Power Group"),
			short_tag("Position Group"),
			undefined_tag("Flags", 9999),
			long_tag("Color Red"),
			long_tag("Color Green"),
			long_tag("Color Blue"),
			long_tag("Intensity"),
			undefined_tag("Falloff Angle", 9999),
			undefined_tag("Cutoff Angle", 9999),
		}),
		block_tag("Light Fixtures Palette",
		{
			undefined_tag("Light Fixture", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Sound Scenery",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			undefined_tag("Volume Type", 9999),
			long_tag("Height"),
			undefined_tag("Override Distance Bounds", 9999),
			undefined_tag("Override Cone Angle Bounds", 9999),
			long_tag("Override Outer Cone Gain"),
		}),
		block_tag("Sound Scenery Palette",
		{
			undefined_tag("Sound Scenery", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Light Volumes",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			short_tag("Power Group"),
			short_tag("Position Group"),
			undefined_tag("Flags", 9999),
			short_tag("Type"),
			short_tag("Flags"),
			short_tag("Lightmap Type"),
			short_tag("Lightmap Flags"),
			long_tag("Lightmap Half Life"),
			long_tag("Lightmap Light Scale"),
			undefined_tag("Target Point", 9999),
			long_tag("Width"),
			long_tag("Height Scale"),
			undefined_tag("Field Of View", 9999),
			long_tag("Falloff Distance"),
			long_tag("Cutoff Distance"),
		}),
		block_tag("Light Volumes Palette",
		{
			undefined_tag("Light Volume", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Player Starting Profile",
		{
			string_tag("Name"),
			long_tag("Starting Health Damage"),
			long_tag("Starting Shield Damage"),
			undefined_tag("Primary Weapon", 9999),
			short_tag("Rounds Loaded"),
			short_tag("Rounds Total"),
			undefined_tag("Secondary Weapon", 9999),
			short_tag("Rounds Loaded"),
			short_tag("Rounds Total"),
			undefined_tag("Starting Frag Grenade Count", 9999),
			undefined_tag("Starting Plasma Grenade Count", 9999),
			undefined_tag("Starting Unused Grenade Count", 9999),
			undefined_tag("Starting Unused Grenade Count", 9999),
		}),
		block_tag("Player Starting Locations",
		{
			undefined_tag("Position", 9999),
			undefined_tag("Facing", 9999),
			short_tag("Team Designator"),
			short_tag("BSP Index"),
			short_tag("Game Type 1"),
			short_tag("Game Type 2"),
			short_tag("Game Type 3"),
			short_tag("Game Type 4"),
			short_tag("Spawn Type 1"),
			short_tag("Spawn Type 2"),
			short_tag("Spawn Type 3"),
			short_tag("Spawn Type 4"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("Campaign Player Type"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Kill Trigger Volumes",
		{
			undefined_tag("Name", 9999),
			short_tag("Object Name Index"),
			short_tag("Node Index"),
			undefined_tag("Node Name", 9999),
			undefined_tag("Forward", 9999),
			undefined_tag("Up", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Extents", 9999),
			long_tag("Unknown"),
			short_tag("Kill Trigger Volume Index"),
			short_tag("Unknown"),
		}),
		undefined_tag("Recorded Animations Block", 9999),
		undefined_tag("Recorded Animations Block", 9999),
		block_tag("Netgame Flags",
		{
			undefined_tag("Position", 9999),
			undefined_tag("Facing", 9999),
			short_tag("Type"),
			short_tag("Team Designator"),
			short_tag("Identifier"),
			short_tag("Flags"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Netgame Equipment",
		{
			undefined_tag("Flags", 9999),
			short_tag("Game Type 1"),
			short_tag("Game Type 2"),
			short_tag("Game Type 3"),
			short_tag("Game Type 4"),
			short_tag("Team Index"),
			short_tag("Spawn Time"),
			short_tag("Respawn On Empty Time"),
			short_tag("Respawn Timer Starts"),
			byte_tag("Classification"),
			byte_tag("Unknown"),
			byte_tag("Unknown"),
			byte_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Orientation", 9999),
			undefined_tag("Item/Vehicle Collection", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Starting Equipment",
		{
			undefined_tag("Starting Grenades", 9999),
			short_tag("Game Type 1"),
			short_tag("Game Type 2"),
			short_tag("Game Type 3"),
			short_tag("Game Type 4"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Item Collection 1", 9999),
			undefined_tag("Item Collection 2", 9999),
			undefined_tag("Item Collection 3", 9999),
			undefined_tag("Item Collection 4", 9999),
			undefined_tag("Item Collection 5", 9999),
			undefined_tag("Item Collection 6", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("BSP Switch Trigger Volumes",
		{
			short_tag("Trigger Volume Index"),
			short_tag("Source BSP Index"),
			short_tag("Destination BSP Index"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
		}),
		block_tag("Decals",
		{
			short_tag("Palette Index"),
			byte_tag("Yaw"),
			byte_tag("Pitch"),
			undefined_tag("Position", 9999),
		}),
		block_tag("Decal Palette",
		{
			undefined_tag("Decal", 9999),
		}),
		block_tag("Detail Object Collection Palette",
		{
			undefined_tag("Detail Object Collection", 9999),
		}),
		block_tag("Style Palette",
		{
			undefined_tag("Style", 9999),
		}),
		block_tag("Squad Groups",
		{
			string_tag("Name"),
			short_tag("Parent Index"),
			short_tag("Initial Order Index"),
		}),
		block_tag("Squads",
		{
			string_tag("Name"),
			undefined_tag("Flags", 9999),
			short_tag("Team"),
			short_tag("Parent Squad Group Index"),
			long_tag("Squad Delay Time"),
			short_tag("Normal Difficulty Count"),
			short_tag("Insane Difficulty Count"),
			short_tag("Major Upgrade"),
			short_tag("Unknown"),
			short_tag("Vehicle Type Index"),
			short_tag("Character Type Index"),
			short_tag("Initial Zone Index"),
			short_tag("Unknown"),
			short_tag("Initial Weapon Index"),
			short_tag("Initial Secondary Weapon Index"),
			short_tag("Grenade Type"),
			short_tag("Initial Order Index"),
			undefined_tag("Vehicle Variant", 9999),
			block_tag("Starting Loctations",
			{
				undefined_tag("Name", 9999),
				undefined_tag("Position", 9999),
				short_tag("Reference Frame"),
				short_tag("Unknown"),
				undefined_tag("Facing", 9999),
				undefined_tag("Flags", 9999),
				short_tag("Character Type Index"),
				short_tag("Initial Weapon Index"),
				short_tag("Initial Secondary Weapon Index"),
				short_tag("Unknown"),
				short_tag("Vehicle Type Index"),
				short_tag("Seat Type"),
				short_tag("Grenade Type"),
				short_tag("Swarm Count"),
				undefined_tag("Actor Variant Name", 9999),
				undefined_tag("Vehicle Variant Name", 9999),
				long_tag("Initial Movement Distance"),
				short_tag("Emitter Vehicle Index"),
				short_tag("Initial Movement Mode"),
				string_tag("Placement Script"),
				short_tag("Placement Script Index"),
				short_tag("Unknown"),
			}),
			string_tag("Placement Script"),
			short_tag("Placement Script Index"),
			short_tag("Unknown"),
		}),
		block_tag("Zones",
		{
			string_tag("Name"),
			undefined_tag("Flags", 9999),
			short_tag("Manual BSP Index"),
			short_tag("Unknown"),
			block_tag("Firing Positions",
			{
				undefined_tag("Position", 9999),
				short_tag("Reference Frame"),
				short_tag("Flags"),
				short_tag("Area Index"),
				short_tag("Cluster Index"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Normal", 9999),
			}),
			block_tag("Areas",
			{
				string_tag("Name"),
				undefined_tag("Area Flags", 9999),
				undefined_tag("Position", 9999),
				short_tag("Unknown"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				short_tag("Firing Position Start Index"),
				short_tag("Firing Position Count"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Unknown", 9999),
				byte_tag("Unknown"),
				byte_tag("Unknown"),
				byte_tag("Unknown"),
				byte_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Unknown", 9999),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				short_tag("Manual Reference Frame"),
				short_tag("Unknown"),
				block_tag("Flight Hints",
				{
					short_tag("Flight Hint Index"),
					short_tag("Point Index"),
				}),
			}),
		}),
		block_tag("Mission Scenes",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Flags", 9999),
			block_tag("Trigger Conditions",
			{
				short_tag("Combination Rule"),
				short_tag("Unknown"),
				block_tag("Triggers",
				{
					undefined_tag("Trigger Flags", 9999),
					short_tag("Trigger Index"),
					short_tag("Unknown"),
				}),
			}),
			block_tag("Roles",
			{
				undefined_tag("Name", 9999),
				short_tag("Group"),
				short_tag("Unknown"),
				block_tag("Role Variants",
				{
					undefined_tag("Variant Designation", 9999),
				}),
			}),
		}),
		block_tag("Character Palette",
		{
			undefined_tag("Character", 9999),
		}),
		undefined_tag("AI Pathfinding Data Block", 9999),
		undefined_tag("AI Pathfinding Data Block", 9999),
		undefined_tag("AI Animation References Block", 9999),
		undefined_tag("AI Animation References Block", 9999),
		undefined_tag("AI Script References Block", 9999),
		undefined_tag("AI Script References Block", 9999),
		undefined_tag("AI Recording References Block", 9999),
		undefined_tag("AI Recording References Block", 9999),
		undefined_tag("AI Conversations Block", 9999),
		undefined_tag("AI Conversations Block", 9999),
		undefined_tag("Script Syntax Data", 9999),
		undefined_tag("Script String Data", 9999),
		block_tag("Scripts",
		{
			string_tag("Name"),
			short_tag("Script Type"),
			short_tag("Return Type"),
			undefined_tag("Root Expression", 9999),
		}),
		block_tag("Globals",
		{
			string_tag("Name"),
			short_tag("Type"),
			short_tag("Unknown"),
			undefined_tag("Initialization Expression", 9999),
		}),
		block_tag("Script References",
		{
			undefined_tag("Reference", 9999),
		}),
		undefined_tag("Source Files Block", 9999),
		undefined_tag("Source Files Block", 9999),
		block_tag("Scripting Data",
		{
			block_tag("Point Sets",
			{
				string_tag("Name"),
				block_tag("Points",
				{
					string_tag("Name"),
					undefined_tag("Position", 9999),
					short_tag("Reference Frame"),
					short_tag("Unknown"),
					long_tag("Surface Index"),
					undefined_tag("Facing Direction y", 9999),
				}),
				short_tag("BSP Index"),
				short_tag("Manual Reference Frame"),
				undefined_tag("Flags", 9999),
			}),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Cutscene Flags",
		{
			undefined_tag("Unknown", 9999),
			string_tag("Name"),
			undefined_tag("Position", 9999),
			undefined_tag("Facing", 9999),
		}),
		block_tag("Cutscene Camera Points",
		{
			short_tag("Flags"),
			short_tag("Type"),
			string_tag("Name"),
			undefined_tag("Position", 9999),
			undefined_tag("Orientation", 9999),
			long_tag("Unknown"),
		}),
		block_tag("Cutscene Titles",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Text Bounds", 9999),
			short_tag("Justification"),
			short_tag("Font"),
			undefined_tag("Text Color", 9999),
			undefined_tag("Shadow Color", 9999),
			long_tag("Fade In Time"),
			long_tag("Up Time"),
			long_tag("Fade Out Time"),
		}),
		undefined_tag("Custom Object Names", 9999),
		undefined_tag("Chapter Title Text", 9999),
		undefined_tag("HUD Messages", 9999),
		block_tag("Structure BSPs",
		{
			undefined_tag("Structure BSP Offset", 9999),
			undefined_tag("Structure BSP Size", 9999),
			undefined_tag("Primary Magic Meta Offset", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Structure BSP", 9999),
			undefined_tag("Structure Lightmap", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Radiance Estimated Search Distance"),
			undefined_tag("Unknown", 9999),
			long_tag("Luminels Per World Unit"),
			long_tag("Output White Reference"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("Flags"),
			short_tag("Unknown"),
			short_tag("Default Sky"),
			short_tag("Unknown"),
		}),
		block_tag("Scenario Resources",
		{
			block_tag("References",
			{
				undefined_tag("Reference", 9999),
			}),
			block_tag("Script Source",
			{
				undefined_tag("Reference", 9999),
			}),
			block_tag("AI Resources",
			{
				undefined_tag("Reference", 9999),
			}),
		}),
		block_tag("Structure Physics",
		{
			undefined_tag("MOPP Code", 9999),
			block_tag("Environment Object Identifiers",
			{
				undefined_tag("Unique ID", 9999),
				short_tag("Origin BSP Index"),
				byte_tag("Type"),
				byte_tag("Source"),
			}),
			undefined_tag("Unknown", 9999),
			long_tag("MOPP Bounds min x"),
			long_tag("MOPP Bounds min y"),
			long_tag("MOPP Bounds min z"),
			long_tag("MOPP Bounds max x"),
			long_tag("MOPP Bounds max y"),
			long_tag("MOPP Bounds max z"),
		}),
		block_tag("Unit Seats Mapping",
		{
			tagref_tag("Unit"),
			undefined_tag("Seats", 9999),
		}),
		block_tag("Scenario Kill Triggers",
		{
			short_tag("Trigger Volume"),
		}),
		block_tag("Script Expressions",
		{
			undefined_tag("Salt", 9999),
			short_tag("Opcode"),
			short_tag("Value Type"),
			short_tag("Expression Type"),
			undefined_tag("Next Expression", 9999),
			undefined_tag("String Address", 9999),
			byte_tag("Value 00 (LSB)"),
			byte_tag("Value 01 Byte"),
			byte_tag("Value 02 Byte"),
			byte_tag("Value 03 (MSB)"),
		}),
		block_tag("Orders",
		{
			string_tag("Name"),
			short_tag("Style Index"),
			short_tag("Unknown"),
			undefined_tag("Flags", 9999),
			short_tag("Force Combat Status"),
			short_tag("Unknown"),
			string_tag("Entry Script"),
			short_tag("Script Index"),
			short_tag("Follow Squad Index"),
			long_tag("Follow Radius"),
			block_tag("Primary Area Set",
			{
				short_tag("Area Type"),
				short_tag("Unknown"),
				short_tag("Zone Index"),
				short_tag("Area Index"),
			}),
			block_tag("Secondary Area Set",
			{
				short_tag("Area Type"),
				short_tag("Unknown"),
				short_tag("Zone Index"),
				short_tag("Area Index"),
			}),
			block_tag("Secondary Set Trigger",
			{
				short_tag("Combination Rule"),
				short_tag("Dialogue Type"),
				block_tag("Triggers",
				{
					undefined_tag("Trigger Flags", 9999),
					short_tag("Trigger Index"),
					short_tag("Unknown"),
				}),
			}),
			block_tag("Special Movement",
			{
				undefined_tag("Special Movement 1", 9999),
			}),
			block_tag("Order Endings",
			{
				short_tag("Next Order Index"),
				short_tag("Combination Rule"),
				long_tag("Delay Time"),
				short_tag("Dialogue Type"),
				short_tag("Unknown"),
				block_tag("Triggers",
				{
					undefined_tag("Trigger Flags", 9999),
					short_tag("Trigger Index"),
					short_tag("Unknown"),
				}),
			}),
		}),
		block_tag("AI Triggers",
		{
			string_tag("Name"),
			undefined_tag("Trigger Flags", 9999),
			short_tag("Combination Rule"),
			short_tag("Unknown"),
			block_tag("Conditions",
			{
				short_tag("Rule Type"),
				short_tag("Squad"),
				short_tag("Squad Group"),
				short_tag("A"),
				long_tag("X"),
				short_tag("Trigger Volume"),
				short_tag("Unknown"),
				string_tag("Exit Condition Script"),
				short_tag("Exit Condition Script Index"),
				short_tag("Unknown"),
				undefined_tag("Flags", 9999),
			}),
		}),
		block_tag("Background Sound Palette",
		{
			string_tag("Name"),
			undefined_tag("Background Sound", 9999),
			undefined_tag("Inside Cluster Sound", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Cutoff Distance"),
			undefined_tag("Scale Flags", 9999),
			long_tag("Interior Scale"),
			long_tag("Portal Scale"),
			long_tag("Exterior Scale"),
			long_tag("Interpolation Speed"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Sound Environment Palette",
		{
			string_tag("Name"),
			undefined_tag("Sound Environment", 9999),
			long_tag("Cutoff Distance"),
			long_tag("Interpolation Speed"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Weather Palette",
		{
			string_tag("Name"),
			undefined_tag("Weather System", 9999),
			short_tag("Unknown"),
			short_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Wind", 9999),
			undefined_tag("Wind Direction", 9999),
			long_tag("Wind Magnitude"),
			undefined_tag("Unknown", 9999),
			string_tag("Wind Scale Function"),
		}),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		undefined_tag("Null Block", 9999),
		block_tag("Scenario Cluster Data",
		{
			undefined_tag("BSP", 9999),
			block_tag("Background Sounds",
			{
				short_tag("Palette Index"),
				short_tag("Unknown"),
			}),
			block_tag("Sound Environments",
			{
				short_tag("Palette Index"),
				short_tag("Unknown"),
			}),
			long_tag("BSP Checksum"),
			block_tag("Cluster Centroids",
			{
				undefined_tag("Centroid", 9999),
			}),
			block_tag("Weather Properties",
			{
				short_tag("Palette Index"),
				short_tag("Unknown"),
			}),
			block_tag("Atmospheric Fog Properties",
			{
				short_tag("Palette Index"),
				short_tag("Unknown"),
			}),
		}),
		long_tag("Object Salts 1"),
		long_tag("Object Salts 2"),
		long_tag("Object Salts 3"),
		long_tag("Object Salts 4"),
		long_tag("Object Salts 5"),
		long_tag("Object Salts 6"),
		long_tag("Object Salts 7"),
		long_tag("Object Salts 8"),
		long_tag("Object Salts 9"),
		long_tag("Object Salts 10"),
		long_tag("Object Salts 11"),
		long_tag("Object Salts 12"),
		long_tag("Object Salts 13"),
		long_tag("Object Salts 14"),
		long_tag("Object Salts 15"),
		long_tag("Object Salts 16"),
		long_tag("Object Salts 17"),
		long_tag("Object Salts 18"),
		long_tag("Object Salts 19"),
		long_tag("Object Salts 20"),
		long_tag("Object Salts 21"),
		long_tag("Object Salts 22"),
		long_tag("Object Salts 23"),
		long_tag("Object Salts 24"),
		long_tag("Object Salts 25"),
		long_tag("Object Salts 26"),
		long_tag("Object Salts 27"),
		long_tag("Object Salts 28"),
		long_tag("Object Salts 29"),
		long_tag("Object Salts 30"),
		long_tag("Object Salts 31"),
		long_tag("Object Salts 32"),
		block_tag("Spawn Data",
		{
			long_tag("Dynamic Spawn Lower Height"),
			long_tag("Dynamic Spawn Upper Height"),
			long_tag("Game Objective Reset Height"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			block_tag("Dynamic Spawn Overloads",
			{
				short_tag("Overload Type"),
				short_tag("Unknown"),
				long_tag("Inner Radius"),
				long_tag("Outer Radius"),
				long_tag("Weight"),
			}),
			block_tag("Static Respawn Zones",
			{
				undefined_tag("Name", 9999),
				undefined_tag("Relevant Team", 9999),
				undefined_tag("Relevant Games", 9999),
				undefined_tag("Flags", 9999),
				long_tag("Position x"),
				long_tag("Position y"),
				long_tag("Position z"),
				long_tag("Lower Height"),
				long_tag("Upper Height"),
				long_tag("Inner Radius"),
				long_tag("Outer Radius"),
				long_tag("Weight"),
			}),
			block_tag("Static Initial Spawn Zones",
			{
				undefined_tag("Name", 9999),
				undefined_tag("Relevant Team", 9999),
				undefined_tag("Relevant Games", 9999),
				undefined_tag("Flags", 9999),
				undefined_tag("Position", 9999),
				long_tag("Lower Height"),
				long_tag("Upper Height"),
				long_tag("Inner Radius"),
				long_tag("Outer Radius"),
				long_tag("Weight"),
			}),
		}),
		undefined_tag("Sound Effects Collection", 9999),
		block_tag("Crates",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
			undefined_tag("Variant Name", 9999),
			undefined_tag("Active Change Colors", 9999),
			undefined_tag("Primary Color", 9999),
			undefined_tag("Secondary Color", 9999),
			undefined_tag("Tertiary Color", 9999),
			undefined_tag("Quaternary Color", 9999),
		}),
		block_tag("Crate Palette",
		{
			undefined_tag("Crate", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("Global Lighting", 9999),
		block_tag("Atmospheric Fog Palette",
		{
			undefined_tag("Name", 9999),
			long_tag("Color Red"),
			long_tag("Color Green"),
			long_tag("Color Blue"),
			long_tag("Spread Distance"),
			undefined_tag("Unknown", 9999),
			long_tag("Maximum Density"),
			long_tag("Start Distance"),
			long_tag("Opaque Distance"),
			long_tag("Color Red"),
			long_tag("Color Green"),
			long_tag("Color Blue"),
			long_tag("Spread Distance"),
			undefined_tag("Unknown", 9999),
			long_tag("Maximum Density"),
			long_tag("Start Distance"),
			long_tag("Opaque Distance"),
			long_tag("Planar Color Red"),
			long_tag("Planar Color Green"),
			long_tag("Planar Color Blue"),
			long_tag("Planar Maximum Density"),
			long_tag("Planar Override Amount"),
			long_tag("Planar Minimum Distance Bias"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Patchy Color Red"),
			long_tag("Patchy Color Green"),
			long_tag("Patchy Color Blue"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Patchy Density min"),
			long_tag("Patchy Density max"),
			long_tag("Patchy Distance min"),
			long_tag("Patchy Distance max"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Patchy Fog", 9999),
			block_tag("Mixers",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Atmospheric Fog Source", 9999),
				undefined_tag("Interpolator", 9999),
				short_tag("Unknown"),
				short_tag("Unknown"),
			}),
			long_tag("Amount"),
			long_tag("Threshold"),
			long_tag("Brightness"),
			long_tag("Gamma Power"),
			short_tag("Camera Immersion Flags"),
			short_tag("Unknown"),
		}),
		block_tag("Planar Fog Palette",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Planar Fog", 9999),
			short_tag("Unknown"),
			short_tag("Unknown"),
		}),
		block_tag("Flocks",
		{
			short_tag("BSP Index"),
			short_tag("Unknown"),
			short_tag("Bounding Trigger Volume"),
			short_tag("Flags"),
			long_tag("Ecology Margin"),
			block_tag("Sources",
			{
				undefined_tag("Position", 9999),
				undefined_tag("Starting", 9999),
				long_tag("Radius"),
				long_tag("Weight"),
			}),
			block_tag("Sinks",
			{
				undefined_tag("Position", 9999),
				long_tag("Radius"),
			}),
			long_tag("Production Frequency"),
			undefined_tag("Scale", 9999),
			undefined_tag("Creature", 9999),
			undefined_tag("Boid Count", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			long_tag("Neighborhood Radius"),
			long_tag("Avoidance Radius"),
			long_tag("Forward Scale"),
			long_tag("Alignment Scale"),
			long_tag("Avoidance Scale"),
			long_tag("Leveling Force Scale"),
			long_tag("Sink Scale"),
			undefined_tag("Perception Angle", 9999),
			long_tag("Average Throttle"),
			long_tag("Maximum Throttle"),
			long_tag("Position Scale"),
			long_tag("Position Min Radius"),
			long_tag("Position Max Radius"),
			long_tag("Movement Weight Threshold"),
			long_tag("Danger Radius"),
			long_tag("Danger Scale"),
			undefined_tag("", 9999),
			long_tag("Random Offset Scale"),
			undefined_tag("Random Offset Period", 9999),
			undefined_tag("Flock Name", 9999),
		}),
		undefined_tag("Subtitles", 9999),
		undefined_tag("Decorators Block", 9999),
		undefined_tag("Decorators Block", 9999),
		block_tag("Creatures",
		{
			short_tag("Palette Index"),
			short_tag("Name Index"),
			undefined_tag("Placement Flags", 9999),
			undefined_tag("Position", 9999),
			undefined_tag("Rotation", 9999),
			long_tag("Scale"),
			short_tag("Transform Flags"),
			short_tag("Manual BSP Flags"),
			undefined_tag("Unique ID", 9999),
			short_tag("Origin BSP Index"),
			byte_tag("Type"),
			byte_tag("Source"),
			byte_tag("BSP Policy"),
			byte_tag("Unknown"),
			short_tag("Editor Folder"),
		}),
		block_tag("Creature Palette",
		{
			undefined_tag("Creature", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Decorator Palette",
		{
			undefined_tag("Decorator Set", 9999),
		}),
		block_tag("BSP Transition Volumes",
		{
			short_tag("Unknown"),
			short_tag("BSP Index Key"),
			short_tag("Trigger Volume Index"),
			short_tag("Unknown"),
		}),
		block_tag("Structure Lighting",
		{
			undefined_tag("BSP", 9999),
			block_tag("Lighting Points",
			{
				undefined_tag("Position", 9999),
			}),
		}),
		block_tag("Editor Folders",
		{
			long_tag("Parent Folder"),
			string_tag("Name"),
		}),
		block_tag("Level Data",
		{
			undefined_tag("Level Description", 9999),
			block_tag("Campaign Level Data",
			{
				long_tag("Campaign ID"),
				long_tag("Map ID"),
				undefined_tag("Bitmap", 9999),
				undefined_tag("English Name", 9999),
				undefined_tag("Japanese Name", 9999),
				undefined_tag("German Name", 9999),
				undefined_tag("French Name", 9999),
				undefined_tag("Spanish Name", 9999),
				undefined_tag("Italian Name", 9999),
				undefined_tag("Korean Name", 9999),
				undefined_tag("Chinese Name", 9999),
				undefined_tag("Portuguese Name", 9999),
				undefined_tag("English Description", 9999),
				undefined_tag("Japanese Description", 9999),
				undefined_tag("German Description", 9999),
				undefined_tag("French Description", 9999),
				undefined_tag("Spanish Description", 9999),
				undefined_tag("Italian Description", 9999),
				undefined_tag("Korean Description", 9999),
				undefined_tag("Chinese Description", 9999),
				undefined_tag("Portuguese Description", 9999),
			}),
			block_tag("Multiplayer",
			{
				long_tag("Map ID"),
				undefined_tag("Bitmap", 9999),
				undefined_tag("English Name", 9999),
				undefined_tag("Japanese Name", 9999),
				undefined_tag("German Name", 9999),
				undefined_tag("French Name", 9999),
				undefined_tag("Spanish Name", 9999),
				undefined_tag("Italian Name", 9999),
				undefined_tag("Korean Name", 9999),
				undefined_tag("Chinese Name", 9999),
				undefined_tag("Portuguese Name", 9999),
				undefined_tag("English Description", 9999),
				undefined_tag("Japanese Description", 9999),
				undefined_tag("German Description", 9999),
				undefined_tag("French Description", 9999),
				undefined_tag("Spanish Description", 9999),
				undefined_tag("Italian Description", 9999),
				undefined_tag("Korean Description", 9999),
				undefined_tag("Chinese Description", 9999),
				undefined_tag("Portuguese Description", 9999),
				string_tag("Path"),
				long_tag("Sort Order"),
				undefined_tag("Flags", 9999),
				byte_tag("Unknown"),
				byte_tag("Unknown"),
				byte_tag("Unknown"),
				undefined_tag("Max Teams None", 9999),
				undefined_tag("Max Teams CTF", 9999),
				undefined_tag("Max Teams Slayer", 9999),
				undefined_tag("Max Teams Oddball", 9999),
				undefined_tag("Max Teams KOTH", 9999),
				undefined_tag("Max Teams Race", 9999),
				undefined_tag("Max Teams Headhunter", 9999),
				undefined_tag("Max Teams Juggernaut", 9999),
				undefined_tag("Max Teams Territories", 9999),
				undefined_tag("Max Teams Assault", 9999),
				undefined_tag("Max Teams Stub 10", 9999),
				undefined_tag("Max Teams Stub 11", 9999),
				undefined_tag("Max Teams Stub 12", 9999),
				undefined_tag("Max Teams Stub 13", 9999),
				undefined_tag("Max Teams Stub 14", 9999),
				undefined_tag("Max Teams Stub 15", 9999),
			}),
		}),
		undefined_tag("Territory Location Names", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Mission Dialogue",
		{
			undefined_tag("Mission Dialogue", 9999),
		}),
		undefined_tag("Objectives", 9999),
		block_tag("Interpolators",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Accelerator Name", 9999),
			undefined_tag("Multiplier Name", 9999),
			undefined_tag("Function", 9999),
			short_tag("Unknown"),
			short_tag("Unknown"),
		}),
		undefined_tag("Shared References Block", 9999),
		undefined_tag("Shared References Block", 9999),
		block_tag("Screen Effect References",
		{
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Screen Effect", 9999),
			undefined_tag("Primary Input", 9999),
			undefined_tag("Secondary Input", 9999),
			short_tag("Unknown"),
			short_tag("Unknown"),
		}),
		block_tag("Simulation Definition Table",
		{
			undefined_tag("Tag", 9999),
		}),
	});
};
