#include "skin.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* skin_group = new tag_collection(
	"skin",
	{
		
		long_tag("Unknown"),
		undefined_tag("bitm", 9999),
		short_tag("Coord X Top arrow"),
		short_tag("Coord Y Top arrow"),
		short_tag("Coord X Bottom arrow"),
		short_tag("Coord Y Bottom arrow"),
		block_tag("Button effects",
		{
			long_tag("Unknown"),
			short_tag("Brightness"),
			short_tag("Brightness only once"),
			block_tag("Button switching effects",
			{
				long_tag("Unknown"),
				long_tag("Bitmap Flashing speed"),
				long_tag("Button shifting space"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
		}),
		block_tag("Buttons Text strings",
		{
			undefined_tag("Text options", 9999),
			short_tag("Animation Index"),
			short_tag("Intro Animation Delay Milliseconds"),
			short_tag("Unknown"),
			short_tag("Font Type"),
			long_tag("Alpha"),
			long_tag("Color Red"),
			long_tag("Color Green"),
			long_tag("Color Blue"),
			undefined_tag("Text Placement", 9999),
			undefined_tag("String name", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Button bitmaps",
		{
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Animation Index"),
			short_tag("Intro Animation Delay Milliseconds"),
			short_tag("Alpha transparence"),
			short_tag("Xbox live bitmap setting"),
			short_tag("Bitmap Placement coord X"),
			short_tag("Bitmap Placement coord Y"),
			long_tag("Horizontal bitmap scrolling speed"),
			long_tag("Unknown"),
			undefined_tag("bitm", 9999),
			short_tag("Bitmap Layer Level"),
			short_tag("Unknown"),
			long_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			undefined_tag("Bitmap color variation fuction", 9999),
			long_tag("Unknown"),
			long_tag("Unknown"),
		}),
		block_tag("Emblem",
		{
			undefined_tag("Flags", 9999),
			short_tag("Animation Index"),
			short_tag("Intro Animation Delay Milliseconds"),
			short_tag("Xbox live bitmap setting"),
			short_tag("Unknown"),
			undefined_tag("bitm", 9999),
			undefined_tag("shad", 9999),
			short_tag("Coord X"),
			short_tag("Coord Y"),
			short_tag("Coord X"),
			short_tag("Coord Y"),
		}),
		block_tag("Buttons Holder",
		{
			long_tag("Unknown"),
			undefined_tag("Skin", 9999),
			short_tag("Coord X"),
			short_tag("Coord Y"),
			undefined_tag("unknown", 9999),
			undefined_tag("Max Visible Buttons", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("Coord X"),
			short_tag("Coord Y"),
		}),
	});
};
