#include "sky.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* sky_group = new tag_collection(
	"sky",
	{
		
		undefined_tag("Render Model", 9999),
		undefined_tag("Animation Graph", 9999),
		undefined_tag("Flags", 9999),
		long_tag("Render model Scale"),
		long_tag("Movement Scale"),
		block_tag("Cube Map",
		{
			undefined_tag("Cube Map Reference", 9999),
			long_tag("Power Scale"),
		}),
		long_tag("Indoor Ambient Color R"),
		long_tag("Indoor Ambient Color G"),
		long_tag("Indoor Ambient Color B"),
		undefined_tag("Unknown", 9999),
		long_tag("Outdoor Ambient Color R"),
		long_tag("Outdoor Ambient Color G"),
		long_tag("Outdoor Ambient Color B"),
		undefined_tag("Unknown", 9999),
		long_tag("Fog Spread Distance"),
		block_tag("Atmospheric Fog",
		{
			long_tag("Color R"),
			long_tag("Color G"),
			long_tag("Color B"),
			long_tag("Maximum Density"),
			long_tag("Start Distance"),
			long_tag("Opaque Distnace"),
		}),
		block_tag("Secondary Fog",
		{
			long_tag("Color R"),
			long_tag("Color G"),
			long_tag("Color B"),
			long_tag("Maximum Density"),
			long_tag("Start Distance"),
			long_tag("Opaque Distance"),
		}),
		block_tag("Sky Fog",
		{
			long_tag("Color R"),
			long_tag("Color G"),
			long_tag("Color B"),
			long_tag("Density"),
		}),
		block_tag("Patchy Fog",
		{
			long_tag("Color R"),
			long_tag("Color G"),
			long_tag("Color B"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Density Min"),
			long_tag("Density Max"),
			long_tag("Distance Max"),
			long_tag("Distance Max"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Patchy Fog", 9999),
		}),
		long_tag("Bloom Override Amount"),
		long_tag("Bloom Override Threshold"),
		long_tag("Bloom Override Brightness"),
		long_tag("Bloom Override Gamma Power"),
		block_tag("Lights",
		{
			long_tag("Direction Vector i"),
			long_tag("Direction Vector j"),
			long_tag("Direction Vector k"),
			undefined_tag("Direction Y", 9999),
			undefined_tag("Direction P", 9999),
			undefined_tag("Lens Flare", 9999),
			block_tag("Fog",
			{
				long_tag("Color R"),
				long_tag("Color G"),
				long_tag("Color B"),
				long_tag("Maximum Density"),
				long_tag("Start Distnace"),
				long_tag("Opaque Distnace"),
				undefined_tag("Cone Min", 9999),
				undefined_tag("Cone Max", 9999),
				long_tag("Atmospheroc Fog Influence"),
				long_tag("Secondary Fog Influence"),
				long_tag("Sky Fog Influence"),
			}),
			block_tag("Fog Opposite",
			{
				long_tag("Color R"),
				long_tag("Color G"),
				long_tag("Color B"),
				long_tag("Maximum Density"),
				long_tag("Start Distnace"),
				long_tag("Opaque Distnace"),
				undefined_tag("Cone Min", 9999),
				undefined_tag("Cone Max", 9999),
				long_tag("Atmospheroc Fog Influence"),
				long_tag("Secondary Fog Influence"),
				long_tag("Sky Fog Influence"),
			}),
			block_tag("Radiosity",
			{
				undefined_tag("Flags", 9999),
				long_tag("Color R"),
				long_tag("Color G"),
				long_tag("Color B"),
				long_tag("Power"),
				long_tag("Test Distance"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Diameter", 9999),
			}),
		}),
		undefined_tag("Global Sky Rotation", 9999),
		block_tag("Shader Functions",
		{
			undefined_tag("Unknown", 9999),
			string_tag("Global Functions Name"),
		}),
		block_tag("Animations",
		{
			short_tag("Animation Index"),
			short_tag("Unknown"),
			long_tag("Period"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Clear Color R"),
		long_tag("Clear Color G"),
		long_tag("Clear Color B"),
	});
};
