#include "sncl.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* sncl_group = new tag_collection(
	"sncl",
	{
		
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		undefined_tag("", 9999),
		block_tag("Sound Classes",
		{
			short_tag("Max Sounds Per Tag"),
			short_tag("Max Sounds Per Object"),
			long_tag("Preemption Time"),
			short_tag("Internal Flags"),
			short_tag("Flags"),
			short_tag("Priority"),
			short_tag("Cache Miss Mode"),
			long_tag("Reverb Gain"),
			long_tag("Override Speaker Gain"),
			undefined_tag("Distance Bounds", 9999),
			undefined_tag("Gain Bounds", 9999),
			long_tag("Cutscene Ducking"),
			long_tag("Cutscene Ducking Fade In Time"),
			long_tag("Cutscene Ducking Sustain Time"),
			long_tag("Cutscene Ducking Fade Out Time"),
			long_tag("Scripted Dialog Ducking"),
			long_tag("Scripted Dialog Ducking Fade In Time"),
			long_tag("Scripted Dialog Ducking Sustain Time"),
			long_tag("Scripted Dialog Ducking Fade Out Time"),
			long_tag("Doppler Factor"),
			undefined_tag("Stereo Playback Type", 9999),
			long_tag("Transmission Multiplier"),
			long_tag("Obstruction Max Bend"),
			long_tag("Occlusion Max Bend"),
		}),
	});
};
