#include "spas.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* spas_group = new tag_collection(
	"spas",
	{
		
		undefined_tag("Documentation", 9999),
		block_tag("Parameters",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Explanation", 9999),
			short_tag("Type"),
			short_tag("Flags"),
			undefined_tag("Default Bitmap", 9999),
			long_tag("Default Constant Value"),
			undefined_tag("Default Constant Color", 9999),
			short_tag("Source Extern"),
			short_tag("Unknown"),
		}),
		short_tag("Unknown"),
		short_tag("Unknown"),
		block_tag("Implementations",
		{
			short_tag("Flags"),
			short_tag("Unknown"),
			block_tag("Textures",
			{
				undefined_tag("Source Parameter", 9999),
				short_tag("Source Extern"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Mode"),
				short_tag("Unknown"),
				short_tag("Dot Mapping"),
				short_tag("Input Stage"),
				short_tag("Unknown"),
				block_tag("Address State",
				{
					short_tag("U Address Mode"),
					short_tag("V Address Mode"),
					short_tag("W Address Mode"),
					short_tag("Unknown"),
				}),
				block_tag("Filter State",
				{
					short_tag("Mag Filter"),
					short_tag("Min Filter"),
					short_tag("Mip Filter"),
					short_tag("Unknown"),
					long_tag("Mipmap Bias"),
					short_tag("Max Mipmap Index"),
					short_tag("Anisotropy"),
				}),
				block_tag("Kill State",
				{
					short_tag("Flags"),
					short_tag("Unknown"),
					short_tag("Colorkey Mode"),
					short_tag("Unknown"),
					undefined_tag("Colorkey Color", 9999),
				}),
				block_tag("Misc State",
				{
					short_tag("Component Sign Flags"),
					short_tag("Unknown"),
					undefined_tag("Border Color", 9999),
				}),
				block_tag("Constants",
				{
					undefined_tag("Source Parameter", 9999),
					short_tag("Unknown"),
					short_tag("Constant"),
				}),
			}),
			undefined_tag("Vertex Shader", 9999),
			block_tag("Vs Constants",
			{
				undefined_tag("Source Parameter", 9999),
				short_tag("Scale By Texture Stage"),
				short_tag("Register Bank"),
				short_tag("Register Index"),
				short_tag("Component Mask"),
			}),
			undefined_tag("Pixel Shader Code", 9999),
			short_tag("Channels"),
			short_tag("Alpha-Blend"),
			short_tag("Depth"),
			short_tag("Unknown"),
			block_tag("Channel State",
			{
				short_tag("Flags"),
				short_tag("Unknown"),
			}),
			block_tag("Alpha-Blend State",
			{
				short_tag("Blend Function"),
				short_tag("Blend Src Factor"),
				short_tag("Blend Dst Factor"),
				short_tag("Unknown"),
				undefined_tag("Blend Color", 9999),
				short_tag("Logic-Op Flags"),
				short_tag("Unknown"),
			}),
			block_tag("Alpha-Test State",
			{
				short_tag("Flags"),
				short_tag("Alpha Compare Function"),
				short_tag("Alpha-Test Ref"),
				short_tag("Unknown"),
			}),
			block_tag("Depth State",
			{
				short_tag("Mode"),
				short_tag("Depth Compare Function"),
				short_tag("Flags"),
				short_tag("Unknown"),
				long_tag("Depth Bias Slope Scale"),
				long_tag("Depth Bias"),
			}),
			block_tag("Cull State",
			{
				short_tag("Mode"),
				short_tag("Front Face"),
			}),
			block_tag("Fill State",
			{
				short_tag("Flags"),
				short_tag("Fill Mode"),
				short_tag("Back Fill Mode"),
				short_tag("Unknown"),
				long_tag("Line Width"),
			}),
			block_tag("Misc State",
			{
				short_tag("Flags"),
				short_tag("Unknown"),
				undefined_tag("Fog Color", 9999),
			}),
			block_tag("Constants",
			{
				undefined_tag("Source Parameter", 9999),
				short_tag("Unknown"),
				short_tag("Constant"),
			}),
			undefined_tag("Pixel Shader", 9999),
		}),
		block_tag("Postprocess Definition",
		{
			block_tag("Implementations",
			{
				short_tag("Textures Block Index Data"),
				short_tag("Render States Block Index Data"),
				short_tag("Texture States Block Index Data"),
				short_tag("Unknown"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				short_tag("Unknown"),
				short_tag("Ps Fragments Block Index Data"),
				short_tag("Ps Permutations Block Index Data"),
				short_tag("Ps Combiners Block Index Data"),
				undefined_tag("Vertex Shader", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				short_tag("Default Render States Block Index Data"),
				short_tag("Render State Externs Block Index Data"),
				short_tag("State Externs Block Index Data"),
				short_tag("Constant Externs Block Index Data"),
				short_tag("Constant Externs Block Index Data"),
				short_tag("Ps Constants Block Index Data"),
				short_tag("Vs Constants Block Index Data"),
				short_tag("Pixel Constant Info Block Index Data"),
				short_tag("Vertex Constant Info Block Index Data"),
				short_tag("Render State Info Block Index Data"),
				short_tag("Texture State Info Block Index Data"),
				block_tag("Pixel Shader",
				{
					long_tag("Pixel Shader Handle (Runtime)"),
					long_tag("Pixel Shader Handle (Runtime)"),
					long_tag("Pixel Shader Handle (Runtime)"),
					block_tag("Constant Register Defaults",
					{
						long_tag("Defaults"),
					}),
					undefined_tag("Compiled Shader", 9999),
					undefined_tag("Compiled Shader", 9999),
					undefined_tag("Compiled Shader", 9999),
				}),
				block_tag("Pixel Shader Switch Extern Map",
				{
					byte_tag("Switch Parameter"),
					byte_tag("Case Scalar"),
				}),
				block_tag("Pixel Shader Index Block",
				{
					byte_tag("Pixel Shader Index"),
				}),
			}),
			block_tag("Textures",
			{
				byte_tag("Bitmap Parameter Index"),
				byte_tag("Bitmap Extern Index"),
				byte_tag("Texture Stage Index"),
				byte_tag("Flags"),
			}),
			block_tag("Render States",
			{
				byte_tag("State Index"),
				long_tag("State Value"),
			}),
			block_tag("Texture States",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("Ps Fragments",
			{
				byte_tag("Switch Parameter Index"),
				short_tag("Permutations Index Block Index Data"),
			}),
			block_tag("Ps Permutations",
			{
				short_tag("Enum Index"),
				short_tag("Flags"),
				short_tag("Combiners Block Index Data"),
			}),
			block_tag("Ps Combiners",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Constant Color0", 9999),
				undefined_tag("Constant Color1", 9999),
				byte_tag("Color A Register Ptr Index"),
				byte_tag("Color B Register Ptr Index"),
				byte_tag("Color C Register Ptr Index"),
				byte_tag("Color D Register Ptr Index"),
				byte_tag("Alpha A Register Ptr Index"),
				byte_tag("Alpha B Register Ptr Index"),
				byte_tag("Alpha C Register Ptr Index"),
				byte_tag("Alpha D Register Ptr Index"),
			}),
			block_tag("Externs",
			{
				short_tag("Unknown"),
				byte_tag("Unknown"),
				byte_tag("Extern Index"),
			}),
			block_tag("Constants",
			{
				undefined_tag("Parameter Name", 9999),
				byte_tag("Component Mask"),
				byte_tag("Scale By Texture Stage"),
				byte_tag("Function Index"),
			}),
			block_tag("Constant Info",
			{
				undefined_tag("Parameter Name", 9999),
				short_tag("Unknown"),
				byte_tag("Unknown"),
			}),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
	});
};
