#include "tdtl.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* tdtl_group = new tag_collection(
	"tdtl",
	{
		
		short_tag("Unknown"),
		short_tag("Type"),
		undefined_tag("Attachment Marker Name", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Falloff Distance From Camera"),
		long_tag("Cutoff Distance From Camera"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Arcs",
		{
			short_tag("Flags"),
			short_tag("Sprite Count"),
			long_tag("Natural Length"),
			short_tag("Instances"),
			short_tag("Unknown"),
			undefined_tag("Instance Spread Angle", 9999),
			long_tag("Instance Rotation Period"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Material Effects", 9999),
			undefined_tag("Bitmap", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Horizontal Range", 9999),
			undefined_tag("Vertical Range", 9999),
			long_tag("Vertical Negative Scale"),
			undefined_tag("Vertical Negative Scale", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("Octave 1 Frequency Cycles Per Sec"),
			long_tag("Octave 2 Frequency Cycles Per Sec"),
			long_tag("Octave 3 Frequency Cycles Per Sec"),
			long_tag("Octave 4 Frequency Cycles Per Sec"),
			long_tag("Octave 5 Frequency Cycles Per Sec"),
			long_tag("Octave 6 Frequency Cycles Per Sec"),
			long_tag("Octave 7 Frequency Cycles Per Sec"),
			long_tag("Octave 8 Frequency Cycles Per Sec"),
			long_tag("Octave 9 Frequency Cycles Per Sec"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Octave Flags", 9999),
			block_tag("Cores",
			{
				short_tag("Bitmap Index"),
				short_tag("Unknown"),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Thickness", 9999),
				undefined_tag("Color", 9999),
				undefined_tag("Brightness/Time", 9999),
				undefined_tag("Brightness/Facing", 9999),
				undefined_tag("Along-Axis Scale", 9999),
			}),
			undefined_tag("Range-Collision Scale", 9999),
			undefined_tag("Brightness-Collision Scale", 9999),
		}),
	});
};
