#include "vehi.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* vehi_group = new tag_collection(
	"vehi",
	{
		
		short_tag("Object Type"),
		short_tag("Flags"),
		long_tag("Bounding Radius"),
		undefined_tag("Bounding Offset", 9999),
		long_tag("Acceleration Scale"),
		short_tag("Lightmap Shadow Mode"),
		byte_tag("Sweetener Size"),
		byte_tag("Unknown"),
		undefined_tag("Runtime Flags", 9999),
		long_tag("Dynamic Light Sphere Radius"),
		undefined_tag("Dynamic Light Sphere Offset", 9999),
		undefined_tag("Default Model Variant", 9999),
		undefined_tag("Model", 9999),
		undefined_tag("Crate Object", 9999),
		undefined_tag("Modifier Shader", 9999),
		undefined_tag("Creation Effect", 9999),
		undefined_tag("Material Effects", 9999),
		block_tag("AI Properties",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("AI Type Name", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("AI Size"),
			short_tag("Leap Jump Speed"),
		}),
		block_tag("Functions",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Import Name", 9999),
			undefined_tag("Export Name", 9999),
			undefined_tag("Turn Off With", 9999),
			long_tag("Minimum Value"),
			undefined_tag("Default Function", 9999),
			undefined_tag("Scale By", 9999),
		}),
		long_tag("Apply Collision Damage Scale"),
		undefined_tag("Game Acceleration", 9999),
		undefined_tag("Game Scale", 9999),
		undefined_tag("Absolute Acceleration", 9999),
		undefined_tag("Absolute Scale", 9999),
		short_tag("HUD Text Message Index"),
		short_tag("Unknown"),
		block_tag("Attachments",
		{
			undefined_tag("Type", 9999),
			undefined_tag("Marker", 9999),
			short_tag("Change Color"),
			short_tag("Unknown"),
			undefined_tag("Primary Scale", 9999),
			undefined_tag("Secondary Scale", 9999),
		}),
		block_tag("Widgets",
		{
			undefined_tag("Type", 9999),
		}),
		block_tag("Old Functions",
		{
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Change Colors",
		{
			block_tag("Initial Permutations",
			{
				long_tag("Weight"),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Variant Name", 9999),
			}),
			block_tag("Functions",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Scale Flags", 9999),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Darken By", 9999),
				undefined_tag("Scale By", 9999),
			}),
		}),
		block_tag("Predicted Resources",
		{
			short_tag("Type"),
			short_tag("Resource Index"),
			tagref_tag("Tag Index"),
		}),
		undefined_tag("Flags", 9999),
		short_tag("Default Team"),
		short_tag("Constant Sound Volume"),
		undefined_tag("Integrated Light Toggle", 9999),
		undefined_tag("Camera Field of View", 9999),
		long_tag("Camera Stiffness"),
		undefined_tag("Camera Marker Name", 9999),
		undefined_tag("Camera Submerged Marker Name", 9999),
		undefined_tag("Pitch Auto-Level", 9999),
		undefined_tag("Pitch Range", 9999),
		block_tag("Camera Tracks",
		{
			undefined_tag("Track", 9999),
		}),
		undefined_tag("Acceleration Range", 9999),
		long_tag("Acceleration Action Scale"),
		long_tag("Acceleration Attach Scale"),
		long_tag("Soft Ping Threshold"),
		long_tag("Soft Ping Interrupt Time"),
		long_tag("Hard Ping Threshold"),
		long_tag("Hard Ping Interrupt Time"),
		long_tag("Hard Death Threshold"),
		long_tag("Feign Death Threshold"),
		long_tag("Feign Death Time"),
		long_tag("Distance Of Evade Animation"),
		long_tag("Distance Of Dive Animation"),
		long_tag("Stunned Movement Threshold"),
		long_tag("Feign Death Chance"),
		long_tag("Feign Repeat Chance"),
		undefined_tag("Spawned Turret Character", 9999),
		undefined_tag("Spawned Actor Count", 9999),
		long_tag("Spawned Velocity"),
		undefined_tag("Aiming Velocity Maximum", 9999),
		undefined_tag("Aiming Acceleration Maximum", 9999),
		long_tag("Casual Aiming Modifier"),
		undefined_tag("Looking Velocity Maximum", 9999),
		undefined_tag("Looking Acceleration Maximum", 9999),
		undefined_tag("Right Hand Node", 9999),
		undefined_tag("Left Hand Node", 9999),
		undefined_tag("Preferred Gun Node", 9999),
		undefined_tag("Melee Damage", 9999),
		undefined_tag("Boarding Melee Damage", 9999),
		undefined_tag("Boarding Melee Response", 9999),
		undefined_tag("Landing Melee Damage", 9999),
		undefined_tag("Flurry Melee Damage", 9999),
		undefined_tag("Obstacle Smash Damage", 9999),
		short_tag("Motion Sensor Blip Size"),
		short_tag("Unknown"),
		block_tag("Postures",
		{
			undefined_tag("Name", 9999),
			undefined_tag("Pill Offset", 9999),
		}),
		block_tag("New HUD Interfaces",
		{
			undefined_tag("New Unit HUD Interface", 9999),
		}),
		block_tag("Dialogue Variants",
		{
			short_tag("Variant Number"),
			short_tag("Unknown"),
			undefined_tag("Dialogue", 9999),
		}),
		long_tag("Grenade Velocity"),
		short_tag("Grenade Type"),
		short_tag("Grenade Count"),
		block_tag("Powered Seats",
		{
			long_tag("Driver Powerup Time"),
			long_tag("Driver Powerdown Time"),
		}),
		block_tag("Weapons",
		{
			undefined_tag("Weapon", 9999),
		}),
		block_tag("Seats",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Seat Animation", 9999),
			undefined_tag("Seat Marker Name", 9999),
			undefined_tag("Entry Marker(s) Name", 9999),
			undefined_tag("Boarding Grenade Marker", 9999),
			undefined_tag("Boarding Grenade String", 9999),
			undefined_tag("Boarding Melee String", 9999),
			long_tag("Ping Scale"),
			long_tag("Turnover Time"),
			undefined_tag("Acceleration Range", 9999),
			long_tag("Acceleration Action Scale"),
			long_tag("Acceleration Attach Scale"),
			long_tag("AI Scariness"),
			short_tag("AI Seat Type"),
			short_tag("Boarding Seat Index"),
			long_tag("Listener Interpolation Factor"),
			undefined_tag("", 9999),
			undefined_tag("", 9999),
			undefined_tag("Yaw Rate Bounds", 9999),
			undefined_tag("Pitch Rate Bounds", 9999),
			long_tag("Minimum Speed Reference"),
			long_tag("Maximum Speed Reference"),
			long_tag("Speed Exponent"),
			undefined_tag("Camera Marker Name", 9999),
			undefined_tag("Camera Submerged Marker Name", 9999),
			undefined_tag("Pitch Auto-Level", 9999),
			undefined_tag("Pitch Range", 9999),
			block_tag("Camera Tracks",
			{
				undefined_tag("Track", 9999),
			}),
			block_tag("Unit HUD Interface",
			{
				undefined_tag("New Unit HUD Interface", 9999),
			}),
			undefined_tag("Enter Seat String", 9999),
			undefined_tag("Yaw", 9999),
			undefined_tag("Built-In Gunner", 9999),
			long_tag("Entry Radius"),
			undefined_tag("Entry Marker Cone Angle", 9999),
			undefined_tag("Entry Marker Facing Angle", 9999),
			long_tag("Maximum Relative Velocity"),
			undefined_tag("Invisible Seat Region", 9999),
			long_tag("Invisible Seat Region Index"),
		}),
		long_tag("Boost Peak Power"),
		long_tag("Boost Rise Power"),
		long_tag("Boost Peak Time"),
		long_tag("Boost Fall Power"),
		long_tag("Boost Dead Time"),
		long_tag("Lipsync Attack Weight"),
		long_tag("Lipsync Decay Weight"),
		undefined_tag("Flags", 9999),
		short_tag("Type"),
		short_tag("Control"),
		long_tag("Maximum Forward Speed"),
		long_tag("Maximum Reverse Speed"),
		long_tag("Speed Acceleration"),
		long_tag("Speed Deceleration"),
		long_tag("Maximum Left Turn"),
		long_tag("Maximum Right Turn (negative)"),
		long_tag("Wheel Circumference"),
		long_tag("Turn Rate"),
		long_tag("Blur Speed"),
		short_tag("Specific Type"),
		short_tag("Player Training Vehicle Type"),
		undefined_tag("Flip Message", 9999),
		long_tag("Turn Scale"),
		long_tag("Speed Turn Penalty Power"),
		long_tag("Speed Turn Penalty"),
		long_tag("Maximum Left Slide"),
		long_tag("Maximum Right Slide"),
		long_tag("Slide Acceleration"),
		long_tag("Slide Deceleration"),
		long_tag("Minimum Flipping Angular Velocity"),
		long_tag("Maximum Flipping Angular Velocity"),
		short_tag("Vehicle Size"),
		short_tag("Unknown"),
		long_tag("Fixed Gun Yaw"),
		long_tag("Fixed Gun Pitch"),
		long_tag("Overdampen Cusp Angle"),
		long_tag("Overdampen Exponent"),
		long_tag("Crouch Transition Time"),
		long_tag("Unknown"),
		long_tag("Engine Moment"),
		long_tag("Engine Max Angular Velocity"),
		block_tag("Gears",
		{
			long_tag("Minimum Torque"),
			long_tag("Maximum Torque"),
			long_tag("Peak Torque Scale"),
			long_tag("Past Peak Torque Exponent"),
			long_tag("Torque at Maximum Angular Velocity"),
			long_tag("Torque at 2x Maximum Angular Velocity"),
			long_tag("Minimum Torque"),
			long_tag("Maximum Torque"),
			long_tag("Peak Torque Scale"),
			long_tag("Past Peak Torque Exponent"),
			long_tag("Torque at Maximum Angular Velocity"),
			long_tag("Torque at 2x Maximum Angular Velocity"),
			long_tag("Minimum Time to Up-Shift"),
			long_tag("Engine Up-Shift Scale"),
			long_tag("Gear Ratio"),
			long_tag("Minimum Time to Down-Shift"),
			long_tag("Engine Down-Shift Scale"),
		}),
		long_tag("Flying Torque Scale"),
		long_tag("Seat Entrance Acceleration Scale"),
		long_tag("Seat Exit Acceleration Scale"),
		long_tag("Air Friction Deceleration"),
		long_tag("Thrust Scale"),
		undefined_tag("Suspension Sound", 9999),
		undefined_tag("Crash Sound", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Special Effect", 9999),
		undefined_tag("Unknown Effect", 9999),
		undefined_tag("Flags", 9999),
		long_tag("Ground Friction"),
		long_tag("Ground Depth"),
		long_tag("Ground Damp Factor"),
		long_tag("Ground Moving Friction"),
		long_tag("Ground Maximum Slope 0"),
		long_tag("Ground Maximum Slope 1"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Anti Gravity Bank Lift"),
		long_tag("Steering Bank Reaction Scale"),
		long_tag("Gravity Scale"),
		long_tag("Radius"),
		block_tag("Anti Gravity Points",
		{
			undefined_tag("Marker Name", 9999),
			undefined_tag("Flags", 9999),
			long_tag("Antigrav Strength"),
			long_tag("Antigrav Offset"),
			long_tag("Antigrav Height"),
			long_tag("Antigrav Damp Factor"),
			long_tag("Antigrav Normal k1"),
			long_tag("Antigrav Normal k0"),
			long_tag("Radius"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("Unknown"),
			short_tag("Damage Source Region Index"),
			undefined_tag("Damage Source Region Name", 9999),
			long_tag("Default State Error"),
			long_tag("Minor Damage Error"),
			long_tag("Medium Damage Error"),
			long_tag("Major Damage Error"),
			long_tag("Destroyed State Error"),
		}),
		block_tag("Friction Points",
		{
			undefined_tag("Marker Name", 9999),
			undefined_tag("Flags", 9999),
			long_tag("Fraction Of Total Mass"),
			long_tag("Radius"),
			long_tag("Damaged Radius"),
			short_tag("Friction Type"),
			short_tag("Unknown"),
			long_tag("Moving Friction Velocity Differential"),
			long_tag("E-Brake Moving Friction"),
			long_tag("E-Brake Friction"),
			long_tag("E-Brake Moving Friction Velocity Differential"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Collision Material Name", 9999),
			short_tag("Collision Global Material Index"),
			short_tag("Model State Destroyed"),
			undefined_tag("Region Name", 9999),
			short_tag("Region Index"),
			short_tag("Unknown"),
		}),
		block_tag("Phantom Shapes",
		{
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("Unknown", 9999),
			undefined_tag("User Data", 9999),
			long_tag("Child Shapes Size"),
			undefined_tag("Child Shapes Capacity", 9999),
			short_tag("Shape Type 0"),
			short_tag("Shape Index 0"),
			long_tag("Collision Filter 0"),
			short_tag("Shape Type 1"),
			short_tag("Shape Index 1"),
			long_tag("Collision Filter 1"),
			short_tag("Shape Type 2"),
			short_tag("Shape Index 2"),
			long_tag("Collision Filter 2"),
			short_tag("Shape Type 3"),
			short_tag("Shape Index 3"),
			long_tag("Collision Filter 3"),
			undefined_tag("Multisphere Count", 9999),
			undefined_tag("Flags", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			long_tag("x0"),
			long_tag("x1"),
			long_tag("y0"),
			long_tag("y1"),
			long_tag("z0"),
			long_tag("z1"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			undefined_tag("Number of Spheres", 9999),
			undefined_tag("Sphere 0", 9999),
			long_tag("w Sphere 0"),
			undefined_tag("Sphere 1", 9999),
			long_tag("w Sphere 1"),
			undefined_tag("Sphere 2", 9999),
			long_tag("w Sphere 2"),
			undefined_tag("Sphere 3", 9999),
			long_tag("w Sphere 3"),
			undefined_tag("Sphere 4", 9999),
			long_tag("w Sphere 4"),
			undefined_tag("Sphere 5", 9999),
			long_tag("w Sphere 5"),
			undefined_tag("Sphere 6", 9999),
			long_tag("w Sphere 6"),
			undefined_tag("Sphere 7", 9999),
			long_tag("w Sphere 7"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			undefined_tag("Number of Spheres", 9999),
			undefined_tag("Sphere 0", 9999),
			long_tag("w Sphere 0"),
			undefined_tag("Sphere 1", 9999),
			long_tag("w Sphere 1"),
			undefined_tag("Sphere 2", 9999),
			long_tag("w Sphere 2"),
			undefined_tag("Sphere 3", 9999),
			long_tag("w Sphere 3"),
			undefined_tag("Sphere 4", 9999),
			long_tag("w Sphere 4"),
			undefined_tag("Sphere 5", 9999),
			long_tag("w Sphere 5"),
			undefined_tag("Sphere 6", 9999),
			long_tag("w Sphere 6"),
			undefined_tag("Sphere 7", 9999),
			long_tag("w Sphere 7"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			undefined_tag("Number of Spheres", 9999),
			undefined_tag("Sphere 0", 9999),
			long_tag("w Sphere 0"),
			undefined_tag("Sphere 1", 9999),
			long_tag("w Sphere 1"),
			undefined_tag("Sphere 2", 9999),
			long_tag("w Sphere 2"),
			undefined_tag("Sphere 3", 9999),
			long_tag("w Sphere 3"),
			undefined_tag("Sphere 4", 9999),
			long_tag("w Sphere 4"),
			undefined_tag("Sphere 5", 9999),
			long_tag("w Sphere 5"),
			undefined_tag("Sphere 6", 9999),
			long_tag("w Sphere 6"),
			undefined_tag("Sphere 7", 9999),
			long_tag("w Sphere 7"),
			undefined_tag("Runtime Code Pointer", 9999),
			short_tag("Size"),
			short_tag("Count"),
			undefined_tag("User Data", 9999),
			undefined_tag("Number of Spheres", 9999),
			undefined_tag("Sphere 0", 9999),
			long_tag("w Sphere 0"),
			undefined_tag("Sphere 1", 9999),
			long_tag("w Sphere 1"),
			undefined_tag("Sphere 2", 9999),
			long_tag("w Sphere 2"),
			undefined_tag("Sphere 3", 9999),
			long_tag("w Sphere 3"),
			undefined_tag("Sphere 4", 9999),
			long_tag("w Sphere 4"),
			undefined_tag("Sphere 5", 9999),
			long_tag("w Sphere 5"),
			undefined_tag("Sphere 6", 9999),
			long_tag("w Sphere 6"),
			undefined_tag("Sphere 7", 9999),
			long_tag("w Sphere 7"),
		}),
	});
};
