#include "weap.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* weap_group = new tag_collection(
	"weap",
	{
		
		short_tag("Object Type"),
		short_tag("Flags"),
		long_tag("Bounding Radius"),
		undefined_tag("Bounding Offset", 9999),
		long_tag("Acceleration Scale"),
		short_tag("Lightmap Shadow Mode"),
		byte_tag("Sweetener Size"),
		byte_tag("Unknown"),
		undefined_tag("Runtime Flags", 9999),
		long_tag("Dynamic Light Sphere Radius"),
		undefined_tag("Dynamic Light Sphere Offset", 9999),
		undefined_tag("Default Model Variant", 9999),
		undefined_tag("Model", 9999),
		undefined_tag("Crate Object", 9999),
		undefined_tag("Modifier Shader", 9999),
		undefined_tag("Creation Effect", 9999),
		undefined_tag("Material Effects", 9999),
		block_tag("AI Properties",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("AI Type Name", 9999),
			undefined_tag("Unknown", 9999),
			short_tag("AI Size"),
			short_tag("Leap Jump Speed"),
		}),
		block_tag("Functions",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Import Name", 9999),
			undefined_tag("Export Name", 9999),
			undefined_tag("Turn Off With", 9999),
			long_tag("Minimum Value"),
			undefined_tag("Default Function", 9999),
			undefined_tag("Scale By", 9999),
		}),
		long_tag("Apply Collision Damage Scale"),
		undefined_tag("Game Acceleration", 9999),
		undefined_tag("Game Scale", 9999),
		undefined_tag("Absolute Acceleration", 9999),
		undefined_tag("Absolute Scale", 9999),
		short_tag("HUD Text Message Index"),
		short_tag("Unknown"),
		block_tag("Attachments",
		{
			undefined_tag("Type", 9999),
			undefined_tag("Marker", 9999),
			short_tag("Change Color"),
			short_tag("Unknown"),
			undefined_tag("Primary Scale", 9999),
			undefined_tag("Secondary Scale", 9999),
		}),
		block_tag("Widgets",
		{
			undefined_tag("Type", 9999),
		}),
		block_tag("Old Functions",
		{
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Change Colors",
		{
			block_tag("Initial Permutations",
			{
				long_tag("Weight"),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Variant Name", 9999),
			}),
			block_tag("Functions",
			{
				undefined_tag("Unknown", 9999),
				undefined_tag("Scale Flags", 9999),
				undefined_tag("Color Lower Bound", 9999),
				undefined_tag("Color Upper Bound", 9999),
				undefined_tag("Darken By", 9999),
				undefined_tag("Scale By", 9999),
			}),
		}),
		block_tag("Predicted Resources",
		{
			short_tag("Type"),
			short_tag("Resource Index"),
			tagref_tag("Tag Index"),
		}),
		undefined_tag("Flags", 9999),
		short_tag("Old Message Index"),
		short_tag("Sort Order"),
		long_tag("Multiplayer On-Ground Scale"),
		long_tag("Campaign On-Ground Scale"),
		undefined_tag("Pickup Message", 9999),
		undefined_tag("Swap Message", 9999),
		undefined_tag("Pickup or Dual Wield Message", 9999),
		undefined_tag("Swap or Dual Wield Message", 9999),
		undefined_tag("Dual Wield Only Message", 9999),
		undefined_tag("Picked Up Message", 9999),
		undefined_tag("Singular Quantity Message", 9999),
		undefined_tag("Plural Quantity Message", 9999),
		undefined_tag("Switch-To Message", 9999),
		undefined_tag("Switch-To From AI Message", 9999),
		undefined_tag("UNUSED", 9999),
		undefined_tag("Collision Sound", 9999),
		block_tag("Predicted Bitmaps",
		{
			undefined_tag("Bitmap", 9999),
		}),
		undefined_tag("Detonation Damage Effect", 9999),
		undefined_tag("Detonation Delay", 9999),
		undefined_tag("Detonating Effect", 9999),
		undefined_tag("Detonation Effect", 9999),
		undefined_tag("Flags", 9999),
		undefined_tag("Unknown", 9999),
		short_tag("Secondary Trigger Mode"),
		short_tag("Maximum Alternate Shots Loaded"),
		long_tag("Turn On Time"),
		long_tag("Ready Time"),
		undefined_tag("Ready Effect", 9999),
		undefined_tag("Ready Damage Effect", 9999),
		long_tag("Heat Recovery Threshold"),
		long_tag("Overheated Threshold"),
		long_tag("Heat Detonation Threshold"),
		long_tag("Heat Detonation Fraction"),
		long_tag("Heat Loss Per Second"),
		long_tag("Heat Illumination"),
		long_tag("Overheated Heat Loss Per Second"),
		undefined_tag("Overheated", 9999),
		undefined_tag("Overheated Damage Effect", 9999),
		undefined_tag("Detonation", 9999),
		undefined_tag("Detonation Damage Effect", 9999),
		undefined_tag("Player Melee Damage", 9999),
		undefined_tag("Player Melee Response", 9999),
		undefined_tag("Magnetism Angle", 9999),
		long_tag("Magnetism Range"),
		long_tag("Throttle Magnitude"),
		long_tag("Throttle Minimum Distance"),
		undefined_tag("Throttle Maximum Adjustment Angle", 9999),
		undefined_tag("Damage Pyramid Angles", 9999),
		long_tag("Damage Pyramid Depth"),
		undefined_tag("1st Hit Melee Damage", 9999),
		undefined_tag("1st Hit Melee Response", 9999),
		undefined_tag("2nd Hit Melee Damage", 9999),
		undefined_tag("2nd Hit Melee Response", 9999),
		undefined_tag("3rd Hit Melee Damage", 9999),
		undefined_tag("3rd Hit Melee Response", 9999),
		undefined_tag("Lunge Melee Damage", 9999),
		undefined_tag("Lunge Melee Response", 9999),
		byte_tag("Melee Damage Reporting Type"),
		byte_tag("Unknown"),
		short_tag("Magnification Levels"),
		undefined_tag("Magnification Range", 9999),
		undefined_tag("Autoaim Angle", 9999),
		long_tag("Autoaim Range"),
		undefined_tag("Magnetism Angle", 9999),
		long_tag("Magnetism Range"),
		undefined_tag("Deviation Angle", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		short_tag("Movement Penalized"),
		short_tag("Unknown"),
		long_tag("Forwards Movement Penalty"),
		long_tag("Sideways Movement Penalty"),
		long_tag("AI Scariness"),
		long_tag("Weapon Power-On Time"),
		long_tag("Weapon Power-Off Time"),
		undefined_tag("Weapon Power-On Effect", 9999),
		undefined_tag("Weapon Power-Off Effect", 9999),
		long_tag("Age Heat Recovery Penalty"),
		long_tag("Age Rate Of Fire Penalty"),
		long_tag("Age Misfire Start"),
		long_tag("Age Misfire Chance"),
		undefined_tag("Pickup Sound", 9999),
		undefined_tag("Zoom-In Sound", 9999),
		undefined_tag("Zoom-Out Sound", 9999),
		long_tag("Active Camo Ding"),
		long_tag("Active Camo Regrowth Rate"),
		undefined_tag("Handle Node", 9999),
		undefined_tag("Weapon Class", 9999),
		undefined_tag("Weapon Name", 9999),
		short_tag("Multiplayer Weapon Type"),
		short_tag("Weapon Type"),
		short_tag("Tracking Type"),
		short_tag("Unknown"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("First Person",
		{
			undefined_tag("First Person Model", 9999),
			undefined_tag("First Person Animations", 9999),
		}),
		undefined_tag("New HUD Interface", 9999),
		block_tag("Predicted Resource",
		{
			short_tag("Type"),
			short_tag("Resource Index"),
			tagref_tag("Tag Index"),
		}),
		block_tag("Magazines",
		{
			undefined_tag("Flags", 9999),
			short_tag("Rounds Recharged"),
			short_tag("Rounds Total Initial"),
			short_tag("Rounds Total Maximum"),
			short_tag("Rounds Loaded Maximum"),
			short_tag("Runtime Rounds Inventory Maximum"),
			short_tag("Unknown"),
			long_tag("Reload Time"),
			short_tag("Rounds Reloaded"),
			short_tag("Unknown"),
			long_tag("Chamber Time"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Reloading Effect", 9999),
			undefined_tag("Reloading Damage Effect", 9999),
			undefined_tag("Chambering Effect", 9999),
			undefined_tag("Chambering Damage Effect", 9999),
			block_tag("Magazine Equipment",
			{
				short_tag("Rounds (0 for Max)"),
				short_tag("Unknown"),
				undefined_tag("Equipment", 9999),
			}),
		}),
		block_tag("New Triggers",
		{
			undefined_tag("Flags", 9999),
			short_tag("Input"),
			short_tag("Behavior"),
			short_tag("Primary Barrel"),
			short_tag("Secondary Barrel"),
			short_tag("Prediction"),
			short_tag("Unknown"),
			long_tag("Autofire Time"),
			long_tag("Autofire Throw"),
			short_tag("Secondary Action"),
			short_tag("Primary Action"),
			long_tag("Charging Time"),
			long_tag("Charged Time"),
			short_tag("Overcharged Action"),
			short_tag("Unknown"),
			long_tag("Charged Illumination"),
			long_tag("Spew Time"),
			undefined_tag("Charging Effect", 9999),
			undefined_tag("Charging Damage Effect", 9999),
		}),
		block_tag("Barrels",
		{
			undefined_tag("Flags", 9999),
			undefined_tag("Rounds Per Second", 9999),
			long_tag("Acceleration Time"),
			long_tag("Deceleration Time"),
			long_tag("Barrel Spin Scale"),
			long_tag("Blurred Rate Of Fire"),
			undefined_tag("Shots Per Fire", 9999),
			long_tag("Fire Recovery Time"),
			long_tag("Soft Recovery Fraction"),
			short_tag("Magazine"),
			short_tag("Rounds Per Shot"),
			short_tag("Minimum Rounds Loaded"),
			short_tag("Rounds Between Tracers"),
			undefined_tag("Optional Barrel Marker Name", 9999),
			short_tag("Prediction Type"),
			short_tag("Firing Noise"),
			long_tag("Acceleration Time"),
			long_tag("Deceleration Time"),
			undefined_tag("Damage Error", 9999),
			long_tag("Acceleration Time"),
			long_tag("Deceleration Time"),
			long_tag("Runtime Dual Error Acceleration Rate"),
			long_tag("Runtime Dual Error Deceleration Rate"),
			undefined_tag("Minimum Error", 9999),
			undefined_tag("Error Angle", 9999),
			long_tag("Dual Wield Damage Scale"),
			short_tag("Distribution Function"),
			short_tag("Projectiles Per Shot"),
			undefined_tag("Distribution Angle", 9999),
			undefined_tag("Minimum Error", 9999),
			undefined_tag("Error Angle", 9999),
			undefined_tag("First Person Offset", 9999),
			byte_tag("Damage Reporting Type"),
			byte_tag("Unknown"),
			short_tag("Unknown"),
			undefined_tag("Projectile", 9999),
			undefined_tag("Damage Effect", 9999),
			long_tag("Ejection Port Recovery Time"),
			long_tag("Illumination Recovery Time"),
			long_tag("Heat Generated Per Round"),
			long_tag("Age Generated Per Round"),
			long_tag("Overload Time"),
			undefined_tag("Angle Change Per Shot", 9999),
			long_tag("Angle Change Acceleration Time"),
			long_tag("Angle Change Deceleration Time"),
			short_tag("Angle Change Function"),
			short_tag("Unknown"),
			long_tag("Runtime Angle Change Acceleration Rate"),
			long_tag("Runtime Angle Change Deceleration Rate"),
			long_tag("Runtime Illumination Recovery Rate"),
			long_tag("Runtime Ejection Port Recovery Rate"),
			long_tag("Runtime Rate Of Fire Acceleration Rate"),
			long_tag("Runtime Rate Of Fire Deceleration Rate"),
			long_tag("Runtime Error Acceleration Rate"),
			long_tag("Runtime Error Deceleration Rate"),
			block_tag("Firing Effects",
			{
				short_tag("Shot Count Lower Bound"),
				short_tag("Shot Count Upper Bound"),
				undefined_tag("Firing Effect", 9999),
				undefined_tag("Misfire Effect", 9999),
				undefined_tag("Empty Effect", 9999),
				undefined_tag("Firing Damage", 9999),
				undefined_tag("Misfire Damage", 9999),
				undefined_tag("Empty Damage", 9999),
			}),
		}),
		long_tag("Weapon Power On Velocity"),
		long_tag("Weapon Power Off Velocity"),
		long_tag("Maximum Movement Acceleration"),
		long_tag("Maximum Movement Velocity"),
		long_tag("Maximum Turning Acceleration"),
		long_tag("Maximum Turning Velocity"),
		undefined_tag("Deployed Vehicle", 9999),
		undefined_tag("Age Effect", 9999),
		undefined_tag("Aged Weapon", 9999),
		undefined_tag("First Person Weapon Offset", 9999),
		undefined_tag("First Person Scope Size", 9999),
	});
};
