#include "weat.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* weat_group = new tag_collection(
	"weat",
	{
		
		block_tag("Particle System",
		{
			undefined_tag("Sprites", 9999),
			long_tag("View Box Width"),
			long_tag("View Box Height"),
			long_tag("View Box Depth"),
			long_tag("Exclusion Radius"),
			long_tag("Max Velocity"),
			long_tag("Min Mass"),
			long_tag("Max Mass"),
			long_tag("Min Size"),
			long_tag("Max Size"),
			long_tag("Maximum Number Of Particles"),
			long_tag("Initial Velocity i"),
			long_tag("Initial Velocity j"),
			long_tag("Initial Velocity k"),
			undefined_tag("Unknown", 9999),
			long_tag("Resource Block Offset"),
			undefined_tag("Resource Block Size", 9999),
			undefined_tag("Section Data Size", 9999),
			undefined_tag("Resource Data Size", 9999),
			block_tag("Resources",
			{
				byte_tag("Type"),
				byte_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Primary Locator"),
				short_tag("Secondary Locator"),
				undefined_tag("Resource Data Size", 9999),
				undefined_tag("Resource Data Offset", 9999),
			}),
			tagref_tag("Owner Tag"),
			short_tag("Owner Tag Section Offset"),
			short_tag("Unknown"),
			long_tag("Unknown"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Type", 9999),
			long_tag("Minimum Opacity"),
			long_tag("Maximum Opacity"),
			long_tag("Rain Streak Scale"),
			long_tag("Rain Line Width"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		block_tag("Background Plates",
		{
			undefined_tag("Texture 0", 9999),
			undefined_tag("Texture 1", 9999),
			undefined_tag("Texture 2", 9999),
			long_tag("Plate Position 0"),
			long_tag("Plate Position 1"),
			long_tag("Plate Position 2"),
			long_tag("Move Speed 0 i"),
			long_tag("Move Speed 0 j"),
			long_tag("Move Speed 0 k"),
			long_tag("Move Speed 1 i"),
			long_tag("Move Speed 1 j"),
			long_tag("Move Speed 1 k"),
			long_tag("Move Speed 2 i"),
			long_tag("Move Speed 2 j"),
			long_tag("Move Speed 2 k"),
			long_tag("Texture Scale 0"),
			long_tag("Texture Scale 1"),
			long_tag("Texture Scale 2"),
			long_tag("Jitter 0 i"),
			long_tag("Jitter 0 j"),
			long_tag("Jitter 0 k"),
			long_tag("Jitter 1 i"),
			long_tag("Jitter 1 j"),
			long_tag("Jitter 1 k"),
			long_tag("Jitter 2 i"),
			long_tag("Jitter 2 j"),
			long_tag("Jitter 2 k"),
			long_tag("Plate Z Near"),
			long_tag("Plate Z Far"),
			long_tag("Depth Blend Z Near"),
			long_tag("Depth Blend Z Far"),
			long_tag("Opacity 0"),
			long_tag("Opacity 1"),
			long_tag("Opacity 2"),
			undefined_tag("Flags", 9999),
			long_tag("Tint Color 0 R"),
			long_tag("Tint Color 0 G"),
			long_tag("Tint Color 0 B"),
			long_tag("Tint Color 1 R"),
			long_tag("Tint Color 1 G"),
			long_tag("Tint Color 1 B"),
			long_tag("Tint Color 2 R"),
			long_tag("Tint Color 2 G"),
			long_tag("Tint Color 2 B"),
			long_tag("Mass 1"),
			long_tag("Mass 2"),
			long_tag("Mass 3"),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
			undefined_tag("Unknown", 9999),
		}),
		long_tag("Wind Tiling Scale"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Wind Primary Heading i"),
		long_tag("Wind Primary Heading j"),
		long_tag("Wind Primary Heading k"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Primary Rate Of Change"),
		long_tag("Primary Min Strength"),
		undefined_tag("Unknown", 9999),
		long_tag("Wind Gusting Heading i"),
		long_tag("Wind Gusting Heading j"),
		long_tag("Wind Gusting Heading k"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Gust Directional Rate Of Change"),
		long_tag("Gust Strength Rate Of Change"),
		long_tag("Gust Cone Angle"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Turbulance Rate Of Change"),
		long_tag("Turbulence Scale x,y,z i"),
		long_tag("Turbulence Scale x,y,z j"),
		long_tag("Turbulence Scale x,y,z k"),
		long_tag("Gravity Constant"),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Fade Radius"),
	});
};
