#include "wgit.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* wgit_group = new tag_collection(
	"wgit",
	{
		
		short_tag("Back ground blur (blur=0 noblur=37)"),
		short_tag("Unknown"),
		short_tag("Menu ID"),
		short_tag("Visibles X-A-B Options Buttons"),
		long_tag("Unknown"),
		long_tag("Unknown"),
		long_tag("Unknown"),
		long_tag("Unknown"),
		undefined_tag("Unic", 9999),
		block_tag("Menu Content",
		{
			short_tag("Unknown"),
			short_tag("Transition Type"),
			block_tag("Buttons 1",
			{
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Button Transition type (bitmask)"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Font Type"),
				long_tag("Unknown"),
				long_tag("Text Color Red"),
				long_tag("Text Color Green"),
				long_tag("Text Color Blue"),
				short_tag("Bitmap Placement Positive Coord Y"),
				short_tag("Bitmap Placement Positive Coord X"),
				short_tag("Text Placement Negative Coord Y"),
				short_tag("Text Placement Negative Coord X"),
				undefined_tag("Bitm", 9999),
				undefined_tag("coord", 9999),
				undefined_tag("coord", 9999),
				undefined_tag("coord", 9999),
				undefined_tag("coord", 9999),
				undefined_tag("Something count", 9999),
				undefined_tag("Bitmap Transiton type (bitmask)", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("brightness something?", 9999),
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Unknown"),
			}),
			block_tag("Buttons 2",
			{
				short_tag("Buttons loop"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Button Type (Palette [skin])"),
				short_tag("Unknown"),
				short_tag("Number of visibles buttons"),
				short_tag("Unknown"),
				short_tag("Buttons Placement Coord X"),
				short_tag("Buttons Placement Coord Y"),
				short_tag("Transition Type? (bitmask)"),
				short_tag("Variation?"),
			}),
			long_tag("Unknown"),
			long_tag("Unknown"),
			block_tag("Text strings",
			{
				undefined_tag("Text options", 9999),
				short_tag("Transtion type (bitmask)"),
				short_tag("Variation?"),
				short_tag("Unknown"),
				short_tag("Font Type"),
				long_tag("Alpha"),
				long_tag("Color Red"),
				long_tag("Color Green"),
				long_tag("Color Blue"),
				undefined_tag("Text Placement", 9999),
				undefined_tag("String name", 9999),
				undefined_tag("Unknown", 9999),
			}),
			block_tag("UI bitmaps",
			{
				short_tag("unknown"),
				short_tag("Unknown"),
				short_tag("Transition type (bitmask)"),
				short_tag("Variation?"),
				short_tag("Alpha transparence"),
				short_tag("Xbox live bitmap setting"),
				short_tag("Bitmap Placement coord X"),
				short_tag("Bitmap Placement coord Y"),
				long_tag("Horizontal bitmap scrolling speed"),
				long_tag("Unknown"),
				undefined_tag("bitm", 9999),
				short_tag("Bitmap Layer Level"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				short_tag("Coord X for ?"),
				short_tag("Coord Y for ?"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
			block_tag("ModelsScript Objects: Scenery/Bipeds...)",
			{
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Transition type (bitmask)"),
				short_tag("Variation?"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				block_tag("Script Object",
				{
					string_tag("Script Object name"),
				}),
				block_tag("Unknown",
				{
					string_tag("Unknown"),
				}),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				undefined_tag("relatives: coord, size, palcement", 9999),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			long_tag("Unknown"),
			block_tag("Variable Buttons",
			{
				long_tag("Unknown"),
				undefined_tag("Skin", 9999),
				short_tag("Coord X"),
				short_tag("Coord Y"),
				undefined_tag("unknown", 9999),
				undefined_tag("Max Visible Buttons", 9999),
				undefined_tag("Unknown", 9999),
				undefined_tag("Unknown", 9999),
				short_tag("Coord X"),
				short_tag("Coord Y"),
			}),
		}),
		short_tag("Font Type"),
		short_tag("Unknown"),
		undefined_tag("Header Title Text String", 9999),
		block_tag("Descriptions/Help Text",
		{
			undefined_tag("Text Strings", 9999),
			block_tag("Notification messages",
			{
				undefined_tag("Text Strings", 9999),
			}),
		}),
		block_tag("Prededicated Resources: Bitmap tags",
		{
			undefined_tag("Bitm", 9999),
		}),
		undefined_tag("Source Color", 9999),
		undefined_tag("Destination Color", 9999),
		long_tag("Accumulate Zoom Scale X"),
		long_tag("Accumulate Zoom Scale Y"),
		long_tag("Refraction Scale X"),
		long_tag("Refraction Scale Y"),
		undefined_tag("Mouse Cursor Definition", 9999),
	});
};
