#include "wigl.h"

using namespace tag_definitions;

namespace tag_definitions
{
	tag_collection* wigl_group = new tag_collection(
	"wigl",
	{
		
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		long_tag("Unknown"),
		short_tag("Auto typing text: time"),
		short_tag("Auto typing text: words per line"),
		long_tag("Auto typing text: size"),
		long_tag("Auto typing text: Alpha?"),
		long_tag("Red"),
		long_tag("Green"),
		long_tag("Blue"),
		long_tag("Unknown"),
		long_tag("Blur blending speedUnknown"),
		long_tag("Blur blending speedUnknown"),
		long_tag("Blur color opacity"),
		long_tag("Blur Red"),
		long_tag("Blur Green"),
		long_tag("Blur Blue"),
		long_tag("Unknown"),
		long_tag("Unknown"),
		long_tag("Unknown"),
		block_tag("Dialogs",
		{
			undefined_tag("Dialog Group", 9999),
			short_tag("Unknown"),
			short_tag("Window type? (wgit palette)"),
			undefined_tag("Unic Text", 9999),
			undefined_tag("Default Header", 9999),
			undefined_tag("Default Content", 9999),
			undefined_tag("Option 1", 9999),
			undefined_tag("Option 2", 9999),
			block_tag("Variations",
			{
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				short_tag("Unknown"),
				undefined_tag("Header", 9999),
				undefined_tag("Content", 9999),
				undefined_tag("Option 1", 9999),
				undefined_tag("Option 2", 9999),
			}),
		}),
		undefined_tag("Selection Change Sound 1", 9999),
		undefined_tag("Forward Sound 1", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Advance Sound", 9999),
		undefined_tag("Back Sound", 9999),
		undefined_tag("Shortcut Sound", 9999),
		undefined_tag("Selection Change Sound 2", 9999),
		undefined_tag("Keyboard Click Sound", 9999),
		undefined_tag("Message Recieved Sound", 9999),
		undefined_tag("Forward Sound 2", 9999),
		undefined_tag("Countdown Sound", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Pickup Health Sound", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Global Bitmaps", 9999),
		undefined_tag("Global Unic", 9999),
		block_tag("Virtual Keyboard Buttons settings",
		{
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Selected button Brightness"),
			short_tag("Unknown"),
			block_tag("Button switching effects",
			{
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
			short_tag("Selected button Brightness"),
			short_tag("Unknown"),
			block_tag("Button switching effects",
			{
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Unknown"),
			block_tag("Unknown",
			{
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
		}),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Button effects?",
		{
			short_tag("Unknown"),
			short_tag("Unknown"),
			short_tag("Brightness"),
			short_tag("Unknown"),
			block_tag("Button switching effects?",
			{
				short_tag("Unknown"),
				short_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
				long_tag("Unknown"),
			}),
		}),
		block_tag("Buttons Palette",
		{
			undefined_tag("Skin", 9999),
		}),
		undefined_tag("unic", 9999),
		undefined_tag("Built-in Gametype Names", 9999),
		undefined_tag("Unknown", 9999),
		undefined_tag("Unknown", 9999),
		block_tag("Unknown",
		{
			short_tag("Unknown"),
			short_tag("Unknown"),
		}),
		short_tag("Main window Header text #Font type#"),
		short_tag("Pop up window Header text #Font type#"),
		short_tag("Pop up window Confirmation dialog Header text #Font type#"),
		short_tag("Unknown Header Fontype"),
		long_tag("Unknown Header Fontype"),
		long_tag("Red Header Tittle"),
		long_tag("Green Header Tittle"),
		long_tag("Blue Header Tittle"),
		short_tag("Main Window Header text Coord Y"),
		short_tag("Main window Header text Coord X"),
		short_tag("Pop up window Confirmation dialog Header text Coord X"),
		short_tag("Pop up window Confirmation dialog Header text Coord X"),
		short_tag("Main window Buttons Coord Y"),
		short_tag("Main window Buttons Coord x"),
		short_tag("Main window Buttons Coord Y"),
		short_tag("Main window Buttons Coord X"),
		short_tag("Game setup Header text Coord Y"),
		short_tag("Game setup Header text Coord X"),
		short_tag("Pop up Confirmation dialog Header text Coord Y"),
		short_tag("Pop up Confirmation dialog Header text Coord X"),
		short_tag("Game setup Buttons Coord Y"),
		short_tag("Game setup Buttons Coord X"),
		short_tag("Keyboard window Buttons Coord Y"),
		short_tag("Keyboard window Buttons Coord X"),
		short_tag("Unknown Header text coords Y"),
		short_tag("Unknown Header text coords X"),
		short_tag("Unknown Header text coords Y"),
		short_tag("Unknown Header text coords X"),
		short_tag("Unknown Button coords Y"),
		short_tag("Unknown Button coords X"),
		short_tag("Campaign/gametype settings Pop Up dialog Button Y"),
		short_tag("Campaign/gametype settings Pop Up dialog Button X"),
		short_tag("Pop Up confirmation dialog Header Text Y"),
		short_tag("Pop Up confirmation dialog Header Text X"),
		short_tag("Unknown Header text coords Y"),
		short_tag("Unknown Header text coords X"),
		short_tag("Unknown Button coords Y"),
		short_tag("Unknown Button coords X"),
		short_tag("Pop up Confirmation dialog Button Coord Y"),
		short_tag("Pop up Confirmation dialog Button Coord X"),
		undefined_tag("Music", 9999),
		undefined_tag("Music duration time?", 9999),
	});
};
